<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div class="tabbable" id="tabs">
		<ul>
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Details');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Notes');?></a></li> 
		</ul>
	
	
		<div style="display: block" class="" id="tab1"> 
		    
		    <div class="span6"> 
		        <?php echo $form->creationdate->render() ?>
		        <?php echo $form->number->render() ?>
		        <?php echo $form->invoice_id->render() ?>
		    </div>
		    <div class="span6"> 
		        <?php echo $form->total_net->render() ?>
		        <?php echo $form->total_vat->render() ?>
		        <?php echo $form->total->render() ?>
	        </div>
	        
	        
	        <table>
				<tr>
					<td width="10%"><?php echo $this->form->quantity->setDecorators(array('Simple'));?></td>
					<td width="70%"><?php echo $this->form->description->setDecorators(array('Simple'));?></td>
					<td width="10%"><?php echo $this->form->price->setDecorators(array('Simple'));?></td>
					<td width="10%"><?php echo $this->form->vat->setDecorators(array('Simple'));?></td>
				</tr>
			</table>
		
		</div>
		
		<div class="tab-pane" id="tab2">
		 	<?php echo $this->simplegrid($this->items) ?>
		</div>
		
		<div class="tab-pane" id="tab3">
		 	<?php echo $form->note->render() ?>
		</div>
		
	</div>
	
	<?php echo $form->creditnote_id->render()?>
</form>
</div>
