<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Payments');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Notes');?></a></li> 
		</ul>
	
	    <div class="tab-content">
    		<div class="tab-pane active" id="tab1"> 
    		    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
    		        <?php echo $form->creationdate->render() ?>
    		        <?php echo $form->expiringdate->render() ?>
    		        <?php echo $form->number->render() ?>
    		        <?php echo $form->company->render() ?>
    		        <?php echo $form->category_id->render() ?>
    		    </div>
    		    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
    		        <?php echo $form->total_net->render() ?>
    		        <?php echo $form->total_vat->render() ?>
    		        <?php echo $form->total->render() ?>
    		        <?php echo $form->status_id->render() ?>
    		        
    		        <?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
    			        <span style="<?php echo !empty($this->attachment) ? "display:none" : ""?>">
    			        	<?php echo $form->document->render() ?>
    			        </span>
    			        
    			        <?php if($this->attachment): ?>
    			        		<p><a class="badge" href="/documents/purchase_invoices/<?php echo $this->attachment ?>"><?php echo $this->attachment ?></a> 
    			        		<a class="btn btn-danger" href="/admin/purchases/deletefile/id/<?php echo $this->id ?>"><?php echo $this->translate('Delete')?></a></p>
    			        <?php endif; ?>
    			    <?php endif;?>
    	        </div>
    	        
    		   	<?php echo $form->purchase_id->render()?>
    		
    		</div>
    		
    		<div class="tab-pane" id="tab2">
    			<?php echo $form->paymentdate->render() ?>
    		 	<?php echo $form->method_id->render() ?>
    		</div>
    		
    		<div class="tab-pane" id="tab3">
    		 	<?php echo $form->note->render() ?>
    		</div>
    	</div>
	</div>
</form>
