<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-danger\">".$this->translate('field') ." <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	<div class="tabbable" id="tabs">
		
		<ul class="nav nav-tabs"> 
			<li><a data-toggle="tab" href="#tab1" class="default-tab current"><?php echo $this->translate('Main');?></a></li>
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Custom Fields');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Information');?></a></li> 
		</ul>
		
        <div class="tab-content">
    	    <div class="tab-pane" id="tab1"> 
    	        <div class="row">
        	        <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
        	            <?php echo $form->isp_id->render() ?>
        	            <?php echo $form->type_id->render() ?>
        	            <?php echo $form->name->render() ?>
        	            <?php echo $form->ip->render()?>
        				<?php echo $form->panel_id->render()?> 
        				<?php echo $form->cost->render()?>
        				<?php echo $form->buy_date->render()?>
        	        </div>
        	        <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
        	            <?php echo $form->netmask->render()?>
        	            <?php echo $form->host->render()?>
        	            <?php echo $form->domain->render()?>
        	            <?php echo $form->status_id->render()?>
        	            <?php echo $form->datacenter->render()?>
        	            <?php echo $form->max_accounts->render()?>
        	            <?php echo $form->is_default->render()?>
        	        </div>
    	        </div>
    	    </div>
        
    	    <div class="tab-pane" id="tab2"> 
    	    	<?php echo $form->attributes->render() ?>
    	    </div>
        
    	    <div class="tab-pane" id="tab3"> 
    	    	<?php echo $form->description->render() ?>
    	    </div>
       		<?php echo $form->server_id->render()?>
       	</div>
	</div>
</form>
