<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">
	
	<? if( $form->isErrors() ): ?>
		<div class="messages">    
		   <? foreach( $form->getElements() as $field){
		         $errors = array();
		   	     if($field->hasErrors()){
		        	foreach( $field->getErrors() as $error){
		        		$errors[] = $this->translate($error);
		        	}
		            echo "<div class=\"alert alert-error\">".$this->translate('field') ." <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
		        }   
		    } ?>
		</div>    
	<? endif; ?>
	
	<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
		
		<div id="tabs">
			<ul>
				<li><a href="#tab1"><?=$this->translate('Main');?></a></li> 
			</ul>
	    
		    <div id="tab1"> 
		    	<fieldset class="column-left"> 
		            <?php echo $form->paymentdate->render()?>
		            <?php echo $form->order_id->render()?>
		            <?php echo $form->customer_id->render()?>
		            <?php echo $form->confirmed->render()?>
	            </fieldset>
	            
	            <fieldset class="column-right"> 
		            <?php echo $form->income->render()?>
		            <?php echo $form->outcome->render()?>
		            <?php echo $form->bank_id->render()?>
		            <?php echo $form->reference->render()?>
	            </fieldset>
	            
	            <div class="clear"></div>
		    </div>
		    
	   		<?php echo $form->payment_id->render()?>
	   	</div>
	</form>
</div>	
