<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>
	
<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
	
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
		</ul>
		
        <div class="tab-content">
		    <div class="tab-pane active" id="tab1"> 
		    	<div class="col-sm-6 col-xs-12"> 
		            <?php echo $form->paymentdate->render()?>
		            <?php echo $form->order_id->render()?>
		            <?php echo $form->customer_id->render()?>
		            <?php echo $form->confirmed->render()?>
	            </div>
	            
	            <div class="col-sm-6 col-xs-12"> 
		            <?php echo $form->income->render()?>
		            <?php echo $form->outcome->render()?>
		            <?php echo $form->bank_id->render()?>
		            <?php echo $form->reference->render()?>
	            </div>
            </div>
	    </div>
	    
   		<?php echo $form->payment_id->render()?>
   	</div>
</form>
