
<div class="row">
    <div class="col-lg-12 col-md-12 col-xs-12">
	    <?php if(!empty($this->data)):?>
	        <?php echo $this->data['body']; ?>
	    <?php else: ?>
	       <h2><?php echo $this->translate("Ooops! Sorry, it's our fault!")?></h2>
	       <br>
	       <p><?php echo $this->translate("The page that you are trying to get is no longer available.")?></p>
	       <p><?php echo $this->translate("What can I do?")?></p><br>
	       <ul>
	           <li><a class="btn btn-primary" href="/"><?php echo $this->translate("Go to the homepage")?></a></li>
	           <li><a class="btn btn-primary" href="/customer/login"><?php echo $this->translate("Login as customer")?></a></li>
	       </ul>
	    <?php endif;?>
    </div>
</div>