
<div class="row">
    <div class="col-lg-8 col-md-8 col-xs-12">
	    <?php if(!empty($this->data)):?>
	        <div id="content"><?php echo $this->data['body']; ?></div>
	    <?php else: ?>
	       <h2><?php echo $this->translate("Ooops! Sorry, it's our fault!")?></h2>
           <br>
           <p><?php echo $this->translate("The page that you are trying to get is no longer available.")?></p>
           <p><?php echo $this->translate("What can I do?")?></p><br>
           <ul>
               <li><a class="btn btn-primary" href="/"><?php echo $this->translate("Go to the homepage")?></a></li>
               <li><a class="btn btn-primary" href="/customer/login"><?php echo $this->translate("Login as customer")?></a></li>
           </ul>
	    <?php endif;?>
    </div>    
    
    <div class="col-lg-4 col-md-4 col-xs-12">
        <?php $this->blocks()->showblock("right") ?>
    </div>
</div>