<?php $form = $this->form;?>

<div class="row">
	<div class="col-lg-12">
		<h2><?= $this->translate('Domains Bulk Registration'); ?></h2>
		<p><?= $this->translate("It's easy to register your new domain names in bulk."); ?></p>
		<small><?= $this->translate("Just enter your names in the field below. One domain name for each row."); ?></small>
	</div>
	
	<div class="col-lg-12">
		<form method="<?php echo $form->getMethod() ?>" class="custom" action="<?php echo $form->getAction()?>">
			<p><?php echo $form->domains->render()?></p>
				
			<?php $tlds = DomainsTlds::getList(); ?>
			<ul class="list-inline">
			<?php foreach ($tlds as $id=>$tld): ?>
				<li><label for="<?php echo $id?>"><input type="checkbox" name="tlds[]" value="<?php echo $id?>" id="<?php echo $id?>"> .<?php echo strtoupper($tld)?></label></li>
			<?php endforeach; ?>
			</ul>
			
			<p><?= $this->translate("When the 'Search' button is clicked, please be patient while we check domain availability."); ?></p>
			<p align="right"><?php echo $form->bulksearch->render()?></p>
		</form>
	</div>
</div>