<h2><?php echo $this->translate('Domain Registration Order'); ?></h2>
<p><b><?php echo $this->translate("Create your new order with the following domains."); ?></b></p>

<?php
	$form = $this->form;
	$domains = $this->domains;
?>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	<table class="table">
		<thead>
			<tr>
			    <td width="10px"><input type="checkbox" class="selectall" title="<?php echo $this->translate('Select all')?>"></td>
			    <td><?php echo $this->translate('Domain')?></td>
			    <td><?php echo $this->translate('Status')?></td>
			    <td><?php echo $this->translate('Billing Cycle')?></td>
			    <td><?php echo $this->translate('Price')?></td>
			</tr>
		</thead>
		<tbody>
		<?php foreach($domains as $domain):?>
		
			<?php 
				if(is_null($domain['isavailable'])){
					$class = "";
					$mex = $this->translate("To be check");
				}elseif($domain['isavailable']){
					$class = "register";
					$mex = $this->translate("Domain Registration");
					$status = $this->translate("Domain Available");
				}else{
					$class = "transfer";
					$mex = $this->translate("Domain Transfer");
					$status = $this->translate("Domain is ready to be transferred");
				}
			?>
			<tr class="domain <?php echo $class?>">
			    <td><input type="checkbox" checked value="<?php echo $domain['domain_id']; ?>" id="items" name="item[]"></td>
			    <td>
			        <?php if($domain['isavailable']): ?>
			        	<h4><?php echo $domain['domain']; ?></h4>
			        <?php else: ?>
			        	<h4><a target="_blank" href="http://www.<?php echo $domain['domain']; ?>"><?php echo $domain['domain']; ?></a></h4>
			        <?php endif;?>
			        
			        <div id="dtemp_<?php echo $domain['domain_id']; ?>"><?php echo $this->translate($mex) ?></div>
			        <?php if(!$domain['isavailable']): ?>
			        	<!-- <div class="whoisinfo"><a target="_blank" href="http://whois.domaintools.com/<?php echo $domain['domain']; ?>"><?php echo $this->translate("Get more information") ?></a></div> -->
			        <?php endif;?>
			    </td>
			    <td>
			         <?php if(!$domain['isavailable']): ?>
			             <input name="authcode[]" type="text" placeholder="<?php echo $this->translate('Authentication Code') ?>" title="<?php echo $this->translate('Please write here your AuthCode in order to transfer the domain')?>" name="authcode" class="form-control" />
			         <?php else:?>
			             <input type="hidden" name="authcode[]"/>
			             <p><?php echo $this->translate('Domain Available') ?></p>
			         <?php endif;?>
			    </td>
			    <td><?php echo $form->billing_id->render(); ?></td>
			    <td><?php echo $this->currency($domain['price'], array('currency' => Settings::findbyParam('currency'))); ?></td>
			</tr>
		<?php endforeach;?>
	    </tbody>
	</table>
	<br><br>
	<p align="right"><?php echo $form->order->render(); ?></p>
</form>
