<h2><?= $this->translate('Domains Bulk Registration'); ?></h2>
<p><?= $this->translate("It's easy to register your new domain names in bulk."); ?></p><br/><br/>
<small><?= $this->translate("Just enter your names in the field below. One domain name for each row."); ?></small><br/><br/>
<?php $form = $this->form;?>


<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	<p><?php echo $form->domains->render()?></p>
	
	<div class="tlds">
		
		<ul class="tldlist">
		<?php $tlds = DomainsTlds::getList(); ?>
		
		<li class="boxrounded selectalltldsitems"><input type="checkbox" name="selectall" class="selectalltlds" value=""> <span>
		<?php echo $this->translate('Select All')?></span></li>
		
		<?php foreach ($tlds as $id=>$tld): ?>
			<li class="boxrounded"><input type="checkbox" name="tlds[]" value="<?= $id?>"> <span><?= strtoupper($tld)?></span></li>
		<?php endforeach; ?>
		</ul>
	</div>
	<div class="clear"></div>
	
	<br><br>
	<p><?= $this->translate("When the 'Search' button is clicked, please be patient while we check domain availability."); ?></p>
	<br><br>
	<p align="right"><?php echo $form->bulksearch->render()?></p>
</form>
