<?php $form = $this->form; ?>

<div class="toptools">
    <div class="search">
    	<?=$this->searchbox();?> 
	</div>
</div>
<div class="clear"></div>
<div class="headtitle"></div>

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"notification error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<h2><?php echo $this->domainame ?></h2>
<p></p>

<div id="tabs" class="tabWrapper">
	
	<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	    
	    <div id="tab1" class="tabContent"> 
	    	<div class="label"><?php echo $this->translate('Main') ?></div>
          	<div class="column">
          		<br/><br/>
            	<?php echo $this->verticalgrid($this->datagrid)?><br/>
	           	
				<?php
					if($this->autorenew){
						echo '<div class="notification infos">' . $this->translate("This domain will be renewed at the expiring day. Auto-Renew setting is active. You can edit this option until 3 days before the expiring day.") . '</div>';
					}else{
						echo '<div class="notification error">' . $this->translate('This domain will be not renewed at the expiring day.') . '</div>';
					} 
				?>            
	            
	            <?php
	                if($this->days >= 3){
	                    echo $form->autorenew->render();
	                }else{
	                    if(!$this->autorenew){
	                        echo $form->autorenew->render();
	                    }
	                }
	            ?> 
	            <p align="right"><?php echo $form->submit->render()?></p>
            </div> 
	    </div>
	    
	    <div id="tab2" class="tabContent">
	    	<div class="label"><?php echo $this->translate('DNS Zones') ?></div>
	    	<div class="column">
	    		<h3><?php echo $this->translate('DNS Zones') ?></h3>
		    	<p><?= $this->translate('Here you can set your DNS Zones. All the edits have need one hour at least.') ?></p>
	            <table class="zebratable">
	            	<tr>
	            		<td width="250"><?php echo $form->dnsform->subdomain->setDecorators(array('Simple'))?>.<?php echo $this->domainame ?></td>
	            		<td><?php echo $form->dnsform->zones->setDecorators(array('Simple'))?></td>
	            		<td><?php echo $form->dnsform->target->setDecorators(array('Simple'))?></td>
	            		<td><?php echo $form->submit->setDecorators(array('Simple'))?></td>
	            	</tr>
	            </table>
	            <br/><br/>
	           	<?php echo $this->Simplegrid($this->dnsgrid)?>
	           	<?php if(!empty($this->dnsgrid['records'])):?>
	            	<br/><br/><a class="button confirm" href="/domains/updatednszone/id/<?php echo $this->domain_id ?>"><?php echo $this->translate('Update DNS Zones')?></a>
	            <?php endif;?>
	    	</div>
	    </div>
	    
	    
	    <div id="tab3" class="tabContent">
	    	<div class="label"><?php echo $this->translate('Messages') ?></div>
	     	<div class="column">
	     		<h3><?php echo $this->translate('Messages') ?></h3>
	     		<p><?= $this->translate('Here you can see all the questions and replies about this service/domain') ?></p>
            	<div class="messages-list">
	            	<?php echo $this->bbslist($this->messages); ?>
	            </div>
	            <div class="messages-text">
	            	<?php echo $form->note->render()?>
	            </div>
	            <p align="right"><?php echo $form->submit->render()?></p>
            </div>
	    </div>
	    
	    
	    <?php if(!empty($this->orders['records'])): ?>
		    <div id="tab4" class="tabContent">
		    	<div class="label"><?php echo $this->translate('Orders') ?></div>
		    	<div class="column">
		    		<h3><?php echo $this->translate('Orders') ?></h3>
		    		<p><?php echo $this->translate('List of all the orders where the domain appears.') ?></p>
		    		<?php echo $this->Simplegrid($this->orders)?>
		    	</div>
		    </div>
	    <?php endif; ?>
	    
	    <?php if(!empty($this->services['records'])): ?>
		    <div id="tab5" class="tabContent">
		    	<div class="label"><?php echo $this->translate('Services') ?></div>
		    	<div class="column">
		    		<h3><?php echo $this->translate('Services') ?></h3>
			    	<p><?php echo $this->translate('List of all the services attached to the domain.') ?></p>
			    	<?php echo $this->Simplegrid($this->services)?>
		    	</div>
		    </div>
	    <?php endif; ?>
	    
	    <?php if(!empty($this->tasks['records'])): ?>
		    <div id="tab6" class="tabContent">
		    	<div class="label"><?php echo $this->translate('Tasks') ?></div>
		    	<div class="column">
		    		<h3><?php echo $this->translate('Tasks') ?></h3>
			    	<p><?php echo $this->translate('List of all the tasks executed.') ?></p><br/>
			    	<?php echo $this->Simplegrid($this->tasks)?>
		    	</div>
		    </div>
		<?php endif; ?>
		
	    <div id="tab7" class="tabContent">
	    	<div class="label"><?php echo $this->translate('Options') ?></div>
	    	<div class="column">
	    		<h3><?php echo $this->translate('Options') ?></h3>
		    	<p><?php echo $this->translate('In this section you can execute various operation with your domain name.')?></p><br/>
		    	 
				<table>        
		            <?php if(empty($this->is_maintained)): ?>
		            <tr>
		            	<td>
		            		<h5><?php echo strtoupper($this->translate('Transfer here your domain')) ?></h5>
		            		<p><?php echo $this->translate('To transfer your own domain name here you have to set the AuthInfo Code in the following textbox area.') ?></p>
		            		<div class="authinfocode-wrapper">          
				            	<?php echo $form->authinfocode->render()?>
				            	<p align="right"><?php echo $form->submit->render()?></p>
				            </div>
		            	</td>
		            </tr>
		            <?php else: ?>
		            <tr>
		            	<td valign="top" width="200"><strong><?php echo strtoupper($this->translate('Protect your domain')) ?></strong></td>
		            	<td><p><?php echo $this->translate('To protect against theft the domain, the domain is placed in a state that does not allow the transfer. If another registrar requires the transfer of the domain, the operation will be automatically rejected. If you wish to transfer the domain to a new registrar, remove the protection. In this state, the domain will not be protected and another registrar may request the transfer.') ?></p></td>
		            	<td valign="top" width="245"><a class="red-button confirm" href="/domains/register/id/<?php echo $this->domain_id?>/do/lockDomain"><?php echo strtoupper($this->translate('Protect your domain')) ?></a></td>
		            </tr>
		            <tr>
		            	<td valign="top" width="200"><strong><?php echo strtoupper($this->translate('Request the AUTHINFO')) ?></strong></td>
		            	<td>
		            		<p><?php echo $this->translate('The authinfocode is a code that is assigned at the time of registration and that uniquely identifies the domain. The Registrar must notify the Registrant of this code, necessary to perform all operations. Without this code you cannot transfer this domain.') ?></p>
		            		<?php if(!empty($this->authinfocode)): ?>
		            			<div class="authinfocode"><h5><?php echo $this->translate('Authinfo')?></h5><pre><?php echo $this->authinfocode; ?></pre></div>
		            		<?php endif;?>
		            	</td>
		            	<td valign="top" width="245">
		            		<?php if(empty($this->authinfocode)): ?>
		            			<a class="red-button confirm" href="/domains/register/id/<?php echo $this->domain_id?>/do/unlockDomain"><?php echo strtoupper($this->translate('Request the AUTHINFO')) ?></a>
		            		<?php else: ?>	
		            			<a class="red-button confirm" href="/domains/register/id/<?php echo $this->domain_id?>/do/unlockDomain"><?php echo strtoupper($this->translate('Request a NEW AUTHINFO')) ?></a>
		            		<?php endif; ?>
		            	</td>
		            </tr>
		            <?php endif;?>
		        </table>
		     </div>
	    </div>    
	   
	   <?php echo $form->domain_id->render()?>
	</form>
</div>
