<div class="row">
	<div class="large-12 column">
	    <h3>
	    <?php 
	            echo $this->translate($this->title);
	            if(!empty($this->name)){
	                echo ": " . $this->name;
	            } 
	        ?>
	    </h3>
	    <p><?php echo $this->translate($this->description);?></p>
	</div>

	<div class="large-12 column">
		<?php echo $this->Domainsgrid($this->domains);?>
	</div>
</div>