<?php echo $this->render('includes/header.phtml') ?>

<body>
    
    <?php echo $this->blocks()->showblock('admin_startbody');?> 	
    
    <header class="navbar">
    	<div class="navbar-inner">
    		<div class="container">
    			<div class="nav-collapse collapse">
		   			<ul class="nav">
		   				<li><a class="brand" href="/admin">ShineISP</a></li>
		   				<li class="divider-vertical"></li>
	    			</ul>
	    			
	    			<?php echo $this->navigation()->menu()->setPartial(array('partials/navigation.phtml', 'admin'))->render(); ?>
	    			
		   			<ul class="nav pull-right">
		   				<li class="dropdown">
		   					<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-envelope"></i></a>
		   				</li>
                        <li class="dropdown hidden-xs"><?php echo $this->searchbox();?></li>
		   				<li class="dropdown hidden-xs"><?php echo $this->profile();?></li>
	    			</ul>
	    		</div>
	    	</div>
	    </div>
    </header>
    
    <div class="container-fluid">
        <div class="row-fluid">
            
            <div id="sidebar-left" class="span2">
                <?php echo $this->blocks()->showblock('admin_startsidebar');?> 	
                <?php echo $this->languageswitcher();?>
				<?php echo $this->blocks()->showblock('admin_endsidebar');?> 
            </div>
            
            <div id="content" class="span10">
                
                <div class="row-fluid">
                     <div class="span4"><?php echo  $this->breadCrumb();?></div>
                     <div class="span8 pull-right"><?php echo $this->customers(); ?></div>
                </div>
                
                <div id="loading" class="row-fluid hidden">
                     <div class="span12"><?php echo $this->Message($this->translate('Please wait a moment...'))?></div>
                </div>
                
                <?php echo $this->blocks()->showblock('admin_beforecontent');?> 	
			    
				<?php echo $this->layout()->content ?> 
				
				<?php echo $this->blocks()->showblock('admin_endcontent');?> 	
            </div>
        </div>
    </div>
	<?php echo $this->blocks()->showblock('admin_endbody');?> 	
</body>

<?php echo $this->render('includes/footer.phtml') ?>