<?php echo $this->render('includes/header.phtml') ?>

<body>
    
    <?php echo $this->blocks()->showblock('admin_startbody');?> 	
    
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span2">
                <?php echo $this->blocks()->showblock('admin_startsidebar');?> 	
				<?php echo $this->navigation()->menu()->setPartial(array('partials/navigation.phtml', 'admin'))->render(); ?>
				<?php echo $this->blocks()->showblock('admin_endsidebar');?> 
            </div>
            <div class="span10">
                
                <div class="row-fluid">
                     <div class="span4"><?php echo  $this->breadCrumb();?></div>
                     <div class="span8"><?php echo $this->customers(); ?></div>
                </div>
                
                <div id="loading" class="row-fluid hidden">
                     <div class="span12"><?php echo $this->Message($this->translate('Please wait a moment...'))?></div>
                </div>
                <?php echo  $this->profile();?>
                
                <?php echo $this->blocks()->showblock('admin_beforecontent');?> 	
			    <?php echo $this->searchbox();?>
				<?php echo $this->layout()->content ?> 
				<?php echo $this->languageswitcher();?>
				<?php echo $this->blocks()->showblock('admin_endcontent');?> 	
            </div>
        </div>
    </div>
	<?php echo $this->blocks()->showblock('admin_endbody');?> 	
</body>

<?php echo $this->render('includes/footer.phtml') ?>