<?= $this->doctype() ?>
<html>

<head>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>
    <?= $this->headScript() ?>
    <?=$this->blocks()->showblock('admin_htmlhead');?>
</head>
<body>
    <div class="container" id="body-wrapper"> 
        <div class="loginbox">
        	<?= $this->layout()->content ?>
        </div>  
   </div>
</body>
</html>
