<?php echo $this->doctype() ?>
<html>

<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->blocks()->showblock('admin_htmlhead');?>
</head>

<body>
 	
 	<?php echo $this->blocks()->showblock('admin_startbody');?> 
   
    <div class="container" id="body-wrapper"> 
    	<?php echo $this->blocks()->showblock('admin_beforecontent');?> 
        <div class="loginbox">
        	<?php echo $this->layout()->content ?>
        </div>
        <?php echo $this->blocks()->showblock('admin_endcontent');?>   
   </div>
   <?php echo $this->render('includes/footer-bar.phtml') ?>
   <?php echo $this->blocks()->showblock('admin_endbody');?>
</body>
</html>
