<h2><?php echo $this->translate('Sign Up') ?></h2>
<p><?php echo $this->translate('Please %s or fill the applicant form below.', '<a href="/customer/login">' . $this->translate('login') . '</a>')?></p>
<br/>

<?php $form = $this->form; ?>
<? if( $form->isErrors() ): ?>
	<h4><?php echo $this->translate('We have found some errors')?>:</h4>
    <div class="messages">    
       <? foreach( $form->getElements() as $field){
             $errors = array();
             if($field->hasErrors()){
                foreach( $field->getErrors() as $error){
                    $errors[] = $this->translate($error);
                }
                echo "<div class=\"alert alert-warning alert-dismissable\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
            }   
        } ?>
    </div>    
<? endif; ?>

    <form method="<?php echo $form->getMethod() ?>" id="contacts" action="<?php echo $form->getAction()?>">
            <div class="row"> 
                <h4><?php echo $this->translate('General')?></h4>
                <div class="col-lg-6">
	                <?php echo $form->firstname->render() ?>
	                <?php echo $form->lastname->render()?>
	                <?php echo $form->email->render()?>
	                <?php echo $form->password->render()?>
                </div>
            
                <div class="col-lg-6">
                	<?php echo $form->legalform->render()?>
                    <?php echo $form->company_type_id->render()?>
                    
                	<?php echo $form->company->render()?>
                    <?php echo $form->vat->render()?>
                    <?php echo $form->taxpayernumber->render()?>
                </div>
            </div>
            
        	<?php if($this->hasdomain): ?>
            <div class="row">
                <h4><?php echo $this->translate('Personal data')?></h4>
                <small><?php echo $this->translate('Your personal data are mandatories to register or transfer a domain name.')?></small>
                <div class="col-lg-12 col-md-12 col-xs-12">
	                <?php echo $form->birthdate->render()?>
	                <?php echo $form->birthplace->render()?>
	                <?php echo $form->birthdistrict->render()?>
	                <?php echo $form->birthcountry->render()?>
	                <?php echo $form->birthnationality->render()?>
	                <?php echo $form->gender->render()?>
	            </div> 
            </div>
            <?php endif; ?>
            
            <div class="row">
	            <div class="col-lg-6">
	                <h4><?php echo $this->translate('Address')?></h4>
	                <?php echo $form->address->render()?>
	                <?php echo $form->code->render()?>
	                <?php echo $form->city->render()?>
	                <?php echo $form->area->render()?>
	                <?php echo $form->country_id->render()?>
	            </div>
	            
	           <div class="col-lg-6">
	                <h4><?php echo $this->translate('Contacts')?></h4>
	                 <?php echo $form->contact->render()?>
	                 <?php echo $form->contacttypes->render()?>
	           </div>
	       </div>
	  		
	  	   <div class="text-right"><?php echo $form->submit->render()?></div> 
      
      <?php echo $form->customer_id->render()?>
    </form>
