<?php $contact = $this->contact?>
<div id="wizard" class="whitebox boxrounded">
    <h3><a href="/dashboard"><?php echo $contact['company']?></a></h3>
 	<br/>
 	<p><?php echo $this->translate('Dear %s welcome back in to our store!', $contact['firstname'] . " " . $contact['lastname'] )?></p>
    <small><?php echo $this->translate('Your registered email is %s', $contact['email'])?></small>
    <p><a href="/dashboard"><?php echo $this->translate('Dashboard')?></a></p>
    
    <div class="separatorShadow"></div>
    <br/><br/><br/>
    <p align="right"><a class="button" href="/cart/payment"><?php echo $this->translate('Complete Order')?></a></p>
    
    <div class="clearfix"></div>
</div>