<?php $form = $this->form; ?>
<div class="row">
	<div class="col-lg-12">
		<h2><?php echo $this->translate('Register your own domain')?></h2>
		<small><?php echo $this->translate('Type the domain name in the input box shown below and follow only 3 steps.')?></small><br><br>
		
		<?php if(!empty($this->mex)):?>
			<div class="alert alert-warning alert-dismissable"><?php echo $this->mex ?>  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button></div>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
	    <form method="<?php echo $form->getMethod() ?>" id="domainselector" class="form-group" action="<?php echo $form->getAction()?>">
	        <div class="row collapse">
		        <div class="col-lg-9"><?php echo $form->domain->setDecorators(array('ViewHelper'))?> </div>
	        	<div class="col-lg-3"><?php echo $form->tlds->setDecorators(array('ViewHelper'))?></div>
			</div>
			
			<ul class="list-unstyled">
	             <li>
	                 <label for="register"><input id="register" type="radio" name="mode" checked value="register"> <?php echo $this->translate('I would like to register this domain.')?></label>
	                 <p><?php echo $this->translate('Register now your domain name now and every year we will renew it automatically. Anyway you can disable this option by your Control Panel.')?></p>
	             </li>
	             <li>
	                 <label for="transfer"><input id="transfer" type="radio" name="mode" value="link"> <?php echo $this->translate('I am this domain\'s owner.')?></label>
	                 <p><?php echo $this->translate('Write your own domain name previosly registered with another company.')?></p>
	             </li>
	             <li>
	                 <label for="notregister"><input id="notregister" type="radio" name="mode" value="nothing"> <?php echo $this->translate('Do not register or transfer domain')?></label>
	                 <p><?php echo $this->translate('Skip domain transfer or registration. Only a blank hosting is bought.')?></p>
	             </li>
	         </ul>
	         <br><br>
	        <input type="submit" class="btn btn-default" value="<?php echo $this->translate('Continue Order') ?>" id="check" name="check">
	    </form>
	</div>
</div>