<?php $cart = $this->cart ?>
<?php $form = $this->form; ?>
<?php $i = 0; ?>

<h3><?php echo $this->translate('Order Summary'); ?></h3>
<p><?php echo $this->translate('Complete the order choosing your preferite payment method.')?></p>

<div class="row">
	<div class="large-12 column">
		<form method="<?php echo $form->getMethod() ?>" id="cartsummary" action="<?php echo $form->getAction()?>">
			<div id="payment_methods" class="">
			   <h5><?php echo $this->translate('Payment Methods')?></h5>
			   <div class="section-container accordion" data-section="accordion">
			    <?php foreach($this->gateways as $gateway): ?>
			        <section class="<?php echo $i==0 ? "active": ""; ?>">
			        	<p class="title" data-section-title><a href="#"><?php echo $gateway['name']?></a></p>
			        	<div class="content" data-section-content>
				        	<input type="radio" <?php echo $i==0 ? "checked": ""; ?> name="payment" value="<?php echo $gateway['bank_id'] ?>"/> <label for="<?php echo $gateway['bank_id'] ?>"><?php echo $gateway['name']?></label>
				        	<br/><?php echo $gateway['description']?>
				        </div>
				     </section>
				     <?php $i++?>
			    <?php endforeach;?>
			    </div>
			</div>
			
			<?php echo $form->note->render()?>
			
			<label for="conditions"><?php echo $this->translate('Legal Conditions'); ?></label>
			<textarea cols="80" readonly title="" class="textarea" rows="20" id="conditions" name="conditions"><?php echo Settings::findbyParam('conditions') ?></textarea>

			<br/>
			<?php echo $form->submit->render()?>
		</form>
	</div>
</div>

