<?php $cart = $this->cart ?>
<?php $form = $this->form; ?>

<h4><?php echo $this->translate('Shopping Cart'); ?></h4> 
<p><?php echo $this->translate('Complete the order choosing your preferite payment method.')?></p>

<div class="row">
	<div class="large-12 column">
		<?php $form = $this->form; ?>
		<? if( $form->isErrors() ): ?>
		    <div class="messages">    
		       <? foreach( $form->getElements() as $field){
		             $errors = array();
		             if($field->hasErrors()){
		                foreach( $field->getErrors() as $error){
		                    $errors[] = $this->translate($error);
		                }
		                echo "<div data-alert class=\"alert-box alert\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
		            }   
		        } ?>
		    </div>    
		<? endif; ?>
	</div>
</div>

<div class="row">
	<div class="large-12 column">
		<table>
			<thead>
				<tr>
					<td></td>
					<td><?php echo $this->translate('Product Name') ?></td>
					<td></td>
					<td><?php echo $this->translate('Unit Price') ?></td>
					<td><?php echo $this->translate('Taxes') ?></td>
					<td><?php echo $this->translate('Qty') ?></td>
					<td><?php echo $this->translate('Subtotal') ?></td>
					
				</tr>
			</thead>
			<tbody>
				<?php foreach ($cart->getItems() as $item): ?>
					<?php $subtotal = $item->getSubtotal(); ?>
					<?php $months = !empty($subtotal['isrecurring']) && !empty($subtotal['months']) ? " x " . $subtotal['months'] . " " . $this->translate('Months') : null; ?>
					<?php $domain = $item->getDomain(); ?>
					<?php $domainame = !empty($domain['domain']) ? "<br/>" . $domain['domain'] : null ?>
					<tr>
						<td width="50"><?php echo $this->media()->ProductImage($item->getId(), 50, 50, true);?></td>
						<td>
							<?php echo $item->getName() ?> 
							<?php echo $domainame ?>
						</td>
						<td width="20"><a class="gen-enclosed foundicon-trash" href="/cart/summary/del/<?php echo $item->getId() ?>">&nbsp;</a></td>
						<td><?php echo $subtotal['unitprice'] ?> <?php echo $months?></td>
						<td><?php echo $subtotal['taxes'] ?></td>
						<td><?php echo $item->getQty() ?></td>
						<td align="right"><?php echo $subtotal['subtotal'] ?></td>
					</tr>
				<?php endforeach;?>
			</tbody>
			<tfoot>
				<tr>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</tfoot>
		</table>
	</div>
</div>

<div class="row">
	<div class="large-8 column">
		<a class="button small" href="/<?php echo !empty($this->lastproduct) ? $this->lastproduct . ".html" : null ?>"><?php echo $this->translate('Continue Shopping')?></a>
		<a class="button small" href="/cart/clear"><?php echo $this->translate('Clear Shopping Cart')?></a>
	</div>
	<div class="large-4 column">
		<table>
			<tr>
				<td><?php echo $this->translate('Subtotal') ?></td>
				<td align="right"><?php echo $cart->getSubtotal() ?></td>
			</tr>
			<?php if($cart->getSetupfee()): ?>
			<tr>
				<td><?php echo $this->translate('Setup fee') ?></td>
				<td align="right"><?php echo $cart->getSetupfee() ?></td>
			</tr>
			<?php endif;?>
			<tr>
				<td><?php echo $this->translate('Taxes') ?></td>
				<td align="right"><?php echo $cart->getTaxes() ?></td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Grandtotal') ?></td>
				<td align="right"><?php echo $cart->getGrandtotal() ?></td>
			</tr>
			<tr>
				<td align="center" colspan="2"><a class="button success" href="/cart/checkout"><?php echo $this->translate('Proceed to Checkout')?></a></td>
			</tr>
		</table>
	</div>
</div>

<?php Zend_Debug::dump($cart)?>
