<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"notification error\">".$this->translate('field') ." <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>


<form class="multiple_select_form" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div id="tabs">
		<ul>
			<li><a href="#tab1"><?=$this->translate('Main');?></a></li> 
			<li><a href="#tab2"><?=$this->translate('Customer');?></a></li> 
			<li><a href="#tab3"><?=$this->translate('Domains');?></a></li> 
			<li><a href="#tab4"><?=$this->translate('Messages');?></a></li> 
			<li><a href="#tab5"><?=$this->translate('Private Notes');?></a></li> 
			<li><a href="#tab6"><?=$this->translate('Configurations');?></a></li> 
		</ul>
	
	    <div class="ui-tabs-hide" id="tab1">  
	        <fieldset class="column-left"> 
			    <?php echo $form->order_id->render()?>		
				<?php echo $form->product_id->render()?>        
				<?php echo $form->status_id->render()?>
	            <?php echo $form->quantity->render()?>
	        </fieldset>
	        
	        <fieldset class="column-right"> 
	            <?php echo $form->billing_cycle_id->render()?>
	            <?php echo $form->date_start->render()?>
	            <?php echo $form->date_end->render()?>
	            <?php echo $form->autorenew->render()?>
	        </fieldset>   
	        <div class="clear"></div>     
	    </div>
	    
	    <div class="ui-tabs-hide" id="tab2"> 
	        <?= $this->verticalgrid($this->owner_datagrid);?>
	        <div class="clear"></div>
	    </div>  
	    
	    <div class="ui-tabs-hide" id="tab3"> 
            <?php echo $form->domains->render()?>
            <a id="add_items" class="button"><?= $this->translate('Add')?></a> <a id="remove_items" class="button"><?= $this->translate('Remove')?></a>
            <?php echo $form->domains_selected->render()?>
	        <div class="clear"></div>
	    </div>
	    
	    <div class="ui-tabs-hide" id="tab4"> 
            <?php echo $this->bbslist($this->messages); ?>
            <?php echo $form->message->render()?>
	        <div class="clear"></div>
	    </div>    
	    
	    <div class="ui-tabs-hide" id="tab5"> 
	        <?php echo $form->note->render()?>
	        <div class="clear"></div>
	    </div>    
	    
	    <div class="ui-tabs-hide" id="tab6"> 
	        <?php echo $form->setup->render()?>
	        <div class="clear"></div>
	    </div>    
	   
	   <?php echo $form->detail_id->render()?>
	</div>
</form>
</div>