<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') . ": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form class="multiple_select_form" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Products');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Options');?></a></li> 
			<li><a data-toggle="tab" href="#tab4"><?php echo $this->translate('Blocks');?></a></li> 
		</ul>
        <div class="tab-content">
    	    <div class="tab-pane active" id="tab1">
    	        <div class="row"> 
                    <div class="col-sm-6 col-xs-12">
                        <?php echo $form->name->render()?>
                        <?php echo $form->parent->render()?>
                        <?php echo $form->uri->render()?>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                        <?php echo $form->googlecategs->render()?>
                        <?php echo $form->position->render()?>
                        <?php echo $form->enabled->render()?>
                    </div>
                </div>
                <?php echo $form->description->render()?>
    	    </div>
    	    
    	    <div class="tab-pane" id="tab2"> 
    	    	<?php echo $form->products->render()?>
    	    </div>
    	    
    	   <div class="tab-pane" id="tab3">
    	   		 <?php echo $form->keywords->render()?>
                <?php echo $form->wikipages->render() ?>
    	   </div>      
    	    
    	   <div class="tab-pane" id="tab4">
    	   		<?php echo $form->blocks->render() ?>
    	   </div>      
	   </div>
	   <?php echo $form->category_id->render()?>
   </div>
</form>