<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">
	<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
		
		<div id="tabs">
			<ul>
				<li><a href="#tab1"><?=$this->translate('Main');?></a></li> 
			</ul>
	    
		    <div id="tab1"> 
		        <?php echo $form->name->render() ?>
		        <?php echo $form->legalform_id->render() ?>
		    </div>
		</div>
	</form>
</div>
