<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>


<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<?php if(!empty($this->help)): ?><li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Help');?></a></li> <?php endif;?>
		</ul>
		
        <div class="tab-content">
    	    <div class="tab-pane active" id="tab1"> 
    	        <?php echo $form->name->render() ?>
    	        <?php echo $form->active->render() ?>
    	        <?php if(!empty($form->settings)): ?>
    			   <?php echo $form->settings->render()?>
    	    	<?php endif;?>
        	</div>
        	
        	<?php if(!empty($this->help)): ?>
    	    	<div class="tab-pane" id="tab2"> 
    	    		<?php echo $this->help ?>
    	    	</div>
        	<?php endif;?>
        </div>
         <?php echo $form->registrars_id->render() ?>
     </div>
</form>
