<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<?php echo $this->render('partials/formerrors.phtml'); ?>


<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Options');?></a></li> 
		</ul>
    
	    <div class="tab-pane active" id="tab1"> 
	        <?php echo $form->class->render() ?>
	        <?php echo $form->username->render() ?>
	        <?php echo $form->password->render() ?>
    	</div>
    
	    <div id="tab2"> 
	        <?php echo $form->credit->render() ?>
	        <?php echo $form->testmode->render() ?>
	        <?php echo $form->active->render() ?>
		    <?php echo $form->registrars_id->render()?>
    	</div>
    </div>
</form>

</div>