<div id="dashboard">
	<div class="portlets">

		<div class="column column-large" id="col0">
			<?php echo $this->summary(); ?>
		</div>
		
		<div class="column column-fixed column-large" id="col1">
			<div class="portlet" id="processing_order">
		        <?php $statuses = array(Statuses::id("processing", "orders"), Statuses::id("pending", "orders"), Statuses::id("paid", "orders"));?>
				<?php echo $this->widget(Orders::Last($statuses), $this->translate ("Processing Orders"), "orders")?>
			</div>
			
			<div class="portlet" id="new_orders">
		        <?php $statuses = array(Statuses::id("tobepaid", "orders")); ?>
				<?php echo $this->widget(Orders::Last($statuses), $this->translate ("New Orders"), "orders")?>
			</div>
			
			<div class="portlet" id="last_tickets">
				<?php echo $this->widget(Tickets::Last(null, 5), $this->translate ("Last Tickets"), "tickets", array('ticket_id'))?>
			</div>
			
			
			<div class="portlet" id="last_domain_tasks">
				<?php echo $this->widget(DomainsTasks::Last(), $this->translate ("Domain Tasks"), "domainstasks", array('task_id'))?>
			</div>
			
			<div class="portlet" id="last_panel_tasks">
				<?php echo $this->widget(PanelsActions::Last(), $this->translate ("Panel Tasks"), "panelsactions", array('action_id'))?>
			</div>
			
		</div>
		
		
		
		<div class="column column-floated column-medium" id="col2">
			
	        <div class="portlet" id="expiring_domain">
				<?php echo $this->widget(Domains::getExpiringDomains(null, 7, -1, 5), $this->translate ("Expiring Domains"), "domains", array('domain_id'))?>
			</div>
			
			<div class="portlet" id="order-messages">
				<?php echo $this->widget(Messages::Last('orders'), $this->translate ("Order Messages"), "orders")?>
			</div>
			
			<div class="portlet" id="domain-messages">
				<?php echo $this->widget(Messages::Last('domains'), $this->translate ("Domain Messages"), "domains")?>
			</div>
			
			<div class="portlet" id="customers_parade">
				<?php echo $this->widget(Customers::Hitparade(), $this->translate ("Customer Hit Parade"), "customers", array('customer_id'))?>
			</div>
	        
			<div class="portlet" id="customer_summary">
				<?php echo $this->widget(Customers::summary(), $this->translate ("Customers Summary"), "customers")?>
			</div>
			<div class="portlet" id="notes">
				<?php echo $this->widget(Notes::summary($this->user['user_id']), $this->translate ("Notes"), "notes")?>
			</div>
		</div>
	
		<div class="column column-floated column-medium" id="col3">
			<div class="portlet" id="ticket_summary">
				<?php echo $this->widget(Tickets::summary(), $this->translate ("Ticket Summary"), "tickets")?>
			</div>
	        
			<div class="portlet" id="summary_domains">
				<?php echo $this->widget(Domains::summary(), $this->translate ("Domain Summary"), "domains")?>
			</div>
	        
			<div class="portlet" id="product_reviews">
				<?php echo $this->widget(Reviews::summary(), $this->translate ("Product Review Summary"), "reviews")?>
			</div>
		</div>
		
		
		
		<div class="column column-floated column-little" id="col4">
			<div class="portlet" id="googleanalytics_yesterday">
				<?php 
						
					$startdate = date('Y-m-d');
					$startdate = strtotime ( '-1 day' , strtotime ( $startdate ) ) ;
					$startdate = date ( 'Y-m-d' , $startdate );
					
					echo $this->widget(Shineisp_Plugins_Google_Analytics_Main::getNewReturnVisitors($startdate, date('Y-m-d')), $this->translate ("Google Analytics (yesterday)"));
					
				?>
			</div>
		</div>
        <div class="column column-floated column-little" id="col5">
        	<div class="portlet" id="googleanalytics_last30days">
				<?php 
					
					$startdate = date('Y-m-d');
					$startdate = strtotime ( '-1 month' , strtotime ( $startdate ) ) ;
					$startdate = date ( 'Y-m-d' , $startdate );
					
					echo $this->widget(Shineisp_Plugins_Google_Analytics_Main::getNewReturnVisitors($startdate, date('Y-m-d')), $this->translate ("Google Analytics (last 30 days)"));
					
				?>
			</div>
        </div>
		<div class="column column-floated column-little" id="col6">
			<div class="portlet" id="googleanalytics_lastyear">
				<?php 
						
					$startdate = date('Y-m-d');
					$startdate = strtotime ( '-1 year' , strtotime ( $startdate ) ) ;
					$startdate = date ( 'Y-m-d' , $startdate );
					
					echo $this->widget(Shineisp_Plugins_Google_Analytics_Main::getNewReturnVisitors($startdate, date('Y-m-d')), $this->translate ("Google Analytics (last year)"));
				?>
			</div>
		</div>
    </div>      
                                 
</div> 
<div class="clearfix"></div>