<div class="navbar navbar-default navbar-fixed-top">
	<div class="navbar-header">
        <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <?php echo $this->logo()?>
    </div>

    <div class="collapse navbar-collapse">
	    <ul class="nav navbar-nav navbar-nav-left">
	    	<?php echo $this->webmenu();?>
	    </ul>
	    <ul class="nav navbar-nav navbar-nav-right">
	    	<?php echo $this->cart()?>
    		<?php echo $this->profile();?>
    		<?php echo $this->languageswitcher() ?>
    		<?php echo $this->searchbar()?>
    	</ul>
    </div>
	
</div>