<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
    <?php echo $this->render('includes/top.phtml') ?>
    <?php echo $this->render('includes/content-header.phtml') ?>
        
    <div class="row">
    	<aside class="large-9 columns">
    		<?php echo $this->blocks()->showblock('contentstart');?>
	        <?php echo $this->layout()->content ?>
        	<?php echo $this->blocks()->showblock('contentend');?>
    	</aside>
    	
    	<div class="large-3 columns" role="content">
    		<?php echo $this->blocks()->showblock('right');?>
    	</div>
    	
    	<?php echo $this->blocks()->showblock('beforefooter');?>
	    <footer>
	    	<?php echo $this->footer();?>
	        <?php echo $this->blocks()->showblock('footer');?>
	    </footer><!-- End #footer -->
	    <?php echo $this->blocks()->showblock('endfooter');?>
	    
	</div>
        
    <?php echo $this->blocks()->showblock('endbody');?>

<?php echo $this->render('includes/endpage.phtml') ?>