<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
    <?php echo $this->render('includes/top.phtml') ?>
        
    <div class="row">
    	<div class="large-9 columns" role="content">
    		<?php echo $this->blocks()->showblock('contentstart');?>
	        <?php echo $this->layout()->content ?>
        	<?php echo $this->blocks()->showblock('contentend');?>
    	</div>
    	
    	<aside class="large-3 columns">
    		<?php echo $this->blocks()->showblock('right');?>
    	</aside>
    	
	</div>
    
    <?php echo $this->blocks()->showblock('beforefooter');?>
    <footer class="row">
    	<?php echo $this->footer();?>
        <?php echo $this->blocks()->showblock('footer');?>
    </footer><!-- End #footer -->
    <?php echo $this->blocks()->showblock('endfooter');?>
    
    <?php echo $this->blocks()->showblock('endbody');?>

<?php echo $this->render('includes/endpage.phtml') ?>