<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
	<?php echo $this->render('includes/top.phtml') ?>
	
    <div class="row">
    	<?php echo $this->slideshow();?>
		
		<?php # echo $this->render('includes/content-header.phtml') ?>
		<?php echo $this->blocks()->showblock('beforecontent');?>
		<div class="row">
			<?php echo $this->Messages($this->mex)?>
            <?php echo $this->blocks()->showblock('contentstart');?>
            <?php echo $this->layout()->content ?>
            <?php echo $this->blocks()->showblock('contentend');?>
		</div> 
				
		<?php echo $this->blocks()->showblock('beforefooter');?>
        <div class="row">
            <?php echo $this->footer();?>
            <?php echo $this->blocks()->showblock('footer');?>
        </div><!-- End #footer -->
        
        <?php echo $this->blocks()->showblock('endfooter');?>
        
    </div>	<!-- End #main-container -->
    
    <?php echo $this->blocks()->showblock('endbody');?>
    
<?php echo $this->render('includes/endpage.phtml') ?>

