<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
	<?php echo $this->render('includes/top.phtml') ?>
	<?php echo $this->render('includes/content-header.phtml') ?>
	
    <div class="row">
    	<div class="large-12 columns">
    		<?php echo $this->slideshow();?>
		</div>
		
		<?php echo $this->blocks()->showblock('beforecontent');?>
		
		<div class="large-12 columns">
			<?php echo $this->Messages($this->mex)?>
            <?php echo $this->blocks()->showblock('contentstart');?>
            <?php echo $this->layout()->content ?>
            <?php echo $this->blocks()->showblock('contentend');?>
		</div> 
				
		<?php echo $this->blocks()->showblock('beforefooter');?>
		
        <footer class="large-12 columns">
            <?php echo $this->footer();?>
            <?php echo $this->blocks()->showblock('footer');?>
        </footer><!-- End #footer -->
        
        <?php echo $this->blocks()->showblock('endfooter');?>
        
    </div>	<!-- End #main-container -->
    
    <?php echo $this->blocks()->showblock('endbody');?>
    
<?php echo $this->render('includes/endpage.phtml') ?>

