<?= $this->doctype() ?>

<html>
	<head>
	    <?= $this->headTitle() ?>
	    <?= $this->headMeta() ?>
	    <?= $this->headLink() ?>
	    <?= $this->headStyle() ?>
	    <?= $this->headScript() ?>
	   
	    <?=$this->blocks()->showblock('admin_htmlhead');?>
		
		<!--[if IE 8]>
			<link rel="stylesheet" href="/skins/admin/base/css/ie8.css" />
		<![endif]-->
		
		<!-- Set the viewport width to device width for mobile -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	</head>