
	<div class="row">
		<div class="large-4 column">
			<?php if(!empty($this->subcategory)): ?>
				<span><?php echo $this->translate('%s Subcategories', $this->category['name'])?></span>
			    <select class="redirect" id="subcategories">
			    <option value=""><?php echo $this->translate('Select ...') ?></option>
			    <?php foreach ($this->subcategory as $category): ?>
			    	<option value="/categories/<?php echo $category['uri']?>.html"><?php echo $category['name']?></option>
			    <?php endforeach;?>
			    </select>
			<?php endif;?>
		</div>
		<div class="large-8 column">
			<dl class="sub-nav right">
				<dt><?php echo $this->translate('List view')?>:</dt>
				<dd class="active"><a href="/categories/setlayout/mode/list"><img src="<?=$this->paths('skin')?>/images/list.png" alt="<?php echo $this->translate('List') ?>" title="<?php echo $this->translate('List') ?>" /></a></dd>
	    		<dd><a href="/categories/setlayout/mode/thumbs"><img src="<?=$this->paths('skin')?>/images/thumbnail.png" alt="<?php echo $this->translate('Thumb') ?>" title="<?php echo $this->translate('Thumb') ?>" /></a></dd>
	    	</dl>
		</div>
	</div>
