
	<div class="row">
		<div class="col-lg-4">
			<?php if(!empty($this->subcategory)): ?>
				<form name="catselector" class="custom dropdown">
				    <select class="medium redirect" id="subcategories">
				    <option value=""><?php echo $this->translate('%s Subcategories', $this->category['name'])?></option>
				    <?php foreach ($this->subcategory as $category): ?>
				    	<option value="/categories/<?php echo $category['uri']?>.html"><?php echo $category['name']?></option>
				    <?php endforeach;?>
				    </select>
				</form>
			<?php endif;?>
		</div>
		<div class="col-lg-8">
			<ul class="pull-right list-inline">
				<li class="<?php echo !empty($this->layoutmode) && $this->layoutmode == "list" ? "active" : "" ?>"><i class="glyphicon glyphicon-th-list"></i> <a href="/categories/setlayout/mode/list"><?php echo $this->translate('List') ?></a></li>
	    		<li class="<?php echo !empty($this->layoutmode) && $this->layoutmode == "thumbs" ? "active" : "" ?>"><i class="glyphicon glyphicon-th"></i> <a href="/categories/setlayout/mode/thumbs"><?php echo $this->translate('Thumb') ?></a></li>
	    	</ul>
		</div>
	</div>
