
<div class="row">
	<div class="large-12 column">
		<h2><?php echo $this->category['name'];?></h2>
    	<div class="catshortdescription"><?php echo $this->category['description']?></div>
    	
    	<?php echo $this->render('categories/header.phtml') ?>
	</div>
</div>

<div class="row" id="products">
	<div class="large-12 column">
    
	    <?php if(is_array($this->products) && count($this->products)>0): ?>
		
			<ul id="thumbs" class="no-bullet">
				<?php foreach($this->products as $products): ?>
				    <li>
				    	<div class="large-4 column">
				    		<h4><a href="/products/<?php echo $products['uri'] ?>.html"><?php echo $products['name'] ?></a></h4>
				    		<?php echo $this->media()->ProductImage($products['product_id'], 250, 250);?>
					        <?php echo $this->prices()->getAllPricesInfo($products['product_id']); ?><br/>
					        <a class="small button" href="/products/<?php echo $products['uri'] ?>.html"><?php echo $this->translate('Learn more') ?></a>
				        </div>
				    </li>
				<?php endforeach; ?>
			</ul>
		
		<?php else:?>
		   <p><?php echo $this->translate('No product has been found.')?></p>
		   <p><a href="/"><?php echo $this->translate('Homepage')?></a></p>
		<?php endif;?>
	</div>
</div>

<div class="row">
	<div class="large-12 column">
		<?php echo $this->pager ?>
	</div>
</div>