<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form class="multiple_select_form" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Content');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Options');?></a></li> 
			<li><a data-toggle="tab" href="#tab4"><?php echo $this->translate('Layouts');?></a></li> 
			<li><a data-toggle="tab" href="#tab5"><?php echo $this->translate('Blocks');?></a></li> 
		</ul>

	    <div class="tab-content"> 
    	    <div class="tab-pane active" id="tab1"> 
                <?php echo $form->title->render()?>
                <?php echo $form->var->render()?>
                <?php echo $form->language_id->render()?>
                <?php echo $form->parent_id->render()?>
                <?php echo $form->active->render()?>
    	    </div>
        
    	    <div class="tab-pane" id="tab2"> 
    	   		<?php echo $form->body->render()?>
    	    </div>
        
    	    <div class="tab-pane" id="tab3"> 
    	        <?php echo $form->blog->render()?>
    	   		<?php echo $form->showinmenu->render()?>
                <?php echo $form->showonrss->render()?>
    	    	<?php echo $form->keywords->render()?>
    	    </div>
        
    	    <div class="tab-pane" id="tab4"> 
    	        <?php echo $form->pagelayout->render()?>
                <?php echo $form->layout->render()?>
                <?php echo $form->xmllayout->render()?>
    	    </div>
        
    	    <div class="tab-pane" id="tab5"> 
                <?php echo $form->blocks->render()?>
    	    </div>
        </div>
   		<?php echo $form->page_id->render()?>
   	</div>
</form>
