<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form class="multiple_select_form" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div class="tabbable" id="tabs">
		<ul>
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Content');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Options');?></a></li> 
			<li><a data-toggle="tab" href="#tab4"><?php echo $this->translate('Layouts');?></a></li> 
		</ul>

	    <div class="tab-pane active" id="tab1"> 
            <?php echo $form->title->render()?>
            <?php echo $form->var->render()?>
            <?php echo $form->language_id->render()?>
            <?php echo $form->pagelayout->render()?>
            <?php echo $form->layout->render()?>
            <?php echo $form->parent_id->render()?>
            <?php echo $form->active->render()?>
	    </div>
    
	    <div class="tab-pane" id="tab2"> 
	   		<?php echo $form->body->render()?>
            <a class="toggle button" href="#"><?php echo $this->translate('Disable/Enable Wysiwyg')?></a>
	    </div>
    
	    <div class="tab-pane" id="tab3"> 
	   		<?php echo $form->showinmenu->render()?>
            <?php echo $form->showonrss->render()?>
	    	<?php echo $form->keywords->render()?>
	    </div>
    
	    <div class="tab-pane" id="tab4"> 
            <?php echo $form->blocks->render()?>
            <?php echo $form->xmllayout->render()?>
	    </div>
    
   		<?php echo $form->page_id->render()?>
   	</div>
</form>
</div>