<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form class="multiple_select_form" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
		</ul>
		
        <div class="tab-content">
    	    <div class="tab-pane active" id="tab1"> 
                <?php echo $form->email->render()?> 
                <?php echo $form->subscriptiondate->render()?>
    	    </div>
        
       		<?php echo $form->subscriber_id->render()?>
       </div>
	</div>
</form>