<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form class="multiple_select_form" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
    <div class="tabbable" id="tabs">
    	<ul class="nav nav-tabs">
    		<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
    		<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Queue');?></a></li> 
    	</ul>
        <div class="tab-content">
    	    <div class="tab-pane" id="tab1"> 
                <?php echo $form->subject->render()?> 
                <?php echo $form->sendat->render()?>
                <?php echo $form->sent->render()?>
                <?php echo $form->message->render()?>
                <?php echo $form->sendagain->render()?>
        	</div>
        
    	    <div class="tab-pane" id="tab2">
    	        <div>
    	            <?php echo $this->simplegrid($this->queue)?> 
    	        </div>
    	        
    	    </div>
        </div>
       <?php echo $form->news_id->render()?>
    </div>
</form>