<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form class="multiple_select_form" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div id="tabs">
		<ul>
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Queue');?></a></li> 
		</ul>

	    <div id="tab1"> 
            <?php echo $form->subject->render()?> 
            <?php echo $form->sendat->render()?>
            <?php echo $form->sent->render()?>
            <?php echo $form->message->render()?>
            <?php echo $form->sendagain->render()?>
    	</div>
    
	    <div class="tab-pane" id="tab2">
	        <fieldset>
	            <?php echo $this->simplegrid($this->queue)?> 
	        </fieldset>
	        <div class="clear"></div>
	    </div>
    </div>
   <?php echo $form->news_id->render()?>
</form>


</div>