<?php $summary = $this->summary ?>
<?php echo  $this->render('partials/header.phtml') ?>

<div class="container" id="page_wrapper">
	<div class="row" id="page">
		<div class="col-lg-12 col-md-12" id="content">
    		<div class="panel panel-default">
                <div class="panel-heading"><?php echo $this->translate('Summary')?></div>
                <div class="panel-body">
    				<h2><?php echo $this->translate('Setup has been Completed!')?></h2>
    				<p><?php echo $this->translate('ShineISP has been configured. Now you can start to customize your ShineISP configuration.')?></p><br/>
    				
    				<h4><?php echo $this->translate('Administration Credentials')?></h4>
    				<p>
    					<?php echo $this->translate('Please write down your own credentials to login at the administration control panel.')?><br/>
    					<?php echo $this->translate('Email')?>: <b><?php echo $summary['email'] ?></b><br/>
    					<?php echo $this->translate('Password')?>: <b><?php echo $summary['password'] ?></b>
    				</p>
    				<a href="https://twitter.com/intent/tweet?screen_name=shine_software&text=Thank%20you%20guys%20for%20#ShineISP%20downloaded%20from%20@github.%20I%20have%20installed%20your%20#isp%20#software%20in%20our%20server!" class="twitter-mention-button" data-size="large" data-related="shine_software">Tweet to @shine_software</a>
					<a href="https://twitter.com/shine_software" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @shine_software</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

    				<div class="text-right">
    					<a class="btn btn-success" target="_blank" href="/admin"><?php echo $this->translate('Administration')?></a>
    					<a class="btn btn-primary" target="_blank" href="/"><?php echo $this->translate('Public Site')?></a>
    				</div>
    			</div>
			</div>
			<?php echo  $this->render('partials/footer.phtml') ?>			
		</div>	
	</div>
</div>