<?php $summary = $this->summary ?>

<div class="row" id="page_wrapper">
	<div class="col-lg-12" id="page">
		<?php echo  $this->render('partials/header.phtml') ?>		
		<div id="content">
    		<div class="panel panel-default">
                <div class="panel-heading"><?php echo $this->translate('Summary')?></div>
                <div class="panel-body">
    				<h2><?php echo $this->translate('Setup has been Completed!')?></h2>
    				<p><?php echo $this->translate('ShineISP has been configured. Now you can start to customize your ShineISP configuration.')?></p><br/><br/>
    				
    				<h4><?php echo $this->translate('Administration Credentials')?></h4>
    				<p>
    					<?php echo $this->translate('Please write down your own credentials to login at the administration control panel.')?><br/>
    					<?php echo $this->translate('Email')?>: <b><?php echo $summary['email'] ?></b><br/>
    					<?php echo $this->translate('Password')?>: <b><?php echo $summary['password'] ?></b>
    				</p><br/><br/>
    				
    				<h4><?php echo $this->translate('ShineISP Disclaimer')?></h4>
    				<p><?php echo nl2br(Shineisp_Commons_Utilities::readfile(PUBLIC_PATH . "/../LICENSE")) ?></p><br/>
    				<a class="adminbutton btn btn-primary" target="_blank" href="/admin"><?php echo $this->translate('Administration')?></a>
    				<a class="publicbutton btn btn-primary" target="_blank" href="/"><?php echo $this->translate('Public Site')?></a>
    			</div>
			</div>
			<?php echo  $this->render('partials/footer.phtml') ?>			
		</div>	
	</div>
</div>