<?php $form = $this->form; ?>

<?php echo $this->render('partials/header.phtml') ?>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12s">
		<h3><?php echo $this->translate('Contact us')?></h3>
		<p><?php echo $this->translate('Fill the form with your requests, we will reply you as soon as possible.')?></p>
		<div class="row">
			<form method="<?php echo $form->getMethod() ?>" class="custom dropdown" action="<?php echo $form->getAction()?>">
			    <div class="col-lg-6">
			        <?php echo $form->fullname->render() ?>
			        <?php echo $form->company->render() ?>
			        <?php echo $form->email->render() ?>
			    </div>
			    <div class="col-lg-6">
			    	<?php echo $form->subject->render() ?>
			        <?php echo $form->message->render() ?>
			        <?php echo $form->captcha->render() ?>
			        <?php echo $form->submit->render() ?>
			    </div>
			</form>
		</div>
	</div>
</div>