<?php $form = $this->form ?>
<?php echo  $this->render('partials/header.phtml') ?>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" id="setup">
	<div class="container" id="page_wrapper">
		<div class="row" id="page">
			<div class="col-lg-12 col-md-12" id="content">
				<div class="progress" style="display:none">Please wait a moment...</div>
				
				<?php if($this->error):?>
					 <div class="alert alert-danger alert-dismissable">
					       <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					       <?php echo $this->error?>
					  </div>
				<?php endif;?>
				
				<div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('Database Connection')?></div>
                    <div class="panel-body">
    					<?php echo $form->hostname->render() ?>
    					<?php echo $form->username->render() ?>
    					<?php echo $form->password->render() ?>
    					<?php echo $form->database->render() ?>
					
    					<input type="button" class="btn btn-danger" id="chkdb" value="<?php echo $this->translate('Check DB Connection')?>">
    					<div id="chkdbresult"></div>
				    </div>
				</div>
				<div class="submit"><?php echo $form->submit->render() ?></div>
				<?php echo  $this->render('partials/footer.phtml') ?>			
			</div>		
		</div>
	</div>
</form>
