
<div class="body-content-homepage">
	<div class="generic-help">
		<br/><br/>
		<h4><?php echo $this->translate('What can you do?'); ?></h4>
		<p><?php echo $this->translate('Have no fear, help is near! There are many ways you can get back on track with our store.'); ?></p>
		
		<ul>
			<li><?php echo $this->translate('Go back to the previous page.'); ?></li>
			<li><?php echo $this->translate('Follow this link to get you back on track!'); ?> <a href="/"><?php echo $this->translate('Homepage')?></a></li>
		</ul>

		<p><?php echo $this->translate('Tell us which is the broken link. You will not be contacted by us about this report.')?></p><br/>
		<p><a class="blue-button" href="/contacts"><?php echo $this->translate('Contact us')?></a> <a class="blue-button" href="/"><?php echo $this->translate('Homepage')?></a> </p>
	</div> 
</div>
