<div class="row">
	<div class="col-lg-12"><br/>
		<h3><?php echo $this->translate('Reset your password')?></h3>
		
		<?php if( $this->mex ): ?>
		    <?php echo "<div class=\"alert alert-info\">" . $this->mex . "</div>"; ?>
		<?php endif;?>
		
		<form id="passwordform" action="/index/password" method="post">
			<p><?php echo $this->translate('Write your email in the follow text box in order to reset your password.')?></p>
			<div class="col-lg-8">
			    <input type="text" class="form-control" placeholder="<?php echo $this->translate('Email')?>" name="account" id="account" >
			</div>
			<div class="col-lg-4">
			    <input type="submit" class="btn btn-success" value="<?php echo $this->translate('Reset your password')?>" id="passwordreset" />
			    <a href="/index/login/" class="btn btn-info"><?php echo $this->translate('Login page')?></a>
			</div>
		</form>
	</div>
</div>