<div class="row">
	<div class="col-lg-12"><br/>
		<h4><?= $this->translate('Reset your password')?></h4>
		
		<?php if( $this->mex ): ?>
		    <?php echo "<div data-alert class=\"alert-box " . $this->mextype . "\">" . $this->mex . "</div>"; ?>
		<?php endif;?>
		
		<form id="passwordform" action="/index/password" method="post">
			<p><?php echo $this->translate('Write your email in the follow text box in order to reset your password.')?></p>
			<div class="col-lg-8">
			    <input type="text" placeholder="<?php echo $this->translate('Email')?>" name="account" id="account" >
			</div>
			<div class="col-lg-4">
			    <input type="submit" value="<?php echo $this->translate('Reset your password')?>" id="passwordreset" class="button small">
			</div>
		</form>
	</div>
</div>