<div class="col-content">
	<h2><?= $this->translate('Reset your password')?></h2>
	
	<? if( $this->mex ): ?>
	    <?php echo "<div class=\"notification " . $this->mextype . "\">" . $this->mex . "</div>"; ?>
	<?php endif;?>
	
	<form id="passwordform" action="/index/password" method="post">
		<fieldset>
		    <p><?= $this->translate('Write your email in the follow text box in order to reset your password.')?></p><br>
		    <label for="account"><?= $this->translate('Email')?></label><br>
		    <input type="text" value="" name="account" id="account" class="text-input medium-input">
		    
		    <input type="submit" value="<?= $this->translate('Reset your password')?>" id="passwordreset" class="button bigbtn">
		</fieldset>
	</form>
</div>