<h4><?php echo $this->translate('Login or Create a new Account')?></h4><hr>   
	
<div class="row">  
	
    <div class="large-6 column">
    	<fieldset class="login">
	        <h2><?=$this->translate('Create a new Account')?></h2>
	        <p>
	            <?php echo $this->translate('By creating an account with our store, you will be able to move through the checkout process faster, view and track your orders in your account and more.')?>
	        </p>
	        
	        <a class="button" href="/customer/signup"><?= $this->translate('Create an Account') ?></a>
		</fieldset>
    </div>
    
    <div class="large-6 column">
        <?php if($this->form):?>
            
            <? if( $this->message ): ?>
               <?php echo "<div data-alert class=\"alert-box alert\">" . $this->message . "</div>"; ?>
            <?php endif;?>
            
            <? $form = $this->form; ?>
                 
                    <form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
                        <fieldset class="login">
                            <h2><?=$this->translate('Login')?></h2>
                            <p><?echo $this->translate('Sign in to get subscribed services.')?></p>
                            <?php echo $form->email->render() ?>
                            <?php echo $form->password->render() ?>
                            <p align="right"><a href="/index/password"><?php echo $this->translate('Forgot your password?'); ?></a>
                            <?php echo $form->login->render() ?>
                        </fieldset>
                    </form>
            <?php endif;?>
    </div>
</div>


