<?php $form = $this->form; ?>

<div class="row">   
	<div class="col-lg-12">   
	    <h3><?php echo $this->translate('New Account')?></h3>
	    <p><?php echo $this->translate('Create your new account today!'); ?> </p>
	    <p align="right"><?php echo $this->translate('Already registered?'); ?> <a href="/customer/login"><?php echo $this->translate('Sign in'); ?></a></p>
	    <?php if( $this->message ): ?>
        	<?php echo "<div class=\"alert alert-warning alert-dismissable\">" . $this->message . "</div>"; ?>
        <?php endif;?>
            
		<? if( $this->form->isErrors() ): ?>
			<div class="messages">    
			   <? foreach( $this->form->getElements() as $field){
			         $errors = array();
			   	     if($field->hasErrors()){
			        	foreach( $field->getErrors() as $error){
			        		$errors[] = $this->translate($error);
			        	}
			            echo "<div class=\"alert alert-warning alert-dismissable\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
			        }   
			    } ?>
			</div>    
		<? endif; ?>
	</div>
</div>

<div class="row"> 	
    <?php if($this->form):?>
        <form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
            <div class="col-lg-6">
                <?php echo $form->firstname->render() ?>
                <?php echo $form->lastname->render() ?>
                <?php echo $form->email->render() ?>
                <?php echo $form->password->render() ?>
                <?php echo $form->password_confirm->render() ?>
                <p>
                <?php 
                    // ReCaptcha
                    $privKey = Settings::findbyParam('recaptcha_private_key');
                    $pubKey = Settings::findbyParam('recaptcha_public_key');
                    
                    if(!empty($pubKey) && !empty($privKey)){
                        echo $form->captcha->render();
                    }
                ?>
                </p>
            </div>
            <div class="col-lg-6">
                <?php echo $form->company->render() ?>
                <?php echo $form->legalform->render() ?>
                <?php echo $form->company_type_id->render() ?>
                <?php echo $form->taxpayernumber->render() ?>
                <?php echo $form->vat->render() ?><br/><br/>
                <div class="text-right"><?php echo $form->signup->render() ?></div>
            </div>
        </form>
    <?php endif;?>
</div>

