<div class="signup-form">   
    <h1><?php echo $this->translate('New Account')?></h1>
    <p><?php echo $this->translate('Create your new account today!'); ?> </p>
    
    
	<? if( $this->form->isErrors() ): ?>
		<div class="messages">    
		   <? foreach( $this->form->getElements() as $field){
		         $errors = array();
		   	     if($field->hasErrors()){
		        	foreach( $field->getErrors() as $error){
		        		$errors[] = $this->translate($error);
		        	}
		            echo "<div data-alert class=\"alert-box alert\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
		        }   
		    } ?>
		</div>    
	<? endif; ?>
    
    <div class="new-account">
        <?php if($this->form):?>
            <p  class="signin"><?php echo $this->translate('Already registered?'); ?> <a href="/customer/login"><?php echo $this->translate('Sign in'); ?></a></p>
            
            <? if( $this->message ): ?>
               <?php echo "<div data-alert class=\"alert-box alert\">" . $this->message . "</div>"; ?>
            <?php endif;?>
            
            <? $form = $this->form; ?>
                    <form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
                        <div class="column medium">
                            <?php echo $form->firstname->render() ?>
                            <?php echo $form->lastname->render() ?>
                            <?php echo $form->taxpayernumber->render() ?>
                            <?php echo $form->email->render() ?>
                            <?php echo $form->password->render() ?>
                            <?php echo $form->password_confirm->render() ?>
                        </div>
                        <div class="column medium last">
							<?php echo $form->company->render() ?>
							<?php echo $form->legalform->render() ?>
                        	<?php echo $form->company_type_id->render() ?>
                            <?php echo $form->vat->render() ?><br/><br/>
                            
                            <?php 
	                            // ReCaptcha
	                            $privKey = Settings::findbyParam('recaptcha_private_key');
	                            $pubKey = Settings::findbyParam('recaptcha_public_key');
	                            
	                            if(!empty($pubKey) && !empty($privKey)){
									echo $form->captcha->render();
								}
                            ?>
                            
                            <p align="right"><?php echo $form->signup->render() ?></p>
                        </div>
                    </form>
            <?php endif;?>
    </div>
    <div class="clear"></div>
</div>


