<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<?php if($form->panel_id->getValue()): ?><li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Configuration');?></a></li> <?php endif;?>
		</ul>
		
        <div class="tab-content">
    	    <div class="tab-pane" id="tab1"> 
    		    <?php echo $form->name->render()?>
    		    <?php echo $form->isp_id->render()?>
    		    <?php echo $form->active->render()?>
    		   	<?php echo $form->panel_id->render()?>
    		</div>  
    		<?php if($form->panel_id->getValue()): ?>
    			<div class="tab-pane" id="tab2"> 
    				<?php echo $form->parameters->render()?>
    			</div>	
    		<?php endif;?>
		</div>
	</div>
</form>
