<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">
	<h2><?=$this->translate('Selected record');?>: <?=$this->recordselected; ?></h2>
	<p><?=$this->description; ?></p><br/>
	<p>
		<a class="button" href="<?=$this->back;?>"><?=$this->translate('No, I don\'t!'); ?></a>
		<a class="button button_red" href="<?=$this->goto;?>"><?=$this->translate('YES, I want to do it!'); ?></a>
	</p>
</div>