<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<div class="alert alert-info"><?php echo $form->log->getValue() ?></div>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Logs');?></a></li> 
		</ul>
		
	    <div class="tab-content">
		    <div class="tab-pane" id="tab1"> 
		        <div class="row">
		            <div class="col-lg-6">
		                <?php echo $form->action->render() ?>
        		        <?php echo $form->startdate->render() ?>
        		        <?php echo $form->enddate->render() ?>
		            </div>
		            <div class="col-lg-6"> 
        		        <?php echo $form->registrars_id->render() ?>
        		        <?php echo $form->domain_id->render() ?>
        		        <?php echo $form->status_id->render() ?>
		            </div>
		        </div>
		    </div>
		    <div class="tab-pane" id="tab2"> 
		        <div class="row">
		            <div class="col-lg-12"> 
		                <?php echo $form->log->render() ?>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
	<?php echo $form->task_id->render() ?>
</form>
