<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Logs');?></a></li> 
		</ul>
		
        <div class="tab-content">
		    <div class="tab-pane active" id="tab1">
		    	<?php echo $form->action->render() ?>
		        <?php echo $form->startdate->render() ?>
		        <?php echo $form->enddate->render() ?>
		        <?php echo $form->registrars_id->render() ?>
		        <?php echo $form->domain_id->render() ?>
		        <?php echo $form->status_id->render() ?>
		    </div>
		    <div id="tab2"> 
		        <?php echo $form->log->render() ?>
		    </div>
		</div>
	</div>
	<?php echo $form->task_id->render() ?>
</form>
