<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Logs');?></a></li> 
		</ul>
		
        <div class="tab-content">
    	    <div class="tab-pane active" id="tab1"> 
    	        <?php echo $form->action->render() ?>
    	        <?php echo $form->start->render() ?>
    	        <?php echo $form->end->render() ?>
    	        <?php echo $form->panel_id->render() ?>
    	        <?php echo $form->parameters->render() ?>
    	        <?php echo $form->status_id->render() ?>
    	    </div>
        
    	    <div class="tab-pane" id="tab2"> 
    	        <?php echo $form->log->render() ?>
    	    </div>
	    </div>
	</div>
	<?php echo $form->action_id->render() ?>
</form>
