<?php echo $this->render('partials/headers.phtml'); ?>

      
<?php echo $this->form ?>
<div id="graph"></div>

<hr/>

<?php if($this->data):?>
	<?php echo $this->simplegrid($this->data)?>
<?php endif; ?>

<?php // The datagrid will be shown here below ?>			
<?php if($this->incoming):?>
	<?php echo $this->incoming;?>
<?php endif; ?>

<?php // The datagrid will be shown here below ?>			
<?php if($this->expenses):?>
	<?php echo $this->expenses;?>
<?php endif; ?>
			
