<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<?php if(!$this->isrecurring): ?><li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Prices');?></a></li><?php endif;?> 
			<?php if($this->isrecurring): ?><li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Recurring Prices');?></a></li><?php endif; ?> 
			<li><a data-toggle="tab" href="#tab4"><?php echo $this->translate('Categories');?></a></li> 
			<li><a data-toggle="tab" href="#tab5"><?php echo $this->translate('Content');?></a></li> 
			<?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
				<li><a data-toggle="tab" href="#tab6"><?php echo $this->translate('Media');?></a></li>
			<?php endif;?> 
			<li><a data-toggle="tab" href="#tab7"><?php echo $this->translate('Related Products');?></a></li>
			<li><a data-toggle="tab" href="#tab8"><?php echo $this->translate('Product Upgrades');?></a></li>
			<li><a data-toggle="tab" href="#tab9"><?php echo $this->translate('Orders');?></a></li> 
			<li><a data-toggle="tab" href="#tab10"><?php echo $this->translate('Attributes');?></a></li> 
			<li><a data-toggle="tab" href="#tab11"><?php echo $this->translate('Blocks');?></a></li> 
			<li><a data-toggle="tab" href="#tab12"><?php echo $this->translate('Metatags');?></a></li> 
			<li><a data-toggle="tab" href="#tab13"><?php echo $this->translate('Setup');?></a></li> 
		</ul>
    
    	<div class="tab-content">	
		    <div class="tab-pane" id="tab1"> 
			    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
			    	<?php echo $form->sku->render()?>
			        <?php echo $form->type->render()?>
			        <?php echo $form->group_id->render() ?>
			        <?php echo $form->name->render() ?>
			        <?php echo $form->nickname->render() ?>
			        <?php echo $form->ishighlighted->render() ?>
			        <?php echo $form->isrefundable->render() ?>
			        <?php echo $form->autosetup->render() ?>
			        <?php echo $form->cost->render()?>
			    </div>
			    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
			        <?php echo $form->uri->render()?>
		            <?php echo $form->position->render()?>
		            <?php echo $form->enabled->render()?>
		            <?php echo $form->iscomparable->render()?>
		            <?php echo $form->showonrss->render()?>
		            <?php echo $form->downgradable->render()?>
		            <?php echo $form->server_group_id->render()?>
		            <?php echo $form->tax_id->render()?>
		            <?php echo $form->welcome_mail_id->render()?>
		        </div>
		    </div>
	
		    <?php if(!$this->isrecurring): ?>
			    <div class="tab-pane" id="tab2">
			        <div>
			            <?php echo $form->price_1->render()?>
			            <?php echo $form->setupfee->render()?>
			        </div>
			   </div>
		   <?php endif; ?>
		   
		   <?php if($this->isrecurring): ?>
		   <div class="tab-pane" id="tab3">
		        <div>
		            <?php echo $this->simplegrid($this->tranches) ?>
		            <div id="trancheform">
		                <?php echo $form->tranche_qty->render()?>
		                <?php echo $form->tranche_billing_cycle_id->render()?>
		                <?php echo $form->tranche_setupfee->render()?>
		                <?php echo $form->tranche_price->render()?>
		                <?php echo $form->tranche_measure->render()?>
		                <?php echo $form->tranche_includes_domains->render()?>
		            </div>
		        </div>
		   </div> 
		   <?php endif; ?>
		   
		   <div class="tab-pane" id="tab4">
		        <div>
		            <div id="categories" name="categories"></div>
		        </div>
		   </div> 
		   
		   <div class="tab-pane" id="tab5">
		   		<?php echo $form->wikipages->render() ?>
	        	<?php echo $form->shortdescription->render() ?>
	            <?php echo $form->description->render() ?>
		   </div> 
		   
		   <?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
			   <div class="tab-pane" id="tab6">
		            <?php echo  $this->simplegrid($this->media);?>
		            <?php echo $form->attachments->render() ?>
		            <?php echo $form->default->render() ?>
		            <?php echo $form->filedescription->render() ?>
			   </div> 
			<?php endif;?>
			
		   <div class="tab-pane" id="tab7">
		   	    <?php echo $form->related->render() ?>
		   </div> 
		   
		   <div class="tab-pane" id="tab8">
		       <?php echo $form->upgrade->render() ?>
		   </div>
		    	   
		   <div class="tab-pane" id="tab9">
		        <?php echo $this->simplegrid($this->orders) ?>
		   </div> 
		   
		   <div class="tab-pane" id="tab10">
		   		<?php if (!empty( $form->attributes)) { echo $form->attributes->render(); } ?>
		   </div>    
		   
		   <div class="tab-pane" id="tab11">
		        <?php echo $form->blocks->render() ?>
		   </div>    
		   
		   <div class="tab-pane" id="tab12">
		        <?php echo $form->metakeywords->render() ?>
		        <?php echo $form->metadescription->render() ?>
		   </div>    
		   
		   <div class="tab-pane" id="tab13">
		        <?php echo $form->setup->render() ?>
		   </div>    
		   
	   	   <?php echo $form->product_id->render()?>
		</div>
	</div>
	
	<script type="text/javascript">
        var data = <?php echo $this->categories ?>;
	</script>
</form>
