<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"notification error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } 
	    
	    foreach ($form->getSubForms() as $subform) {
	    	foreach( $subform->getElements() as $field){
	    		$errors = array();
	    		if($field->hasErrors()){
		        	foreach( $field->getErrors() as $error){
		        		$errors[] = $this->translate($error);
		        	}
		            echo "<div class=\"notification error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
		        }   
	    	}	
	    }
	    ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div id="tabs">
		<ul>
			<li><a href="#tab1"><?=$this->translate('Main');?></a></li> 
			<li><a href="#tab2"><?=$this->translate('Prices');?></a></li> 
			<li><a href="#tab3"><?=$this->translate('Billing');?></a></li> 
			<li><a href="#tab4"><?=$this->translate('Categories');?></a></li> 
			<li><a href="#tab5"><?=$this->translate('Content');?></a></li> 
			<?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
				<li><a href="#tab6"><?=$this->translate('Media');?></a></li>
			<?php endif;?> 
			<li><a href="#tab7"><?=$this->translate('Related Products');?></a></li>
			<li><a href="#tab8"><?=$this->translate('Upgrade Products');?></a></li>
			<li><a href="#tab9"><?=$this->translate('Orders');?></a></li> 
			<li><a href="#tab10"><?=$this->translate('Attributes');?></a></li> 
			<li><a href="#tab11"><?=$this->translate('Blocks');?></a></li> 
			<li><a href="#tab12"><?=$this->translate('Metatags');?></a></li> 
			<li><a href="#tab13"><?=$this->translate('Setup');?></a></li> 
		</ul>
    
    
	    <div class="ui-tabs-hide default-tab" id="tab1"> 
		    <fieldset class=column-left> 
		    	<?php echo $form->sku->render()?>
		        <?php echo $form->type->render()?>
		        <?php echo $form->group_id->render() ?>
		        <?php echo $form->name->render() ?>
		        <?php echo $form->nickname->render() ?>
		        <?php echo $form->ishighlighted->render() ?>
		    </fieldset>
		    <fieldset class=column-right>
		        <?php echo $form->uri->render()?>
	            <?php echo $form->position->render()?>
	            <?php echo $form->enabled->render()?>
	            <?php echo $form->iscomparable->render()?>
	            <?php echo $form->showonrss->render()?>
	        </fieldset>
		    <div class="clear"></div>
	    </div>
	   <div class="ui-tabs-hide" id="tab2">
	        <fieldset>
	            <?php echo $form->price_1->render()?>
	            <?php echo $form->setupfee->render()?>
	            <?php echo $form->tax_id->render()?>
	            <?php echo $form->cost->render()?>
	        </fieldset>
	        <div class="clear"></div>
	   </div> 
	   <div class="ui-tabs-hide" id="tab3">
	        <fieldset>
	            <?php echo $this->simplegrid($this->tranches) ?>
	            <div id="trancheform">
	                <?php echo $form->tranche_qty->render()?>
	                <?php echo $form->tranche_billing_cycle_id->render()?>
	                <?php echo $form->tranche_price->render()?>
	                <?php echo $form->tranche_measure->render()?>
	            </div>
	        </fieldset>
	        <div class="clear"></div>
	   </div> 
	   <div class="ui-tabs-hide" id="tab4">
	        <fieldset>
	            <div id="categories" name="categories"></div>
	        </fieldset>
	        <div class="clear"></div>
	   </div> 
	   <div class="ui-tabs-hide" id="tab5">
	        <fieldset>
	        	<?php echo $form->shortdescription->render() ?>
	            <?php echo $form->description->render() ?>
	            <?php echo $form->wikipages->render() ?>
	        </fieldset>
	        <div class="clear"></div>
	   </div> 
	   
	   <?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
		   <div class="ui-tabs-hide" id="tab6">
		        <fieldset>
		            <?= $this->simplegrid($this->media);?>
		            <?php echo $form->attachments->render() ?>
		            <?php echo $form->default->render() ?>
		            <?php echo $form->filedescription->render() ?>
		        </fieldset>
		        <div class="clear"></div>
		   </div> 
		<?php endif;?>
	   <div class="ui-tabs-hide" id="tab7">
	        <fieldset>
	           	<?php echo $form->related->render() ?>
	            <div class="clear"></div>
	        </fieldset>
	        <div class="clear"></div>
	   </div> 
	   <div class="ui-tabs-hide" id="tab8">
	        <fieldset>
	           	<?php echo $form->upgrade->render() ?>
	            <div class="clear"></div>
	        </fieldset>
	        <div class="clear"></div>
	   </div> 	   
	   <div class="ui-tabs-hide" id="tab9">
	        <fieldset>
	            <?php echo $this->simplegrid($this->orders) ?>
	        </fieldset>
	        <div class="clear"></div>
	   </div> 
	   <div class="ui-tabs-hide" id="tab10">
	        <fieldset>
	            <?php if (!empty( $form->attributes)) { echo $form->attributes->render(); } ?>
	        </fieldset>
	        <div class="clear"></div>
	   </div>    
	   
	   <div class="ui-tabs-hide" id="tab11">
	        <fieldset>
	            <?php echo $form->blocks->render() ?>
	        </fieldset>
	        <div class="clear"></div>
	   </div>    
	   
	   <div class="ui-tabs-hide" id="tab12">
	        <fieldset>
	            <?php echo $form->metakeywords->render() ?>
	            <?php echo $form->metadescription->render() ?>
	        </fieldset>
	        <div class="clear"></div>
	   </div>    
	   
	   <div class="ui-tabs-hide" id="tab13">
	        <fieldset>
	            <?php echo $form->setup->render() ?>
	        </fieldset>
	        <div class="clear"></div>
	   </div>    
   	   <?php echo $form->product_id->render()?>
	</div>
</form>

<script type="text/javascript">
	var data = <?php echo $this->categories ?>;
	
	$(document).ready(function() {
		$('#name').attr('readonly', <?=$this->isSold?>);
	});
</script>
</div>