<div class="row">

	<?php if($this->dashboard): ?>
	    <div class="col-lg-12 colummn">
	        <h3><?php echo $this->translate('Welcome', $this->customer['firstname'] . " " . $this->customer['lastname'])?></h3>
	        <p><?php echo $this->translate('Welcome to the administration of your own services and domain panel.')?></p>
	        
        	<?php echo $this->navigation()->menu()->setUlClass('button-group round even-1'); ?><br/>
	        
	        <?php if(!empty($this->mex)) :?>
	        <div class="alert-box <?php echo $this->mexstatus; ?>"><?php echo $this->translate($this->mex);?></div>
	        <?php endif;?>
	        
	        <div id="dashboard">
	        
	              <?php echo $this->checkdomains()->showForm(); ?><br/>
	              
	              <?php echo $this->Alerts();?>
	        
	              <div class="segment">
	                <div class="head" title="<?php echo $this->translate('Here below you can see all the domains near at the expiring date.') ?>">
	                    <h4><?php echo $this->translate('Expiring Domains') ?></h4>
	                </div>
	                <div class="content">
	                    <?php echo $this->simplegrid($this->dashboard()->DomainsExpiration());?>
	                </div>
	              </div>  
	                    
	              <div class="segment">
	                <div class="head" title="<?php echo $this->translate('Here below you can see all the services near at the expiring date.') ?>">
	                    <h4><?php echo $this->translate('Expiring Services') ?></h4>
	                </div>
	                <div class="content">
	                    <?php echo $this->simplegrid($this->dashboard()->ServicesExpiration());?>
	                </div>
	              </div>
	              
	              <div class="segment">
	                <div class="head" title="<?php echo $this->translate('In this section you can see all the requested support issues.') ?>">
	                    <h4><?php echo $this->translate('Last Tickets') ?></h4>
	                </div>
	                <div class="content">
	                    <?php echo $this->simplegrid($this->dashboard()->Last()); ?>  
	                </div>
	              </div>      
	              
	              <div class="segment">
	                <div class="head" title="<?php echo $this->translate('Here some statistics about your domains and services.') ?>">
	                    <h4><?php echo $this->translate('Statistiche') ?></h4>
	                </div>
	                <div class="content">
	                   <p align="center">
	                    <?php echo $this->graphs()->tldSummary()?> 
	                    <?php echo $this->graphs()->tldSummaryPerMonth()?>
	                    </p>
	                </div>
	              </div>       
	              
	                  
	        </div>
	    </div>
	<?php endif;?>  
</div>	