<?php $form = $this->loginform; ?>
<?php $isp = Isp::getActiveISP()?>
<div id="login-wrapper" class="loginframe">
    <div id="login-content">
       
       <div id="login-box">             
            <h1><?php echo !empty($isp['company']) ? $isp['company'] : $this->translate('Control Panel')?></h1>
    		<small><?php echo $this->translate('please fill up the form with the administration credentials.')?></small>
            <br/><br/>
            
           <?php if( $this->message ): ?>
                <?php echo $this->Message($this->message); ?>
           <?php endif;?>
           
            <form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
                    <?php echo $form->email->render() ?>
                    <?php echo $form->password->render() ?>
                    <?php echo $form->rememberme->render() ?>
                    
                    <?php echo $form->login->render() ?>
                    <span class="help-inline text-right"><a href="/admin/login/password"><?php echo $this->translate('I forgot my password')?></a></span>
            </form>
        </div>
    </div>
</div>
