<?php $form = $this->loginform; ?>
<?php $isp = Isp::getActiveISP() ?>

<div id="login-wrapper" class="loginframe">
    <div id="login-content">
       <div id="login-box">
            <h1><i class="fa fa-code-fork"></i> <?php echo !empty($isp['company']) ? $isp['company'] : $this->translate('Control Panel')?></h1>
    		<small><?php echo $this->translate('please fill up the form with the administration credentials.')?></small>
            <br/><br/>
            
           <?php if( $this->message ): ?>
                <?php echo $this->Message($this->message); ?>
           <?php endif;?>
           
            <form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
                
                <div class="input-group">
                	<?php echo $form->email->setDecorators(array('ViewHelper')) ?>
                	<span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
                </div>
                <br/>
                <div class="input-group">
                	<?php echo $form->password->setDecorators(array('ViewHelper')) ?>
                	<span class="input-group-addon"><i class="fa fa-key"></i></span>
                </div>
                
                <div class="row">
	                <div class="col-lg-6"><?php echo $form->rememberme->render() ?></div>
                	<div class="col-lg-6 loginbtn text-right"><?php echo $form->login->render() ?></div>
                </div>
            	<small class="help-inline text-right"><a href="/admin/login/password"><?php echo $this->translate('I forgot my password')?></a> - <a href="/"><?php echo $this->translate('Go to the Public Site')?></a></small>
            </form>
        </div>
    </div>
</div>
