<? $form = $this->loginform; ?>

<div id="login-wrapper" class="loginframe">
    <div id="login-content">
       
       <?php if( $this->message ): ?>
            <?php echo "<div class=\"notification error\">" . $this->message . "</div>"; ?>
       <?php endif;?>
       
       <div id="login-box">             
            <h1><?php echo $this->translate('OAuth Consent').' - '.$this->appName?></h1>
    		<small><?php echo $this->translate('please fill up the form with the administration credentials.')?></small>
            <br/><br/>

	       <?php 
	       		if ( !empty($this->requestedScopes) ):
		   ?>
		   			<div><?php echo $this->appName.' '.$this->translate('is trying to get access to the following data:') ?></div>
		   <?php
					foreach ( $this->requestedScopes as $scope ):
		   ?>
		   				<li><?php echo $scope?></li>
		   
		   <?php					
					endforeach;
		   ?>
		   		<br/><br/>
		   <?php
				endif;
	       ?>

			
            <form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
                <fieldset class="login">
                    <?php echo $form->email->render() ?>
                    <?php echo $form->password->render() ?>
                    <div class="column left"><?php echo $form->login->setDecorators(array('Simple')) ?></div>
                </fieldset>
            </form>
        </div>
    </div>
</div>