<? $form = $this->passwordform; ?>

<div id="login-wrapper" class="loginframe">
    <div id="login-content">
       
       <?php if( $this->message ): ?>
            <?php echo "<div class=\"notification information\">" . $this->message . "</div>"; ?>
       <?php endif;?>
       
       <div id="login-box">             
            <h1><?php echo $this->translate('Reset Password')?></h1>
    		<small><?php echo $this->translate('reset the administration password.')?></small>
            <br/><br/>
            <form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
                <div class="login">
                    <?php echo $form->email->render() ?>
                    <?php echo $form->captcha->render() ?>
                    <br/>
                    <div class="column left"><?php echo $form->submit->setDecorators(array('Simple')) ?></div>
                    <div class="getpassword"><a href="/admin"><?php echo $this->translate('Try to login again')?></a></div>
                </div>
            </form>
        </div>
    </div>
</div>