<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->render('includes/top.phtml') ?>
		
	<?php echo $this->blocks()->showblock('startbody');?>

    <div id="content" class="container">
    
		<?php echo $this->blocks()->showblock('beforecontent');?>
	
		<div class="col-lg-12">
			<?php echo $this->Messages(); ?>
	    	<?php echo $this->cmsheader($this->headerdata);?>
            <?php echo $this->blocks()->showblock('contentstart');?>
            <?php echo $this->layout()->content ?>
            <?php echo $this->blocks()->showblock('contentend');?>
		</div> 
		
	    <?php echo $this->blocks()->showblock('beforefooter');?>
			
	    <footer class="row">
	    	<?php echo $this->footer();?>
	        <?php echo $this->blocks()->showblock('footer');?>
	    </footer><!-- End #footer -->
     
    	<?php echo $this->blocks()->showblock('endfooter');?>
    </div>	<!-- End #main-container -->
    
    <?php echo $this->blocks()->showblock('endbody');?>
    
<?php echo $this->render('includes/endpage.phtml') ?>

    