<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->render('includes/top.phtml') ?>
		
	<?php echo $this->blocks()->showblock('startbody');?>

    <div id="content" class="container">
    
		<?php echo $this->blocks()->showblock('beforecontent');?>
	    
	    <!-- Start #main-container -->
		<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
			<?php echo $this->Messages(); ?>
	    	<?php echo $this->cmsheader($this->headerdata);?>
            <?php echo $this->blocks()->showblock('contentstart');?>
            <?php echo $this->layout()->content ?>
            <?php echo $this->blocks()->showblock('contentend');?>
		</div> 

    </div>	<!-- End #main-container -->
    
    <!-- Start #footer -->
    <?php echo $this->blocks()->showblock('beforefooter');?>
    <?php echo $this->render('includes/footer.phtml') ?> 
    <?php echo $this->blocks()->showblock('endfooter');?> 
    <!-- End #footer -->
    
<?php echo $this->render('includes/endpage.phtml') ?>    


	    