<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
	<?php echo $this->render('includes/top.phtml') ?>
	
	<?php echo $this->blocks()->showblock('beforecontent');?>
    
    <div id="content" class="container">
    	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
    		<?php echo $this->blocks()->showblock('left');?>
    	</div>
    	
    	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12" role="content">
    		<?php echo $this->blocks()->showblock('contentstart');?>
	        <?php echo $this->layout()->content ?>
        	<?php echo $this->blocks()->showblock('contentend');?>
    	</div>

    </div>	<!-- End #main-container -->
    
    <?php echo $this->blocks()->showblock('aftercontent');?>
    
    <!-- Start #footer -->
    <?php echo $this->render('includes/footer.phtml') ?> 
    <!-- End #footer -->
    
<?php echo $this->render('includes/endpage.phtml') ?>    
	    