<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
    <?php echo $this->render('includes/top.phtml') ?>
    
    <div id="content" class="container">
    	<div class="col-sm-9 col-md-9 col-lg-9" role="content">
    		<?php echo $this->blocks()->showblock('contentstart');?>
	        <?php echo $this->layout()->content ?>
        	<?php echo $this->blocks()->showblock('contentend');?>
    	</div>
    	
    	<aside class="col-sm-3 col-md-3 col-lg-3 hidden-xs">
    		<?php echo $this->blocks()->showblock('right');?>
    	</aside>
    	
    </div>	<!-- End #main-container -->
    
    <!-- Start #footer -->
    <?php echo $this->render('includes/footer.phtml') ?> 
    <!-- End #footer -->
    
<?php echo $this->render('includes/endpage.phtml') ?>    
	    
    	