<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
    <?php echo $this->render('includes/top.phtml') ?>
        
    <div class="row">
    	<aside class="large-4 columns">
    		<?php echo $this->blocks()->showblock('left');?>
    	</aside>
    	
    	<div class="large-8 columns" role="content">
    		<?php echo $this->blocks()->showblock('contentstart');?>
	        <?php echo $this->layout()->content ?>
        	<?php echo $this->blocks()->showblock('contentend');?>
    	</div>
	    
	</div>
        
    
    <?php echo $this->blocks()->showblock('beforefooter');?>
    <footer class="row">
    	<?php echo $this->footer();?>
        <?php echo $this->blocks()->showblock('footer');?>
    </footer><!-- End #footer -->
    <?php echo $this->blocks()->showblock('endfooter');?>
    <?php echo $this->blocks()->showblock('endbody');?>

<?php echo $this->render('includes/endpage.phtml') ?>