<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
    <?php echo $this->render('includes/top.phtml') ?>
    
    <div id="content" class="container">
    	<div class="large-8 columns" role="content">
    		<?php echo $this->blocks()->showblock('contentstart');?>
	        <?php echo $this->layout()->content ?>
        	<?php echo $this->blocks()->showblock('contentend');?>
    	</div>
    	
    	<aside class="large-4 columns hidden-xs">
    		<?php echo $this->blocks()->showblock('right');?>
    	</aside>
    	
    </div>	<!-- End #main-container -->
    
    <div class="footer-wrapper row">
    	<?php echo $this->footer();?>
        <?php echo $this->blocks()->showblock('footer');?>
    </div>
 
	<?php echo $this->blocks()->showblock('endfooter');?>    
    
    <?php echo $this->blocks()->showblock('endbody');?>
    
<?php echo $this->render('includes/endpage.phtml') ?>

    	