<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
    <?php echo $this->render('includes/top.phtml') ?>
    
    <div class="row content_start">
    	<aside class="col-lg-4 columns">
    		<?php echo $this->blocks()->showblock('left');?>
    	</aside>
    	
    	<div class="col-lg-8 columns" role="content">
    		<?php echo $this->blocks()->showblock('contentstart');?>
	        <?php echo $this->layout()->content ?>
        	<?php echo $this->blocks()->showblock('contentend');?>
    	</div>

    </div>	<!-- End #main-container -->
    
    <!-- Start #footer -->
    <?php echo $this->render('includes/footer.phtml') ?> 
    <!-- End #footer -->
    
<?php echo $this->render('includes/endpage.phtml') ?>    
	    

    	