<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
	<?php echo $this->render('includes/top.phtml') ?>
	
	<?php echo $this->blocks()->showblock('beforecontent');?>
	
    <div id="content" class="container">
        
		<div class="row">
    		<div class="col-lg-12">
    			<?php echo $this->Messages($this->mex)?>
                <?php echo $this->blocks()->showblock('contentstart');?>
                <?php echo $this->layout()->content ?>
                <?php echo $this->blocks()->showblock('contentend');?>
    		</div> 
        </div>
    
	    <?php echo $this->blocks()->showblock('beforefooter');?>

    </div>	<!-- End #main-container -->
    
    <!-- Start #footer -->
    <?php echo $this->blocks()->showblock('beforefooter');?>
    <?php echo $this->render('includes/footer.phtml') ?> 
    <?php echo $this->blocks()->showblock('endfooter');?> 
    <!-- End #footer -->
    
<?php echo $this->render('includes/endpage.phtml') ?>    
	    