<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
	
	<?php echo $this->render('includes/top.phtml') ?>
	
	<?php echo $this->blocks()->showblock('beforecontent');?>
	
	<div class="section">
		<?php echo $this->Messages($this->mex)?>
        <?php echo $this->blocks()->showblock('contentstart');?>
        <?php echo $this->layout()->content ?>
        <?php echo $this->blocks()->showblock('contentend');?>
    </div>
    
    <div class="section">
        <?php echo $this->blocks()->showblock('aftercontent');?>
    </div>
    
    <!-- Start #footer -->
    <?php echo $this->render('includes/footer.phtml') ?> 
    <!-- End #footer -->
    
<?php echo $this->render('includes/endpage.phtml') ?>    
	    