<?php if(!empty($this->files)): ?>
	<div class="attachments">
		<h6><?php echo $this->translate('Attachments') ?></h6>
		<ul class="nav nav-tabs">
		<?php foreach($this->files as $file): ?>
			<?php if(file_exists(PUBLIC_PATH . $file['path'] . $file['file'])): ?>
				<li class="files <?php echo pathinfo($file['file'], PATHINFO_EXTENSION);?>">
					<a href="<?php echo $file['path'] . $file['file']?>"><?php echo basename($file['file'])?></a>
					[<a class="confirm" href="/admin/tickets/delattach/id/<?php echo $file['file_id']?>"><?php echo $this->translate('Delete')?></a>] 
					
				</li>
			<?php else:?>
				<li><?php echo basename($file['file'])?> - <?php echo $this->translate('File not found')?></li>
			<?php endif;?>
		<?php endforeach;?>
		</ul>
	</div>
<?php endif; ?>	