
<?php if ($this->records->count()):?>
	
	<ul class="media-list">
		<?php foreach ( $this->records as $record ) : ?>
		<li class="media">
		    <?php echo !empty($record->customer_id) ? $this->Avatar( $record->Customers->email, 60 ) : $this->Avatar ( $record->Isp->email, 60 ); ?>
		    <div class="media-body">
		    	<h4 class="media-heading"><?php echo !empty($record->customer_id) ?  $record->Customers->lastname . " " . $record->Customers->firstname :  $record->Isp->company; ?> <small><?php echo  $record->dateposted; ?></small></h4>
		    	<div class="message-body"><?php echo  $record->message; ?></div>		
		    </div> 
		</li>
		<?php endforeach;?>
	</ul>
<?php else: ?>
    <div class="alert alert-info"><?php echo $this->translate('No Records')?></div>
<?php endif; ?>
