<?php if (isset($this->searchactive) && $this->searchactive == 1 ): ?>
    <div class="notification attention"><?php echo $this->translate('A search request is still active.')?> <a href="/admin/<?php echo  $this->controller ?>/reset"><?php echo $this->translate('Reset')?></a> / <a href="/admin/<?php echo  $this->controller ?>/search"><?php echo $this->translate('Search Again')?></a></div>
<?php endif; ?>

<?php if (!empty($this->sortactive) ): ?>
    <div class="notification attention"><?php echo $this->translate('Sort by')?>
         <?php foreach($this->sortactive as $item):?>
            <?php echo "<b>" . $item . "</b> /";?>
         <?php endforeach;?>
         
        [<a href="/admin/<?php echo  $this->controller ?>/sortreset"><?php echo $this->translate('Reset')?></a> / <a href="/admin/<?php echo  $this->controller ?>/search"><?php echo $this->translate('Sort')?></a>]
    </div>
<?php endif; ?>
   
<?php if(!empty($this->mex)) :?>
    <div class="notification <?php echo  $this->mexstatus; ?>"><?php echo $this->translate($this->mex);?></div>
<?php endif;?>

<div class="statuses">
 <?php if($this->statuses):?>
     <b><?php echo $this->translate('Statuses');?>:</b> 
     <select name="statuses" id="statuses">
          <option value=""><?php echo $this->translate('Show All');?></option>
              <?php foreach ( $this->statuses as $id=>$status ) : ?>
                  <option value="<?php echo $id?>"><?php echo $this->translate($status);?></option>
              <?php endforeach;?>
      </select>
      <input type="button" rel="<?php echo  $this->controller ?>" id="statusbtn" value="<?php echo $this->translate('Execute');?>">
  <?php endif;?>
 </div>  
 
<?php 
if (isset($this->records[0])):
    // Get all the items inside a multidimensional array
    $items = Shineisp_Commons_Utilities::array_flatten($this->records[0]);
    
    // Get all the fields
    $fields = array_keys($items);
    
    // Counting the field
    $numcols = count($fields);
    
?>
	    
	    <div class="alert alert-info" id="mex" style="display:none"></div>
	    
	    <table border="0" cellpadding="5" class="grid zebratable" id="itemlist">
	       <caption>
	            
	        </caption>
	        <thead>
	            <tr>
	               <?php if($this->show_action_box && ($this->statuses || $this->customactions)):?><th><input type="checkbox" class="selectall" value=""></th><?php endif;?>
	                <?php // Creation of the Rows and Columns?>
		               <?php foreach ( $fields as $field ) : ?>
		                   <?php if(strpos($field, "_id")=== false):?>
		                        <th>
		                          <?php 
		                              $col_label = ucfirst($field);
		                              $col_label = str_replace("_", " ", $col_label);
		                              echo $this->translate($col_label)
		                          ?>
		                          <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/<?php echo  $this->action ?>/page/<?php echo $this->currentpage;?>/sort/<?php echo $field;?>,asc"><img alt="asc" src="<?php echo $this->paths('skin')?>/images/asc.gif"></a>
                                  <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/<?php echo  $this->action ?>/page/<?php echo $this->currentpage;?>/sort/<?php echo $field;?>,desc"><img alt="desc" src="<?php echo $this->paths('skin')?>/images/desc.gif"></a>
		                        </th>
		                   <?php endif;?>
		               <?php endforeach;?>
	               
	                <th><?php echo $this->translate('Commands');?></th>
	            </tr>
	        </thead>
	        
	        <tbody>
		         <?php // Creation of the Rows?>
	             <?php foreach ( $this->records as $record ) : ?>
		           <tr>
                   <?php if($this->show_action_box && ($this->statuses || $this->customactions)):?><td><input type="checkbox" name="item[]" value="<?php echo $record[$this->fields[0]] ?>"></td><?php endif;?>
	               <?php foreach ( $fields as $field ) : ?>
	                   <?php if(strpos($field, "_id")=== false):?>
	                    <?php
			                    // Manage the sub arrays created by the HYDRATE_ARRAY records fetching mode  
			                     $res = "";  
			                     Shineisp_Commons_Utilities::search(array($field), $record, $res);
			                     $value = !empty($res[$field]) ? $this->translate($res[$field]) : "";?>
	                            <td class="values"><a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/edit/id/<?php echo $record[$this->fields[0]]?>"><?php echo $value?></a></td>
	                   <?php endif;?>
	               <?php endforeach;?>
	               <td>
	                   <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/edit/id/<?php echo $record[$this->fields[0]]?>"><img alt="<?php echo  $this->translate('Edit') ?>" src="<?php echo $this->paths('skin')?>/images/pencil.png" border="0"></a> 
	                   <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/confirm/id/<?php echo $record[$this->fields[0]]?>"><img alt="<?php echo  $this->translate('Delete') ?>" src="<?php echo $this->paths('skin')?>/images/cross.png" border="0"></a> 
	               </td>
	               </tr>
	            <?php endforeach;?>
	        
	        </tbody>
	        <tfoot>
		        <tr>
	               <td colspan="<?php echo $numcols+1?>"> 
	                   <div class="bulktools">
	                       <?php if($this->show_action_box && ($this->statuses || $this->customactions)):?>
		                       <b><?php echo $this->translate('Bulk Actions');?>:</b> 
		                       <select name="actions" id="actions">
		                           <option value=""><?php echo $this->translate('Select ...');?></option>
		                           <?php if($this->statuses):?>
		                               <optgroup label="<?php echo $this->translate('Statuses');?>">
		                                   <?php foreach ( $this->statuses as $id=>$status ) : ?>
		                                       <option value="set_status&status=<?php echo $id?>"><?php echo $this->translate($status);?></option>
		                                   <?php endforeach;?>
		                               </optgroup>
		                           <?php endif; ?>
		                           <?php if($this->customactions):?>
		                               <optgroup label="<?php echo $this->translate('Actions');?>">
		                               <?php foreach ( $this->customactions as $action=>$label ) : ?>
		                                   <option value="<?php echo $action;?>"><?php echo $this->translate($label);?></option>
		                               <?php endforeach;?>
		                               </optgroup>
		                           <?php endif; ?>
		                       </select>
		                       <input type="button" rel="<?php echo  $this->controller ?>" id="bulkactions" value="<?php echo $this->translate('Execute');?>"><br />
		                       <?php echo $this->translate('Select the checkboxes in order to execute the same action to all items selected.');?>
		                    <?php endif; ?> 
	                   </div>
	                   <div class="pagingtools">
	                       <?php echo $this->translate('Records');?>: <?php echo $this->recordcount?> - 
	                        <?php echo $this->translate('Items to show');?>: 
	                        <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/recordsperpage/id/5">5</a>
	                        <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/recordsperpage/id/15">15</a>
	                        <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/recordsperpage/id/30">30</a>
	                        <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/recordsperpage/id/50">50</a>
	                        <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/recordsperpage/id/100">100</a>
	                        <a href="/<?php echo  $this->module ?>/<?php echo  $this->controller ?>/recordsperpage/id/all"><?php echo $this->translate('Show All');?></a>
	                   </div>
	               </td>
	            </tr>
	            <tr>
                   <td colspan="<?php echo $numcols+1?>">
                        <div class="pagination"><?php echo $this->pagination; ?></div>
                   </td>
                </tr>
	        </tfoot>
	    </table>
     
    <?php else: ?>
    <div class="alert alert-info"><?php echo $this->translate('No Records')?></div>
<?php endif; ?>
