    
    <div class="page-header pull-left">
    	<h3>
    		<?php if(!empty($this->titlelink)): ?>
    			<a target="blank" href="<?php echo $this->titlelink ?>"><?php if(!empty($this->icon)): ?><i class="<?php echo $this->icon ?>"></i> <?php endif;?><?php echo $this->title;?></a> <sup><small class="fa fa-external-link"></small></sup>
    		<?php else: ?>
    			<?php if(!empty($this->icon)): ?><i class="<?php echo $this->icon ?>"></i> <?php endif;?><?php echo $this->title;?>
    		<?php endif;?>
    	</h3>
    	<?php if(!empty($this->description)): ?>
    		<small><?php echo $this->description;?></small>
    	<?php endif; ?>
    	
    </div>
    
    <div class="pull-right"> 
    	<div class="btn-group btn-group-sm">
			<?php 
				$buttons = $this->buttons;
				if(!empty($buttons)){
					foreach ($buttons as $url => $button){
						$class   = !empty($button['params']['css']) ? implode(" ", $button['params']['css']) : "btn btn-default";
						$target  = !empty($button['params']['target']) ? 'target="'.$button['params']['target'].'"' : "";
						$id      = !empty($button['params']['id']) ? 'id="'.$button['params']['id'].'""' : "";
						$onClick = (isset($button['onclick'])) ? 'onClick="'.$button['onclick'].'"' : '';
						echo '<a class="'.$class.'" '.$id.' href="' . $button['url'] . '" '.$onClick.' '.$target.'>' . $button['label'] . '</a>';
					}
				}
			?>
		</div>	
	</div>
	
<div class="clearfix"></div>

<?php echo $this->Message($this->mex, $this->mexstatus) ?>
