<div id="scrollme" class="overtop sectionheader">
    
    <div class="page-header pull-left">
    	<h2 class="headtitle">
    		<?php if(!empty($this->titlelink)): ?>
    			<a href="<?php echo $this->titlelink?>"><?php echo $this->title;?></a>
    		<?php else: ?>
    			<?php echo $this->title;?>
    		<?php endif;?>
    		
    	</h2>
    	<?php if(!empty($this->description)): ?>
    		<small><?php echo $this->translate($this->description);?></small>
    	<?php endif; ?>
    	
    </div>
    
    <div class="pull-right">
		<?php 
			$buttons = $this->buttons;
			if(!empty($buttons)){
				foreach ($buttons as $url => $button){
					$class   = !empty($button['params']['css']) ? implode(" ", $button['params']['css']) : "";
					$target  = !empty($button['params']['target']) ? 'target="'.$button['params']['target'].'"' : "";
					$id      = !empty($button['params']['id']) ? 'id="'.$button['params']['id'].'""' : "";
					$onClick = (isset($button['onclick'])) ? 'onClick="'.$button['onclick'].'"' : '';
					echo '<a class="'.$class.'" '.$id.' href="' . $button['url'] . '" '.$onClick.' '.$target.'>' . $button['label'] . '</a> ';
				}
			}
		?>
	</div>
	
</div>
<div class="clearfix"></div>
