<?php if(!empty($this->records)): ?>
<ul class="addresses">
	<?php foreach ( $this->records as $record ) : ?>
		<li>
			<h2><?php echo $record['address'] ?></h2>
			<?php echo $record['code'] ?> <?php echo $record['city'] ?> (<?php echo $record['city'] ?>)<br/> <?php echo Countries::getNamebyId($record['country_id']) ?><br /><br />
			<img src="http://maps.googleapis.com/maps/api/staticmap?center=<?php echo $record['latitude'] ?>,<?php echo $record['longitude'] ?>&markers=color:blue%7C<?php echo $record['address'] ?>%20<?php echo $record['code'] ?>%20<?php echo $record['city'] ?>&zoom=8&maptype=roadmap&size=400x200&sensor=false" />
			<br /><br />
            <a class="button button_red" href="<? echo "/" . $this->module . "/" . $this->delete['controller'] . "/" . $this->delete['action'] . "/id/" . $record['address_id']?>" title="<?=$this->translate('delete'); ?>"><?=$this->translate('Delete'); ?></a>
		</li>
	<?php endforeach;?>
</ul>
<?php endif;?>

