<?php if(!empty($this->records)): ?>
<ul class="list-unstyled addresses">
	<?php foreach ( $this->records as $record ) : ?>
		<li>
			<address>
				<strong><?php echo $record['address'] ?></strong><br/>
				<?php echo $record['code'] ?> <?php echo $record['city'] ?> (<?php echo $record['area'] ?>)<br/>
				<?php if($record['region'] != ""): echo $record['region']." - "; endif; ?> <?php echo Countries::getNamebyId($record['country_id']) ?>
			</address>
			<?php $pos = $record['latitude'] . "," . $record['longitude']?>
			<a target="_blank" href="http://maps.google.com/maps?saddr=<?php echo $pos ?>&markers=<?php echo $pos ?>"><img class="img-polaroid" src="http://maps.googleapis.com/maps/api/staticmap?center=<?php echo $record['latitude'] ?>,<?php echo $record['longitude'] ?>&markers=color:blue%7C<?php echo $record['address'] ?>%20<?php echo $record['code'] ?>%20<?php echo $record['city'] ?>&zoom=8&maptype=roadmap&size=400x200&sensor=false" /></a>
			<br /><br />
            <a class="btn btn-danger" href="<? echo "/" . $this->module . "/" . $this->delete['controller'] . "/" . $this->delete['action'] . "/id/" . $record['address_id']?>" title="<?php echo $this->translate('delete'); ?>"><?php echo $this->translate('Delete'); ?></a>
		</li>
	<?php endforeach;?>
</ul>
<?php endif;?>

