<?php

function genMenu($container)
{
    foreach ($container as $page)
    {
        echo '<li class="dropdown">';

        $href = $page->uri;
        $target = 'dropdown-toggle';
    
        echo '<a href="' . $href . '" data-toggle="dropdown" target="' . $target . '">' . $page->label . '</a>';
        
        if (!empty($page->pages))
        {
            echo '<ul class="dropdown-menu">';

            genMenu($page->pages);

            echo '</ul>';
        }

        echo '</li>';
    }
}

echo '<ul class="nav">';

genMenu($this->container);

echo '</ul>';

