<?php $auth = Zend_Auth::getInstance(); ?>

<?php if($auth->hasIdentity()):?>

<?php $name = (!empty($this->data['Isp']['company'])) ? $this->data['Isp']['company'] : null?>

<a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="icon-user"></i> <?php echo $name ?></a>
<ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dLabel">
	<?php $identity = $auth->getIdentity(); ?>
	<li><a title="<?=$this->translate('Profile') ?>" href="/admin/profile/account"><?=$this->translate("%s's %s profile", $identity['lastname'], $identity['AdminRoles']['name']) ?></a></li>
	<li><?php if(!empty($this->data['Isp']['company'])): ?><a title="<?=$this->translate('Company') ?>" href="/admin/isp/account"><?=$this->translate('%s\'s profile', $this->data['Isp']['company']) ?></a><?php endif;?></li>
	<li><a title="<?=$this->translate('Servers') ?>" href="/admin/servers/list"><?=$this->translate('Servers') ?></a></li>
	<li><a title="<?=$this->translate('Roles') ?>" href="/admin/roles"><?=$this->translate('Roles') ?></a></li>
	<li><a title="<?=$this->translate('Logout') ?>" href="/admin/login/out"><?=$this->translate('Logout') ?></a></li>
</ul>
<?php endif;?>