<?php foreach($this->data as $registrar): ?>
	<div class="reg-item">
	    <b><a href="/admin/registrars/edit/id/<?= $registrar['registrars_id'] ?>"><?= $registrar['name'] ?></a></b>
	    <p><?=$this->translate('Username')?>: <?= $registrar['username'] ?><br/>
	       <?=$this->translate('Credit')?>: <b><?= $registrar['credit'] ?></b><br/>
	       <?=$this->translate('Last update')?>: <?= Shineisp_Commons_Utilities::formatDateOut($registrar['lastupdate']) ?></p>
    </div>
<?php endforeach; ?>