<?php 

if (isset($this->records[0])):
    // Get all the items inside a multidimensional array
    $items = Shineisp_Commons_Utilities::array_flatten($this->records[0]);
    
    // Get all the fields
    $fields = array_keys($items);
    
    // Counting the records
    $recordcount = count($this->records);
    
    // Counting the field
    $numcols = count($fields); ?>
    
    <div class="notification infos" id="mex" style="display:none"></div>
        <table border="0" cellpadding="5" class="data sublist" id="sublist_<?=$this->name?>">
            <thead>
                <tr>
                    <?php // Creation of the Rows and Columns?>
                       <?php foreach ( $fields as $field ) : ?>
                           
                           <?php if(strpos($field, "_id")=== false):?>
                                <th>
                                  <?php
                                  // When a record is called using the HYDRATE_SCALAR mode the table aliases are attached in the field name
                                  // In this way we delete the first part of the field name. For instance: o_name --> name 
                                  $arrfield = explode("_", $field);
                                  $field = count($arrfield) > 0 ? $arrfield[count($arrfield)-1] : $field;
                                  echo ucfirst($this->translate($field));
                                  ?>
                                </th>
                           <?php endif;?>
                           
                       <?php endforeach;?>
                   
                    <?php if($this->view || $this->edit || $this->delete || $this->actions ):?><th><?=$this->translate('Commands');?></th><?php endif;?>
                </tr>
            </thead>
            <tbody>
                 <?php  // Creation of the Rows?>
                 <?php foreach ( $this->records as $record ) : ?>
                   <tr>
                   <?php foreach ( $fields as $field ) : ?>
                        <?php if(strpos($field, "_id")=== false):?>
	                        <?php
	                        // Manage the sub arrays created by the HYDRATE_ARRAY records fetching mode    
	                         Shineisp_Commons_Utilities::search(array($field), $record, $res);
	                         $value = !empty($res[$field]) ? $this->translate($res[$field]) : "";
	                         ?>
	                         <td class="values"><?=$value?></td>
                         <?php endif;?>
                   <?php endforeach;?>
                   <?php if($this->view || $this->edit || $this->delete || $this->actions):?>
                   <td>
	                    <?php if($this->view):?>
                           <a href="<? echo "/" . $this->module . "/" . $this->view['controller'] . "/" . $this->view['action'] . "/id/" . $record[$fields[0]]?>" title="<?=$this->translate('Click here to view'); ?>"><?=$this->translate('View'); ?></a>
                        <?php endif;?>

	                    <?php if($this->edit):?>
                            <a href="<? echo "/" . $this->module . "/" . $this->edit['controller'] . "/" . $this->edit['action'] . "/id/" . $record[$fields[0]]?>" title="<?=$this->translate('Click here to edit'); ?>"><?=$this->translate('Edit'); ?></a>
                        <?php endif;?>
                        
                        <?php if($this->delete):?>
                            <a href="<? echo "/" . $this->module . "/" . $this->delete['controller'] . "/" . $this->delete['action'] . "/id/" . $record[$fields[0]]?>" title="<?=$this->translate('delete'); ?>"><?=$this->translate('Delete'); ?></a>
                        <?php endif;?>
                        
                        <?php if($this->actions):?>
	                        <?php foreach ($this->actions as $url=>$name): ?>
	                            <a href="<? echo $url . $record[$fields[0]]?>" title="<?=$this->translate($name); ?>"><?=$this->translate($name); ?></a>
	                        <?php endforeach;?>
                        <?php endif;?>
                        
                        <?php if($this->onclick):?>
	                        <?php foreach ($this->onclick as $onclick=>$name): ?>
	                            <a href="#" title="<?=$this->translate($name); ?>" onclick="<?=str_replace('[id]', $record[$fields[0]], $onclick);?>" >
	                            	<?=$this->translate($name); ?>
	                            </a>
	                        <?php endforeach;?>
                        <?php endif;?>
                        
                   </td>
                   <?php endif;?>
                   </tr>
                <?php endforeach;?>
            
            </tbody>
        </table>
 
    <?php else: ?>
    <div class="notification infos"><?=$this->translate('No Records')?></div>
<?php endif; ?>
