<?php
	$currency       		= Settings::findbyParam('currency'); 
	$income_yearly 			= $this->income_yearly; 
	$income_quarter 		= $this->income_quarter; 
	$income_graph_monthly 	= $this->income_graph_monthly;
	$income_text_monthly  	= $this->income_text_monthly;

  	$currentYear 			= date('Y');
	$lastYear    			= $currentYear -1;
  	$arrgraph    			= array();
  	
?>

<?php if(!empty($income_yearly)): ?>
	<div class="portlet" id="income-yearly">
		<div class="widget-wrapper">
			<div class="widget-header"><h3><a href="#"><?php echo $this->translate('Income by Year')?></a></h3></div>
			<div class="widget-content">
				<ul class="stats">
					<?php foreach($income_yearly as $inc):?>
						<li>
							<h1><?php echo $inc['year']?></h1>
							<span style="cursor:help" title="<? echo $this->translate('%s - Grand Total: %s - Total: %s - VAT: %s', $inc['year'], $this->currency($inc['grandtotal'], array('currency' => $currency)), $this->currency($inc['total'], array('currency' => $currency)), $this->currency($inc['vat'], array('currency' => $currency))) ?>">
								<strong><?php echo $this->currency($inc['total'], array('currency' => $currency)) ?></strong>
							</span>
							 
							<?php if(!empty($inc['old']['total'])): ?>
								<span style="cursor:help" title="<? echo $this->translate('%s - Grand Total: %s - Total: %s - VAT: %s', $inc['old']['year'], $this->currency($inc['old']['grandtotal'], array('currency' => $currency)), $this->currency($inc['old']['total'], array('currency' => $currency)), $this->currency($inc['old']['vat'], array('currency' => $currency))) ?>">
								</span>
							<?php endif;?> 
							<?php if($inc['yieldrate'] != 0): ?><span class="<?php echo ($inc['yieldrate'] > 0) ? "green" : "red" ?>"><?php echo $this->currency($inc['incdec'], array('currency' => $currency)) ?> (<?php echo $inc['yieldrate'] ?>%)</span> <?php endif;?>
						</li>
					<?php endforeach;?>
				</ul>
			</div>
		</div>
	</div>
<?php endif;?>

<?php if(!empty($income_quarter)): ?>
	<div class="portlet" id="income-quarter">
		<div class="widget-wrapper">
			<div class="widget-header"><h3><a href="#"><?php echo $this->translate('Income by Quarter')?></a></h3></div>
			<div class="widget-content">
				<ul class="stats">
					<?php foreach($income_quarter as $inc):?>
						<?php if($inc['year'] == date('Y')): ?>
						<li><strong><?php echo $this->currency($inc['total'], array('currency' => $currency)) ?></strong> 
							<span style="cursor:help" title="<? echo $this->translate('Grand Total: %s - Total: %s - VAT: %s', $this->currency($inc['grandtotal'], array('currency' => $currency)), $this->currency($inc['total'], array('currency' => $currency)), $this->currency($inc['vat'], array('currency' => $currency))) ?>"><small><?php echo $this->translate('%s° quarter of %s', $inc['quarter'], $inc['year'])?></small></span> 
							<?php if(!empty($inc['old']['total'])): ?>
								<span style="cursor:help" title="<? echo $this->translate('Grand Total: %s - Total: %s - VAT: %s', $this->currency($inc['old']['grandtotal'], array('currency' => $currency)), $this->currency($inc['old']['total'], array('currency' => $currency)), $this->currency($inc['old']['vat'], array('currency' => $currency))) ?>">
									<small><?php echo $this->translate('%s° quarter %s: %s', $inc['old']['quarter'], $inc['old']['year'], $this->currency($inc['old']['total'], array('currency' => $currency))) ?></small>
								</span>
							<?php endif;?> 
							<span class="<?php echo ($inc['yieldrate'] > 0) ? "green" : "red" ?>"><?php echo $this->currency($inc['incdec'], array('currency' => $currency)) ?> (<?php echo $inc['yieldrate'] ?>%)</span>
						</li>
						<?php endif; ?>
					<?php endforeach;?>
				</ul>
			</div>
		</div>
	</div>
<?php endif;?>

<?php if(!empty($income_text_monthly)): ?>
<div class="portlet" id="income-text-month">
	<div class="widget-wrapper">
		<div class="widget-header"><h3><a href="#"><?php echo $this->translate('Income by Month (text)')?></a></h3></div>
		<div class="widget-content">
			<ul class="stats">
				<?php foreach($income_text_monthly as $inc):?>
					<?php if($inc['year'] == date('Y')): ?>
					<li><strong><?php echo $this->currency($inc['total'], array('currency' => $currency)) ?></strong> 
						<span style="cursor:help" title="<? echo $this->translate('Grand Total: %s - Total: %s - VAT: %s', $this->currency($inc['grandtotal'], array('currency' => $currency)), $this->currency($inc['total'], array('currency' => $currency)), $this->currency($inc['vat'], array('currency' => $currency))) ?>"><small><?php echo $this->translate('%s° month of %s', $inc['monthly'], $inc['year'])?></small></span> 
						<?php if(!empty($inc['old']['total'])): ?>
							<span style="cursor:help" title="<? echo $this->translate('Grand Total: %s - Total: %s - VAT: %s', $this->currency($inc['old']['grandtotal'], array('currency' => $currency)), $this->currency($inc['old']['total'], array('currency' => $currency)), $this->currency($inc['old']['vat'], array('currency' => $currency))) ?>">
								<small><?php echo $this->translate('%s° month %s: %s', $inc['old']['monthly'], $inc['old']['year'], $this->currency($inc['old']['total'], array('currency' => $currency))) ?></small>
							</span>
						<?php endif;?> 
						<span class="<?php echo ($inc['yieldrate'] > 0) ? "green" : "red" ?>"><?php echo $this->currency($inc['incdec'], array('currency' => $currency)) ?> (<?php echo $inc['yieldrate'] ?>%)</span>
					</li>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
</div>

<div class="portlet" id="income-graph-month">	
	<div class="widget-wrapper">
		<div class="widget-header"><h3><a href="#"><?php echo $this->translate('Income by Month (graph)')?></a></h3></div>
		<div class="widget-content">
			<div id='graph'></div>
		</div>
	</div>
	
	<script type="text/javascript" src="//www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawMonthlyIncomeChart);
      function drawMonthlyIncomeChart() {
		var data = new google.visualization.DataTable({
	       cols: [{id: 'month',          label: '<?=$this->translate('Month')?>', type: 'string'},
	              {id: 'grandTotal',     label: '<?=$this->translate('Income')?> <?=$currentYear?>', type: 'number'},
	              {'p': {'role':'tooltip','html':true}}, // tooltip for current year
	              {id: 'grandTotalLast', label: '<?=$this->translate('Income')?> <?=$lastYear?>', type: 'number'},
	              {'p': {'role':'tooltip','html':true}} // tooltip for previous year
	       ],
	       
	       rows: [
	          <?php
	          	foreach($income_graph_monthly[$currentYear] as $yearIncome):
					$month    = $yearIncome['month'];
					
					$currentTS = new Zend_Date(mktime(0,0,0,$month,1,$currentYear));
					$lastTS    = new Zend_Date(mktime(0,0,0,$month,1,$lastYear));
					$currentMonthTitle = ucwords($currentTS->toString(Zend_Date::MONTH_NAME).' '.$currentYear);
					$lastMonthTitle    = ucwords($currentTS->toString(Zend_Date::MONTH_NAME).' '.$lastYear);
					
					$total    = (isset($yearIncome['total'])) ? $yearIncome['total'] : 0;
					$oldTotal = (isset($income_graph_monthly[$lastYear][$month]['total'])) ? $income_graph_monthly[$lastYear][$month]['total'] : 0;
					$growDiff = (isset($yearIncome['growDiff'])) ? $yearIncome['growDiff'] : 0;
					$growPercent = (isset($yearIncome['growPercent'])) ? $yearIncome['growPercent'] : 0;
					
					$spanColor = ( $growPercent > 0 ) ? 'green' : 'red';

					$arrColonne   = array();
					$arrColonne[] = "{v: '".$yearIncome['month']."'}";				
					$arrColonne[] = "{v:".$total."}";
					$arrColonne[] = "{v:'<div style=\'font-size:14px\'><span style=\'font-size:18px\'><strong>".$currentMonthTitle."</strong></span><br/>".$this->translate('Income').": &euro; ".$total."<br/>".$this->translate('Income')." ".$lastYear.": &euro; ".$oldTotal."<br/>".$this->translate('Grow').": <span class=\'".$spanColor."\'>&euro; ".$growDiff." (".$growPercent."%)</span></div>'}"; // tooltip for current year
					$arrColonne[] = "{v:".$oldTotal."}";
					$arrColonne[] = "{v:'<div style=\'font-size:14px\'><span style=\'font-size:18px\'><strong>".$lastMonthTitle."</strong></span><br/>".$this->translate('Income')." ".$lastYear.": &euro; ".$oldTotal."'}"; // tooltip for previous year

					$arrgraph[] = "{c:[".implode(',',$arrColonne)."]}\n";
	          	endforeach;
				
				echo implode(',', $arrgraph);
				
	      		?>
			]
			
     	}, 0.6);

        var options = {
        	curveType: 'function'
        	,tooltip: {isHtml: true}
        };

        var chart = new google.visualization.LineChart(document.getElementById('graph'));
        chart.draw(data, options);

		$(window).smartresize(function(){
			chart.draw(data, options);
		});
      }
    </script>	
	
</div>
<?php endif;?>