<?php 
	$baseurl = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
	$lang = Zend_Controller_Front::getInstance()->getRequest()->getParam('lang');
	
	$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
	$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();

	if(empty($baseurl)){
	    $baseurl = "/admin/index/index";
	}
	
 	$baseurl = str_replace("/lang/$lang", "", $baseurl);
?>

<?php if(count($this->languages) > 1): ?>
	<a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="glyphicon glyphicon-flag"></i> <?php echo strtoupper($this->langselected) ?> <b class="caret"></b></a>
	<ul class="dropdown-menu">
		<?php foreach ($this->languages as $language): ?>
			<?php 
				if($language['code'] == $this->langselected){
					$selected = "active";
				}else{
					$selected = "";
				}
			?>
			<li class="<?php echo $selected ?>"><a href="<?php echo $baseurl . "/lang/" . $language['code'] ?>"><? echo $this->translate($language['language']) ?></a></li>
			
	    <?php endforeach;?>
	    
	    <li class="divider"></li>
	    <li><a href="/admin/languages/list"><? echo $this->translate('Language Settings') ?></a></li>
    </ul>
<?php endif;?>    
