<?php 
	$baseurl = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
	$lang = Zend_Controller_Front::getInstance()->getRequest()->getParam('lang');
 	$baseurl = str_replace("/lang/$lang", "", $baseurl);
?>

<span class="languageswitcher">
	<?php if(count($this->languages) > 1): ?>
		<select id="languageswitcher">
		<?php foreach ($this->languages as $language): ?>
			<?php 
				if($language['code'] == $this->langselected){
					$selected = "selected";
				}else{
					$selected = "";
				}
			?>
			<option <?php echo $selected?> value="<?php echo $baseurl . "/lang/" . $language['code'] ?>"><? echo $this->translate($language['language']) ?></option>
			
	    <?php endforeach;?>
	    </select>
	<?php endif;?>    
</span>
