<?php
// Email
$re = "/^[a-zA-Z0-9](?:[\\._-](?=[a-zA-Z0-9])|[a-zA-Z0-9])+@(?:[\\._-](?=[a-zA-Z0-9])|[a-zA-Z0-9])+(?:[a-z]{2,4}|com|ru|by)$/i";

if (isset($this->records[0])):
    // Get all the items inside a multidimensional array
    $items = Shineisp_Commons_Utilities::array_flatten($this->records[0]);
    
    // Get all the fields
	$fields = array_keys($items);
	
	// Counting the field
	$numcols = count($fields);
	
	// Main index of the record
	$idx = (!empty($fields[0]) && is_numeric($this->records[0][$fields[0]])) ? $this->records[0][$fields[0]] : "0";

	$res = array();
	?>
	
	<table class="table data">
	    <tbody>
	        <?php // Creation of the Rows and Columns?>
	        <?php foreach ( $this->records as $record ) : ?>
	           <?php foreach ( $fields as $field ) : ?>
		           <?php if(strpos($field, "_id")=== false):?>
		            <?php
                        // Manage the sub arrays created by the HYDRATE_ARRAY records fetching mode
                        Shineisp_Commons_Utilities::search(array($field), $record, $res);
                        $value = !empty($res[$field]) ? $this->translate($res[$field]) : "";
                        preg_match($re, $value, $matches); // check the email address
                        ?>
		             <?php if(!empty($value)): ?>
		                <tr>
				            <td width="15%" class="fields"><?php echo $this->translate(ucfirst($field))?></td>
                            <td class="values">
                                <?php if ($matches): ?>
                                    <a href="mailto:<?php echo $value; ?>"><?php echo $value; ?></a>
                                <?php else: ?>
                                    <?php echo $value; ?>
                                <?php endif; ?>
                            </td>
				        </tr>
		              <?php endif;?>
		           <?php endif;?>
	           <?php endforeach;?>
	        <?php endforeach;?>
	        
	        <?php // Edit Section available only for the administration functions ?>
	        <?php if($this->editpage):?>
	        <tr>
	           <td><?php echo $this->translate('Commands'); ?></td>
	           <td>
	               <a class="btn btn-default" href="<? echo "/admin/" . $this->editpage . "/edit/id/$idx"?>" title="<?php echo $this->translate('Click here to edit'); ?>"><?php echo $this->translate('Edit'); ?></a>
	               <a class="btn btn-default" href="<? echo "/admin/" . $this->editpage . "/confirm/id/$idx"?>" title="<?php echo $this->translate('Delete'); ?>"><?php echo $this->translate('Delete'); ?></a>
	           </td>
	        </tr>
	        <?php endif;?>
	    </tbody>
	    <tfoot>
	       <tr>
	           <td colspan="<?php echo $numcols?>"></td>
	       </tr>
	    </tfoot>
	</table>
	<?php else: ?>
	<div class="alert alert-info"><?php echo $this->translate('No Records')?></div>
<?php endif; ?>
