<div class="block">
	<?php if($this->element): ?>
		<div class="navbar navbar-inner block-header">
			<div class="muted pull-left"><a href="<?php echo $this->controller?>"><?php echo $this->translate($this->label) ?></a></div>
		</div>
		
		<div class="block-content">
			<?php if($this->chart):?>
				<div class="widget-chart">
					<img width="250" src="<?= $this->chart; ?>" alt="chart"/>
				</div>
			<?php endif; ?>
			
			<div class="widget-table <?php echo !empty($this->chart) ? "widget-medium" : "widget-large"?>">
				<?php echo $this->element; ?>
			</div>
		</div>
	<?php endif; ?>
</div>