<?php $form = $this->form; ?>
<?php echo $this->render('partials/header.phtml') ?>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">	
		<p align="right" class="order-buttons">
			<a href="/orders" class="btn btn-default"><?php echo $this->translate('Order list')?></a> 
			<a href="/orders/print/id/<?php echo $this->orderid?>" class="btn btn-default"><?php echo $this->translate('Print Order')?></a> 
            <?php if($this->invoiced): ?>
                <a href="/orders/createinvoice/id/<?php echo $this->invoice_id?>" class="btn btn-default"><?php echo $this->translate('Print Invoice')?></a> 
            <?php else: ?>
            	<?php if(Orders::IsEraseable($this->orderid, $this->customer_id)): ?> 
            		<a href="/orders/setdelete/id/<?php echo $this->orderid?>" class="btn btn-danger confirm"><?php echo $this->translate('Delete')?></a>
            	<?php endif; ?> 
            <?php endif; ?>
		    <a class="btn btn-success" href="/dashboard"><?php echo $this->translate('dashboard')?></a>
        </p> 
	</div>
</div>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">	
		<?php echo $this->status($this->statushistory);?>  
	</div>
</div>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">	
		<?php echo $this->verticalgrid($this->order)?> 
	</div>
</div>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">	
		<?php echo $this->simplegrid($this->details)?>
	</div>
</div>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">	
		<?php // Files attached ?>
        <?php if($this->files[0]): ?>
        <h3><?php echo $this->translate('Files Attached')?></h3>
    	<ul class="list-unstyled">
    		<?php foreach($this->files as $files): ?>
    		<li><span class="badge badge-info"><?php echo $files['categoryname']?></span> <a href="/index/getfiles/key/<?php echo $files['publickey'] ?>"><i class="fa fa-file-text"></i> <?php echo $files['file']?></a> <span class="label label-info"><?php echo $files['download']?></span></li>
    		<?php endforeach; ?>
    	</ul>
    	<?php endif; ?>
	</div>
</div>        

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">	
		<?php if(Null !== Settings::findbyParam('Conditions')): ?>
        	<p class="conditions"><?php echo $this->translate(Settings::findbyParam('Conditions')) ?></p><br/>
        <?php endif;?>
	</div>
</div>

<?php // Methods of payment ?>
 <?php if($this->tobepaid): ?>
    <?php echo $this->payments()->getPaymentsForm($this->orderid);?>
 <?php endif;?>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">	
	    <form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	    	<h3><?php echo $this->translate('Messages')?></h3>
	    	<p><?php echo $this->translate('Here you can read all your questions and the admin replies about this order.') ?></p>
	    	<br/>
	    	<?php echo $this->bbslist($this->messages); ?>
	    	
	    	<?php if(Orders::IsCommentable($this->orderid)): ?>
	            <p><?php echo $form->note->render()?></p>
	            <p align="right"><?php echo $form->save->render();?></p>
	        <?php endif; ?>
	            
	            <?php if(!Orders::IsCommentable($this->orderid)): ?>
	        	<div class="text-right"><a class="btn btn-danger" href="/tickets/new"><?php echo $this->translate('Open a ticket')?></a></div>    
	        <?php endif; ?>
	        <?php echo $form->order_id->render()?>
	    </form>        
    </div>
</div>