<?php $form = $this->form; ?>
<?php echo $this->render('partials/header.phtml') ?>

<div class="row">
	<div class="large-12 column">	
		<p align="right" class="order-buttons">
			<a href="/orders" class="small button"><?php echo $this->translate('Order list')?></a> 
			<a href="/orders/print/id/<?php echo $this->orderid?>" class="small button"><?php echo $this->translate('Print Order')?></a> 
            <?php if($this->invoiced): ?>
                <a href="/orders/createinvoice/id/<?php echo $this->invoice_id?>" class="small button"><?php echo $this->translate('Print Invoice')?></a> 
            <?php else: ?>
            	<?php if(Orders::IsEraseable($this->orderid, $this->customer_id)): ?> 
            		<a href="/orders/setdelete/id/<?php echo $this->orderid?>" class="small button confirm"><?php echo $this->translate('Delete')?></a>
            	<?php endif; ?> 
            <?php endif; ?>
        </p> 
	</div>
</div>

<div class="row">
	<div class="large-12 column">	
		<?php echo $this->status($this->statushistory);?>  
	</div>
</div>

<div class="row">
	<div class="large-12 column">	
		<?php echo $this->verticalgrid($this->order)?> 
	</div>
</div>

<div class="row">
	<div class="large-12 column">	
		<?php echo $this->simplegrid($this->details)?>
	</div>
</div>

<div class="row">
	<div class="large-12 column">	
		<?php if(Null !== Settings::findbyParam('Conditions')): ?>
        	<p class="conditions"><?php echo $this->translate(Settings::findbyParam('Conditions')) ?></p><br/>
        <?php endif;?>
	</div>
</div>

<div class="row">
	<div class="large-12 column">	
		<?php // Files attached ?>
        <?php if($this->files[0]): ?>
    	<ul>
    		<?php foreach($this->files as $files): ?>
    		<li>- <a href="/documents/customers/<?php echo $this->customer_id ?>/orders/<?php echo $this->orderid ?>/<?php echo $files['file'] ?>"><?php echo $files['file']?></a></li>
    		<?php endforeach; ?>
    	</ul>
    	<?php endif; ?>
	</div>
</div>        

<?php // Methods of payment ?>
 <?php if($this->tobepaid): ?>
    <?php echo $this->payments()->getPaymentsForm('order', $this->orderid);?>
 <?php endif;?>

<div class="row">
	<div class="large-12 column">	
	    <form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	    	<h5><?php echo $this->translate('Messages')?></h5>
	    	<p><?= $this->translate('Here you can read all your questions and the admin replies about this order.') ?></p>
	    	
	    	<?php echo $this->bbslist($this->messages); ?>
	    	
	    	<?php if(Orders::IsCommentable($this->orderid)): ?>
	            <p><?php echo $form->note->render()?></p>
	            <p align="right"><?php echo $form->save->render();?></p>
	        <?php endif; ?>
	            
	            <?php if(!Orders::IsCommentable($this->orderid)): ?>
	        	<br/><a class="small button alert" href="/tickets/new"><?php echo $this->translate('Open a ticket')?></a>    
	        <?php endif; ?>
	            <?php echo $form->order_id->render()?>
	</form>        
</div>
</div>