<div class="headtitle">
    <h3>
    <?php 
            echo $this->translate($this->title);
            if(!empty($this->name)){
                echo ": " . $this->name;
            } 
        ?>
    </h3>
    <small><?php echo $this->translate($this->description);?></small>
</div>

<div class="row">
    <div class="col-lg-12 text-right"><a class="btn btn-default" href="/default/orders/download"><?php echo $this->translate('Download Invoices')?></a></div><br/>
</div>
<?php echo $this->grid($this->orders);?>
