<?php echo $this->render('includes/startpage.phtml') ?>

	<?php echo $this->blocks()->showblock('startbody');?>
    <div id="container" class="homepage">
    	
		<?php echo $this->render('includes/top.phtml') ?>
		<div id="slideshow">
			<div class="center">
				<?php echo $this->slideshow();?>
			</div>
		</div>
		<?php echo $this->render('includes/content-header.phtml') ?>
		<?php echo $this->blocks()->showblock('beforecontent');?>
		<div id="content">
			<div class="outerShadow"></div>
			<div class="innerShadow"></div>
            <div class="center">
            	<div class="clearfix"></div>
				<?php echo $this->Messages($this->mex)?>
                <?php echo $this->blocks()->showblock('contentstart');?>
                <?php echo $this->layout()->content ?>
                <?php echo $this->blocks()->showblock('contentend');?>
                <div class="clearfix"></div>
            </div>      
		</div> 
				
		<?php echo $this->blocks()->showblock('beforefooter');?>
        <div id="footer">
        	<div class="center clearfix">
	            <?php echo $this->footer();?>
	            <?php echo $this->blocks()->showblock('footer');?>
	        </div>
        </div><!-- End #footer -->
        <?php echo $this->blocks()->showblock('endfooter');?>
    </div>	<!-- End #main-container -->
    
    <?php echo $this->blocks()->showblock('endbody');?>
    
<?php echo $this->render('includes/endpage.phtml') ?>

