<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
		
	<div id="tabs">
		<ul>
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Options');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('System');?></a></li> 
		</ul>	
		<div class="tab-pane default-tab" id="tab1">  	
		    <fieldset class="column-left">  
				<?php echo $form->code->render() ?>
				<?php echo $form->type->render() ?>
				<?php echo $form->label->render() ?>
				<?php echo $form->description->render() ?>
		    </fieldset>
		    <fieldset class="column-right"> 
		    	<?php echo $form->is_visible_on_front->render() ?>
				<?php echo $form->active->render() ?>
				<?php echo $form->is_required->render() ?>
				<?php echo $form->position->render() ?>
		    </fieldset>
		    <div class="clear"></div>
	    </div>
	    
	    <div class="tab-pane default-tab" id="tab2">
	    	<?php echo $form->is_comparable->render() ?>
	    	<?php echo $form->defaultvalue->render() ?>
	    	<?php echo $form->prefix->render() ?>
			<?php echo $form->suffix->render() ?>
			<?php echo $form->on_product_listing->render() ?>
	    </div>
	      	
	    <div class="tab-pane default-tab" id="tab3">
	    	<?php echo $form->system->render() ?>
	    	<?php echo $form->system_var->render() ?>
	    </div>
	      	
	    <?php echo $form->language_id->render() ?>
	    <?php echo $form->attribute_id->render()?>
    </div>
</form>
</div>
