<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
		
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Options');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('System');?></a></li> 
		</ul>
		
		<div class="tab-content">	
			<div class="tab-pane active" id="tab1">  	
			    <div class="col-sm-6 col-xs-12">  
					<?php echo $form->code->render() ?>
					<?php echo $form->type->render() ?>
					<?php echo $form->label->render() ?>
					<?php echo $form->description->render() ?>
			    </div>
			    <div class="col-sm-6 col-xs-12"> 
			    	<?php echo $form->is_visible_on_front->render() ?>
					<?php echo $form->active->render() ?>
					<?php echo $form->is_required->render() ?>
					<?php echo $form->position->render() ?>
			    </div>
		    </div>
		    
		    <div class="tab-pane" id="tab2">
		    	<?php echo $form->is_comparable->render() ?>
		    	<?php echo $form->defaultvalue->render() ?>
		    	<?php echo $form->prefix->render() ?>
				<?php echo $form->suffix->render() ?>
				<?php echo $form->on_product_listing->render() ?>
		    </div>
		      	
		    <div class="tab-pane" id="tab3">
		    	<?php echo $form->system->render() ?>
		    	<?php echo $form->system_var->render() ?>
		    </div>
		      	
		    <?php echo $form->language_id->render() ?>
		    <?php echo $form->attribute_id->render()?>
	    </div>
	</div>	    
</form>

