<h3><?php echo $this->translate('Login or Create a new Account')?></h3><hr>   
	
<div class="row">  
    <div class="col-lg-6">
    	<fieldset class="login">
	        <h5><?=$this->translate('Create a new Account')?></h5>
	        <p>
	            <?php echo $this->translate('By creating an account with our store, you will be able to move through the checkout process faster, view and track your orders in your account and more.')?>
	        </p>
	        <a class="button" href="/customer/signup"><?= $this->translate('Create an Account') ?></a>
		</fieldset>
    </div>
    
    <div class="col-lg-6">
        <?php if($this->form):?>
            <? $form = $this->form; ?>
            <form method="<?php echo $form->getMethod() ?>" class="custom" action="<?php echo $form->getAction()?>">
                <fieldset class="login">
                    <h5><?=$this->translate('Login')?></h5>
                    <p><?echo $this->translate('Sign in to get subscribed services.')?></p>
                    <?php echo $form->email->render() ?>
                    <?php echo $form->password->render() ?>
                    <p align="right"><a href="/index/password"><?php echo $this->translate('Forgot your password?'); ?></a></p>
                    <?php echo $form->login->setDecorators(array('ViewHelper')) ?>
                </fieldset>
            </form>
        <?php endif;?>
    </div>
</div>


