<h3><?php echo $this->translate('Login or Create a new Account')?></h3><hr>   
	
<div class="row">  
    <div class="col-lg-6">
    	<fieldset class="login">
	        <h3><?php echo $this->translate('Create a new Account')?></h3>
	        <p>
	            <?php echo $this->translate('By creating an account with our store, you will be able to move through the checkout process faster, view and track your orders in your account and more.')?>
	        </p><br/><br/>
	        <a class="btn btn-success btn-lg" href="/customer/signup"><?php echo $this->translate('Create an Account') ?></a>
		</fieldset>
    </div>
    
    
        <?php if($this->form):?>
            <? $form = $this->form; ?>
            <div class="col-lg-6">
	            <form method="<?php echo $form->getMethod() ?>" class="custom" action="<?php echo $form->getAction()?>">
                    <h3><?php echo $this->translate('Login')?></h3>
                    <p><?echo $this->translate('Sign in to get subscribed services.')?></p>
                    <?php echo $form->email->render() ?>
                    <?php echo $form->password->render() ?>
                    <div class="row">
                    	<div class="col-lg-6"><a href="/index/password"><?php echo $this->translate('Forgot your password?'); ?></a></div>
                    	<div class="col-lg-6 text-right"><?php echo $form->login->setDecorators(array('ViewHelper')) ?></div>
                    </div>
	            </form>
	    	</div>
        <?php endif;?>
</div>


