<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">
	
	<?php echo $this->Exception($form); ?>
	
	<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
		
		<div id="tabs">
			<ul>
				<li><a href="#tab1"><?=$this->translate('Main');?></a></li> 
				<li><a href="#tab2"><?=$this->translate('Options');?></a></li> 
			</ul>
	    
		    <div id="tab1"> 
	            <?php echo $form->name->render()?>
	            <?php echo $form->account->render()?>
	            <?php echo $form->method_id->render()?>
	            <?php echo $form->url_test->render()?>
	            <?php echo $form->url_official->render()?>
	            <?php echo $form->enabled->render()?>
	            <?php echo $form->classname->render()?>
	            <?php echo $form->test_mode->render()?>
		    </div>
		    
		    <div class="ui-tabs-hide" id="tab2">
		    	<?php echo $form->description->render()?>
		    </div>
	   		<?php echo $form->bank_id->render()?>
	   	</div>
	</form>
</div>	
