<?php $i = 0;?>
<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

	<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
        
        <div class="tabbable" id="tabs">
	        <ul class="nav nav-tabs">
				<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
				<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Attachments');?></a></li> 
				<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Options');?></a></li> 
			</ul>
			
			<div class="tab-content">
				<div class="tab-pane active" id="tab1">
				  
			        <?php echo $this->verticalgrid($this->datagrid)?>
			        
			        <?php if(!empty($this->record['sibling_id'])): ?>
			        	<div class="relationship"><?php echo $this->translate('Relationships'); ?>: <a href="/admin/tickets/edit/id/<?php echo $this->record['sibling'][0]['ticket_id'] ?>"><?php echo $this->record['sibling'][0]['subject']?></a></div>
			        <?php endif; ?>
			        
			        <?php if("new" == Zend_Controller_Front::getInstance ()->getRequest ()->getActionName ()):?>
			        	<div class="row-fluid"> 
							<div class="span6"><?php echo $form->subject->render()?></div>
				        	<div class="span6"><?php echo $form->category_id->render()?></div>
			        	</div>
			        <?php endif;?>
			        
					<?php if(!empty($this->record)): ?>            
			            <div class="media-list">
			            	<div class="media">
				                <div class="pull-left hidden-phone"><?php echo $this->customeravatar ?></div>
				                <div class="media-body">
				                	<h4 class="media-heading"><a href="/admin/customers/edit/id/<?php echo $this->customerid ?>"><?php echo $this->record['fullname'];?></a> <a href="/admin/customers/edit/id/<?php echo $this->customerid ?>"><?php echo $this->record['company'];?></a> - <small><?php echo $this->record['date_open'];?></small></h4>
				                	<?php echo $this->record['description'];?>
				                	<?php if(!empty($this->notes)):?>
				                	<div class="media">
						                <?php foreach( $this->notes as $note):?>
						                	<div class="media">
							                	<div class="pull-left hidden-phone"><?php echo Shineisp_Commons_Gravatar::get_gravatar ( $this->record ['email'], 50); ?></div>
							                	<div class="media-body">
							                		<h4 class="media-heading"><?php if($note['adminreply']):?>Administrator<?php else:?><a href="/admin/customers/edit/id/<?php echo $this->customerid ?>"><?php echo $this->record['fullname'];?></a> <a href="/admin/customers/edit/id/<?php echo $this->customerid ?>"><?php echo $this->record['company'];?></a><?php endif;?> <small><?php echo $note['date_post']?> - <a class="confirm" href="/admin/tickets/deletenote/id/<?php echo $note['note_id'] ?>"><?php echo $this->translate('Delete')?></a></small></h4>
							                		<?php echo $note['reply']?>	                		
							                	</div>
						                	</div>
						                	<?php $i++; ?>
						                <?php endforeach;?>
						    		</div>
					        		<?php endif;?>
				                </div>
				       		</div>
			            </div>
			        <?php endif;?>
			        <hr/>
			        <?php echo $form->note->render()?>
				</div>
				
				<div class="tab-pane" id="tab2">
					<?php echo $this->Attachments($this->record['ticket_id'], 'tickets'); ?>
					<?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
		            	<?php echo $form->attachments->render()?>
		            <?php endif;?>
				</div>
				
				<div class="tab-pane" id="tab3">
	
			        <div class="span6"> 
			        	<?php echo $form->user_id->render()?>
			        	<?php echo $form->order_id->render()?>
			        	<?php echo $form->sibling_id->render()?>
			        	<?php if(!empty($this->siblings)): ?>
			            	<div class="inputitem">
			            	<label for="siblings"><?php echo $this->translate('Go to'); ?>:</label>
			            	<select id="siblings" class="text-input little-input goto">
			            		<?php foreach ($this->siblings as $id => $sibling): ?>
			            			<option value="/admin/tickets/edit/id/<?php echo $id ?>"><?php echo $sibling?></option>
			            		<?php endforeach;?>
			            	</select></div>
			        	<?php endif; ?>
			        </div>
			        
			        <div class="span6">
					    <?php echo $form->sendemail->render()?>	
				        <?php echo $form->status_id->render()?>
				        <?php echo $form->datetime->render()?>
					</div>    
				    
					<?php echo $form->ticket_id->render()?>			  
				</div>
			
			</div>
		</div>
	</form>