<?php

/**
 * EmailsTemplatesSends
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EmailsTemplatesSends extends BaseEmailsTemplatesSends
{

	/**
	 * getByCustomerID
	 * Get all data  
	 * @param $customerID
	 * @return Array
	 */
	public static function getByCustomerID($customerID, $fields = '*') {
		$records = Doctrine_Query::create ()->select ( $fields )
							->from ( 'EmailsTemplatesSends' )
							->where ( 'customer_id = ?', intval($customerID) )
							->orderBy('id desc')
							->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		
		return $records;
	}


}