<?php

/**
 * FilesCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class FilesCategories extends BaseFilesCategories {
	public static function getList() {
		$registry = Zend_Registry::getInstance();
		$items = array ();
		$arrTypes = Doctrine::getTable ( 'FilesCategories' )->findAll ();
		foreach ( $arrTypes->getData () as $c ) {
			$items [$c ['category_id']] = $registry->Zend_Translate->translate($c ['name']);
		}
		return $items;
	}
}