<?php

/**
 * Files
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Files extends BaseFiles {
	
	/**
	 * Save the file information in the database
	 * @param string $filepath
	 * @param string $attachedto
	 * @param integer $id
	 * @param integer $categoryID (default 3 - Documents)
	 */
	public static function saveit($filename, $path, $attachedto, $id, $categoryID=3) {
		$file = new Files();
		$file->file = $filename;
		$file->path = $path;
		$file->attachedto = $attachedto;
		$file->id = $id;
		$file->date = date('Y-m-d H:i:s');
		$file->ip = $_SERVER['REMOTE_ADDR'];
		$file->category_id = $categoryID;
		return $file->trySave();
	}
	
	/**
	 * find
	 * Get a record by ID
	 * @param $id
	 * @return Doctrine Record
	 */
	public static function find($id) {
		return Doctrine::getTable ( 'Files' )->find ($id );
	}
	
	/**
	 * Get a file by its id
	 * @param $id
	 * @return array
	 */
	public static function get_by_id($id) {
		$file = Doctrine_Query::create ()->from( 'Files' )
									   	   ->where ( "file_id = ?", $id )
									   	   ->limit(1)
									       ->execute ( array (), Doctrine_Core::HYDRATE_ARRAY );
		
		return !empty($file[0]) ? $file[0] : array();
	}
	
	/**
	 * Delete the file
	 * @param $id
	 * @return boolean
	 */
	public static function del($id) {
		$file = Doctrine_Query::create ()->from( 'Files' )
									   	   ->where ( "file_id = ?", $id )
									       ->execute ( array (), Doctrine_Core::HYDRATE_ARRAY );
		// Delete the file
		if(!empty($file[0])){
			@unlink(PUBLIC_PATH . $file[0]['path'] . "/" . $file[0]['file']);
		}	
		
		// Delete the record
		Doctrine::getTable ( 'Files' )->findOneBy ( 'file_id', $id )->delete();
		return true;
	}
	
	/**
	 * Delete all the files of a customer
	 * @param $id
	 * @return boolean
	 */
	public static function delete_all_by_customerId($id) {
		
		$files = Doctrine_Query::create ()->from( 'Files' )
									   	   ->where ( "id = ?", $id )
									   	   ->addWhere ( "attachedto = ?", 'customers' )
									       ->execute ( array (), Doctrine_Core::HYDRATE_ARRAY );

		// Delete all the files and record
		foreach($files as $file){
			@unlink(PUBLIC_PATH . $file['path'] . "/" . $file['file']);
			
			// Delete the record
			Doctrine::getTable ( 'Files' )->findOneBy ( 'file_id', $file['file_id'] )->delete();
		}	
									       
		return true;
	}
	
	/**
	 * findbyExternalId
	 * Get a record by the external ID
	 * @param $id, $attachedto [orders, customers], $fields="*"
	 * @return Doctrine Record
	 */
	public static function findbyExternalId($id, $attachedto, $fields="*") {
		
		return Doctrine_Query::create ()->select($fields)
									   	->from( 'Files f' )
									   	->leftJoin('f.FilesCategories fc')
									   	->where ( "f.id = ?", $id )
									    ->andWhere ( "attachedto = ?", $attachedto )
									    ->execute ( array (), Doctrine_Core::HYDRATE_ARRAY );
										
	}

}