<?php

/**
 * Navigation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Navigation extends BaseNavigation
{
	/**
	 * findAll
	 * Get all the items of a particular module
	 * @param unknown_type $module
	 */
	public static function findAll($module="default") {
		return Doctrine_Query::create ()->from ( 'Navigation' )->where ( 'module = ?', $module )->execute ( null, Doctrine::HYDRATE_ARRAY );
    }
    
    /**
     * getNavItems
     * List of all navigation items
     * @return array
     */
    public static function getNavItems($module) {
        $dq = Doctrine_Query::create ()
        					->select ( "n.label as label, n.description as desc, uri as url" )
        					->from ( 'Navigation n' )
        					->where ( 'module = ?', $module )
        					->andWhere ( 'parent_id = ?', 0 );
        return $dq->execute ( null, Doctrine::HYDRATE_ARRAY );
    }    
    
    /**
     * getParent
     * Get the parent item
     * @return array
     */
    public static function getParent($parent, $module="admin") {
    	$auth = Zend_Auth::getInstance ();
    	$controllers = array();
    	
        $record = Doctrine_Query::create ()
        					->select ( "n.id, n.label as label, n.description as desc, uri as url, n.parent_id" )
        					->from ( 'Navigation n' )
        					->where ( 'parent_id = ?', $parent )
        					->andWhere( 'module = ?', $module );
        
        // Hide some resources within the list
        if ($auth->hasIdentity()) {
        	$identity = $auth->getIdentity();
        	
        	if($identity['AdminRoles']['name'] != "administrator"){
        		
        		// Get all the controllers enabled by the ACL system
	        	foreach ($identity['AdminRoles']['AdminPermissions'] as $permission){
	        		$controllers[] = $permission['AdminResources']['controller'];
	        	}
	        	// Add the condition to the query
	        	if(!empty($controllers)){
	        		$record->whereIn('controller', $controllers);
	        	}
        	}
        	
        }
        
        
        return $record->execute ( null, Doctrine::HYDRATE_ARRAY );
    } 

	
	/*
     * CreateMenu
     * Create a simple Zend_Navigation Configuration array
     */
	public static function CreateMenu($items,  $parent_id = 0, $level = 0) {
		
		$tmp_arr = array ();
		$tmp_items = self::GetItems ( $items, $parent_id );
		for($i = 0; $i < count ( $tmp_items ); $i ++) {
			$level ++;
			$children = self::CreateMenu ( $items, $tmp_items [$i] ['id'], $level );
			$level --;
			$tmp_arr [] = array ('label' => $tmp_items [$i] ['label'], 'id'=>$tmp_items [$i] ['label'], 'description'=>$tmp_items [$i] ['description'], 'uri' => $tmp_items [$i] ['uri'], 'pages' => $children );
		}
		return $tmp_arr;
	}
	
	/*
     * GetItems
     * Get all the childs reading the main array 
     */
	public static function GetItems($items, $parent_id) {
		$tmp_array = array ();
		for($i = 0; $i < count ( $items ); $i ++) {
			if ($items [$i] ['parent_id'] == $parent_id) {
				$tmp_array [] = $items [$i];
			}
		}
		return $tmp_array;
	}    
}
