<?php

/**
 * ProductsRelated
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ShineISP
 * 
 * @author     Shine Software <info@shineisp.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductsRelated extends BaseProductsRelated {
	
	/**
	 * Delete all the products related with a specific product id
	 * 
	 * 
	 * @param integer $product_id
	 */
	public static function delItemsbyProductID($product_id) {
		return Doctrine_Query::create ()->delete ()
										->from ( 'ProductsRelated pr' )
										->whereIn ( 'pr.product_id', $product_id )
										->execute ();
	}
	
	/**
	 * getItemsbyProductID
	 * Get all the products related with a specific product id
	 * @param integer $product_id
	 */
	public static function getItemsbyProductID($product_id) {
		$data = array ();
		$related = Doctrine_Query::create ()
		              ->select ()
		              ->from ( 'ProductsRelated pr' )
                      ->leftJoin('pr.Products p')
		              ->where ( 'pr.product_id = ?', $product_id )
                      ->addWhere( "p.isp_id = ?", Isp::getCurrentId() )
		              ->execute ( array (), Doctrine_Core::HYDRATE_ARRAY );
		
		if (! empty ( $related )) {
			foreach ( $related as $item ) {
				$data [] = $item ['related_product_id'];
			}
		}
		
		return $data;
	}
	
	/**
	 * Get the related products starting 
	 * by a specific product_id
	 * excluding itself
	 * 
	 * @param integer $product_id
	 */
	public static function get_products($product_id, $locale="1") {
		$related = Doctrine_Query::create ()->select ("pr.related_id, p.product_id as product_id, p.uri as uri, p.price_1 as price, pd.name as name, pd.shortdescription as description, p.ishighlighted as ishighlighted")
						->from ( 'ProductsRelated pr' )
						->leftJoin('pr.Products p')
						->leftJoin("p.ProductsData pd WITH pd.language_id = $locale")
						->where ( 'pr.product_id = ?', $product_id )
                        ->addWhere( "p.product_id <> ?", $product_id )
                        ->addWhere( "p.isp_id = ?", Isp::getCurrentId() )
						->orderBy('p.group_id, p.position')
						->execute ( array (), Doctrine_Core::HYDRATE_ARRAY );
		
		return $related;
	}
}