<?php

/**
 * ProductsUpgrades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductsUpgrades extends BaseProductsUpgrades {
	
	/**
	 * Delete all the products related with a specific product id
	 * 
	 * 
	 * @param integer $product_id
	 */
	public static function delItemsbyProductID($product_id) {
		return Doctrine_Query::create ()->delete ()
										->from ( 'ProductsUpgrades pu' )
										->whereIn ( 'pu.product_id', $product_id )
										->execute ();
	}
	
	/**
	 * getItemsbyProductID
	 * Get all the products upgrade with a specific product id
	 * @param integer $product_id
	 */
	public static function getItemsbyProductID($product_id) {
		$data = array ();
		$upgrades = Doctrine_Query::create ()->select ()->from ( 'ProductsUpgrades pu' )
														->where ( 'pu.product_id = ?', $product_id )
														->execute ( array (), Doctrine_Core::HYDRATE_ARRAY );
		
		if (! empty ( $upgrades )) {
			foreach ( $upgrades as $item ) {
				$data [] = $item ['upgrade_product_id'];
			}
		}
		
		return $data;
	}	
	
	/**
	 * getUpgradesbyProductID
	 * Get all the products upgrade with a specific product id
	 * @param integer $product_id
	 */
	public static function getUpgradesbyProductID($product_id,$locale = 1) {
		$data = array ();
		$doctrine	= Doctrine_Query::create ();
		$upgrades = $doctrine->select ('pu.upgrade_product_id, pd.name as productname')
						->from ( 'ProductsUpgrades pu' )
						->leftJoin('pu.Products p')
						->leftJoin ( "p.ProductsData pd WITH pd.language_id = $locale" )
						->where ( 'pu.product_id = ?', $product_id );
		$upgrades = $doctrine->execute ( array (), Doctrine_Core::HYDRATE_ARRAY );
		if (! empty ( $upgrades )) {
			foreach ( $upgrades as $item ) {
				$data [$item['upgrade_product_id']] = $item ['productname'];
			}
		}
		
		return $data;
	}
	
	/**
	 * Get all the products upgrade with a specific product id
	 * @param integer $product_id
	 */
	public static function get_products($product_id, $locale="1") {
		$upgrade = Doctrine_Query::create ()
					->select ("pu.upgrade_id, p.product_id as product_id, p.uri as uri, p.price_1 as price, pd.name as name, pd.shortdescription as description")
					->from ( 'ProductsUpgrades pu' )
					->leftJoin('pu.Products p')
					->leftJoin("p.ProductsData pd WITH pd.language_id = $locale")
					->where ( 'pu.product_id = ?', $product_id )
					->orderBy('p.group_id, p.position')
					->execute ( array (), Doctrine_Core::HYDRATE_ARRAY );
		
		return $upgrade;
	}
}