<?php

/**
 * PurchaseCategories
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ShineISP
 * 
 * @author     Shine Software <info@shineisp.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PurchaseCategories extends BasePurchaseCategories
{
   /**
     * getList
     * Get a list ready for the html select object
     * @return array
     */
    public static function getList() {
        $items = array ();
        
        $records = Doctrine_Query::create ()->from ( 'PurchaseCategories' )->execute ()->toArray ();
        foreach ( $records as $c ) {
            $items [$c ['category_id']] = $c ['category'];
        }
        
        return $items;
    }
    
    /**
     * grid
     * create the configuration of the grid
     */
    public static function grid($rowNum = 10) {
    
    	$translator = Shineisp_Registry::getInstance ()->Zend_Translate;
    
    	$config ['datagrid'] ['columns'] [] = array ('label' => null, 'field' => 'c.category_id', 'alias' => 'category_id', 'type' => 'selectall' );
    	$config ['datagrid'] ['columns'] [] = array ('label' => $translator->translate ( 'Id' ), 'field' => 'c.category_id', 'alias' => 'category_id', 'sortable' => true, 'searchable' => true, 'type' => 'string' );
    	$config ['datagrid'] ['columns'] [] = array ('label' => $translator->translate ( 'Category' ), 'field' => 'c.category', 'alias' => 'category', 'sortable' => true, 'searchable' => true, 'type' => 'string' );
    
    	$config ['datagrid'] ['fields'] = "category_id, category";
    	$config ['datagrid'] ['rownum'] = $rowNum;
    
    	$config ['datagrid'] ['dqrecordset'] = Doctrine_Query::create ()->select ( $config ['datagrid'] ['fields'] )->from ( 'PurchaseCategories c' );
    
    	$config ['datagrid'] ['basepath'] = "/admin/purchasescategories/";
    	$config ['datagrid'] ['index'] = "category_id";
    
    	return $config;
    }
    
    /**
     * getAllInfo
     * Get all data with the File category ID
     * @param $id
     * @return Doctrine Record / Array
     */
    public static function getAllInfo($id, $fields = "*", $retarray = false) {
    
    	try {
    		$dq = Doctrine_Query::create ()->select ( $fields )
    		->from ( 'PurchaseCategories c' )
    		->where ( "category_id = $id" )
    		->limit ( 1 );
    
    		$retarray = $retarray ? Doctrine_Core::HYDRATE_ARRAY : null;
    		$item = $dq->execute ( array (), $retarray );
    
    		return $item;
    	} catch (Exception $e) {
    		die ( $e->getMessage () );
    	}
    }
    
    /**
     * findbyName
     * Get a filecategory record using its name.
     * @param $name
     * @return unknown_type
     */
    public static function findbyName($name) {
    	return Doctrine::getTable ( 'PurchaseCategories' )->findOneBy ( 'name', $name )->toArray();
    }
    
    /**
     * find
     * Get a record by ID
     * @param $id
     * @return Doctrine Record
     */
    public static function find($id, $fields = "*", $retarray = false) {
    	$dq = Doctrine_Query::create ()->select ( $fields )->from ( 'PurchaseCategories c' )
    	->where ( "category_id = $id" )->limit ( 1 );
    
    	$retarray = $retarray ? Doctrine_Core::HYDRATE_ARRAY : null;
    	$records = $dq->execute ( array (), $retarray );
    	return $records;
    }
}