<?php $currency = Settings::findbyParam('currency'); ?>
<?php $form = $this->form; ?>
<?php $price = $this->prices; ?>

<div class="row">   
	<div class="large-12">   
		
		<? if( $form->isErrors() ): ?>
		    <div class="messages">    
		       <? foreach( $form->getElements() as $field){
		             $errors = array();
		             if($field->hasErrors()){
		                foreach( $field->getErrors() as $error){
		                    $errors[] = $this->translate($error);
		                }
		                echo "<div data-alert class=\"alert-box alert\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
		            }   
		        } ?>
		    </div>    
		<?php endif; ?>
		
		<?php echo $this->blocks()->showblock('products_start');?>
		
		<form method="<?php echo $form->getMethod() ?>" id="productdetail" class="custom dropdown" action="<?php echo $form->getAction()?>">
				
		        <div class="row">
		        	<div class="large-12 column">
			       	    <h3><?php echo $this->product['name'] ?></h3>
			       	    
			       	    <?php echo $this->ProductCategories($this->product['categories']) // Category Breadcrump ?>
			       	    
			       	    <ul class="no-bullet inline-list">
			       	    	<li><a href="/products/addreview/id/<?php echo $this->product['product_id'] ?>"><?php echo $this->translate('Add your review') ?></a></li>
			       	    	<li><?php if($this->product['iscomparable'] && !empty($this->group['code'])): ?><a href="/compare/products/code/<?php echo $this->group['code'] ?>"><?php echo $this->translate('Compare') ?> <?php echo $this->group['name']?></a><?php endif; ?></li>
			       	    </ul>
			    	</div>
		        </div>	    
		
			    <div class="row" id="product">
			    
		            <div class="large-4 column" id="product-images">
		                <?php echo $this->media()->ProductImage($this->product['product_id'], 200, 200, true);?>
		                
		                <?php if($price['type'] == "multiple"): ?>
			                <ul class="sticker no-bullet hidden">
			                   <li><?php echo $this->translate('just')?> <span id="priceval" class="priceval"><?php echo $this->product['price_1'] ?></span><em>x</em> <em id="pricefreq"></em></li>
			                   <li><span id="pricetaxval"></span> <?php echo $this->translate('VAT included')?></li>
			                   <li><span id="setupfeecontainer"><?php echo $this->translate('Setup fee')?>: <span id="setupfee"></span></span></li>
			                   <li><span id="tranche_includes"></span></li> 
			                </ul>
		                <?php else: ?>
		                 	<ul class="sticker no-bullet hidden">
		                 		<li><?php echo $this->translate('just')?><span id="priceval" class="priceval"><?php echo $this->currency($price['value'], array('currency' => Settings::findbyParam('currency'))) ?></span></li>
			                    <li><span id="pricetaxval"><?php echo $price['taxincluded'] ?></span> <?php echo $this->translate('VAT included')?></li>
			                </ul>
		                <?php endif;?>
		                
	                	<?php echo $this->blocks()->showblock('products_after_price');?>              
		            </div>
		            
		            <div class="large-8 column">
	
		                <div class="row">
		                	<div class="large-8 column">
		                		<?php echo $this->blocks()->showblock('products_before_shortdescription');?>
		                		<?php echo $this->product['shortdescription']?>
		                		<?php echo $this->blocks()->showblock('products_after_shortdescription');?>
		                	</div>
		                	<div class="large-4 column">
			                    <?php $button = ($this->product['type'] == "hosting") ? $this->translate('Subscribe') : $this->translate('Add to cart') ?>
			                    <?php echo $form->submit->render()?>
			                </div>
		                </div>
		                
		                <div class="row">
		                	<div class="large-12 column">
		                		<?php echo $form->quantity->render()?>
		                	</div>
		                </div>
		                
		                <div class="row">
		                	<div class="large-12 column">
		                		<?php echo $this->blocks()->showblock('products_before_keywords');?>
				             	<?php if(!empty($this->product['metakeywords'])): ?>
				                    <div class="keywords">
				                        <?php echo $this->translate('Keywords') ?>: <?php echo $this->product['metakeywords']?>
				                    </div>
			                	<?php endif;?>
	                			<?php echo $this->blocks()->showblock('products_after_keywords');?>
	                		</div>
	                	</div>
		            </div> 	                
		                
			    </div>
			    
			    <div class="row">
			    	<div class="large-12 column">
			    	
			            <?php echo $this->blocks()->showblock('products_before_description');?>
			            <div class="description"><?php echo $this->product['description']?></div> 
			            <?php echo $this->blocks()->showblock('products_after_description');?>
			            <br/><br/>
			            <?php echo $this->blocks()->showblock('features');?>
			            
			            <div class="clear"></div>
			    	</div>
			    </div>
			<?php echo $form->isrecurring->render()?>
		</form>
		
		
		<?php echo $this->reviews($this->reviewsdata)?>
		
		<?php echo $this->blocks()->showblock('products_end');?>
	</div>
</div>