<?php $currency = Settings::findbyParam('currency'); ?>
<?php $form = $this->form; ?>
<?php $price = $this->prices; ?>

<div class="row">   
	<div class="col-lg-12 col-md-12 col-xs-12">   
		<? if( $form->isErrors() ): ?>
		    <div class="messages">    
		       <? foreach( $form->getElements() as $field){
		             $errors = array();
		             if($field->hasErrors()){
		                foreach( $field->getErrors() as $error){
		                    $errors[] = $this->translate($error);
		                }
		                echo "<div data-alert class=\"alert-box alert\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
		            }   
		        } ?>
		    </div>    
		<?php endif; ?>
		
		<?php echo $this->blocks()->showblock('products_start');?>
		
		<form method="<?php echo $form->getMethod() ?>" id="productdetail" class="custom dropdown" action="<?php echo $form->getAction()?>">
				
		        <div class="row">
		        	<div class="col-lg-12 col-md-12 col-xs-12">
			       	    <h3><?php echo $this->product['name'] ?></h3>
			       	    <?php echo $this->ProductCategories($this->product['categories']) // Category Breadcrump ?>
			       	    <ul class="list-unstyled list-inline">
			       	    	<li><a href="/review/<?php echo $this->product['uri'] ?>.html"><?php echo $this->translate('Add your review') ?></a></li>
			       	    	<li><?php if($this->product['iscomparable'] && !empty($this->group['code'])): ?><a href="/compare/products/code/<?php echo $this->group['code'] ?>"><?php echo $this->translate('Compare') ?> <?php echo $this->group['name']?></a><?php endif; ?></li>
			       	    </ul>
			    	</div>
		        </div>	    
		
			    <div class="row" id="product">
			    
		            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" id="product-images">
		            	<div class="row">
		        			<div class="media col-lg-12 col-md-12 col-xs-12">
		                		<?php echo $this->media()->ProductImage($this->product['product_id'], 240, 200, true);?>
		                	</div>
		                	<div class="col-lg-12 col-md-12 col-xs-12">
				                <?php if($price['type'] == "multiple"): ?>
					                <ul class="list-unstyled">
					                   <li class="price"><?php echo $this->translate('just')?> <span id="priceval" class="priceval"><?php echo $this->product['price_1'] ?></span> <em>x</em> <em id="pricefreq" class="pricefreq"></em></li>
					                   <li class="pricetaxval"><span id="pricetaxval"></span> <?php echo $this->translate('Tax included')?></li>
					                   <li class="setupfeecontainer"><span id="setupfeecontainer"><?php echo $this->translate('Setup fee')?>: <span id="setupfee"></span></span></li>
					                   <li class="setupfeecontainer"><span id="tranche_includes" class="tranche_includes"></span></li> 
					                </ul>
				                <?php else: ?>
				                 	<ul class="list-unstyled">
				                 		<li class="price"><?php echo $this->translate('just')?> <span id="priceval" class="priceval"><?php echo $this->currency($price['value'], array('currency' => Settings::findbyParam('currency'))) ?></span></li>
					                    <li class="pricetaxval"><span id="pricetaxval"><?php echo $this->currency($price['taxincluded'], array('currency' => Settings::findbyParam('currency'))) ?></span> <?php echo $this->translate('Tax included')?></li>
					                </ul>
				                <?php endif;?>
		                	</div>
	                		<?php echo $this->blocks()->showblock('products_after_price');?>              
		            	</div>
		            </div>
		            
		            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
	
		                <div class="row">
		                	<div class="shortdescription col-lg-12 col-md-12 col-xs-12">
		                		<?php echo $this->blocks()->showblock('products_before_shortdescription');?>
		                		<?php echo $this->product['shortdescription']?>
		                		<?php echo $this->blocks()->showblock('products_after_shortdescription');?>
		                	</div>
		                </div>
	
                        <div class="row">
                            <div class="quantity col-lg-7">
                                <div class="input-group">
                                    <?php echo $form->quantity->setDecorators(array('ViewHelper'))?>
                                    <?php echo $form->term->setDecorators(array('ViewHelper'))?>
                                    <span class="input-group-btn">
                                        <?php echo $form->submit->render()?>
                                    </span>
                                </div>
                            </div>
                            <div class="quantity col-lg-5"></div>
                        </div>
		                
		                <div class="row">
		                	<div class="col-lg-12 col-md-12 col-xs-12">
		                		<?php echo $this->blocks()->showblock('products_before_keywords');?>
				             	<?php if(!empty($this->product['metakeywords'])): ?>
				                	<small><?php echo $this->translate('Keywords') ?>: <?php echo $this->product['metakeywords']?></small>
			                	<?php endif;?>
	                			<?php echo $this->blocks()->showblock('products_after_keywords');?>
	                		</div>
	                	</div>
		            </div> 	                
		                
			    </div>
			    
			    <div class="row">
			    	<div class="description col-lg-12 col-md-12 col-xs-12">
			            <?php echo $this->blocks()->showblock('products_before_description');?>
			            <?php echo $this->product['description']?>
			            <?php echo $this->blocks()->showblock('products_after_description');?>
			    	</div>
			    </div>
			    
			    <div class="row">
			    	<div class="features col-lg-12 col-md-12 col-xs-12">
			            <?php echo $this->blocks()->showblock('features');?>
			    	</div>
			    </div>
			    
			   <?php echo $form->product_id->render()?>
		</form>
		
		<div class="row">
			<div class="reviews col-lg-12 col-md-12 col-xs-12">
				<?php echo $this->reviews($this->reviewsdata)?>
			</div>
		</div>
		
		<div class="row">
			<div class="col-lg-12 col-md-12 col-xs-12">
				<?php echo $this->blocks()->showblock('products_end');?>
			</div>
		</div>
	</div>
</div>