<?php $products = $this->products; ?>

<div id="relatedproduct" class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">
	    <h4 class="text-muted"><?php echo $this->translate('Related Products')?></h4>
        <div class="list-group">
            <?php foreach ($products as $product): ?>
                <?php if(!empty($product['name'])): ?>
                    <a href="/<?php echo $product['uri'] ?>.html" class="list-group-item <?php echo ($product['ishighlighted']) ? "active" : null?>">
                        <h4 class="list-group-item-heading"><?php echo $product['name'] ?></h4>
                        <p class="list-group-item-text"><?php echo Shineisp_Commons_Utilities::truncate(strip_tags($product['description']), 100, "...", true, true)  ?></p>
                    </a>
                <?php endif; ?>
            <?php endforeach;?>
        </div>
	</div>
</div>