<?php $products = $this->products; ?>
<div id="relatedproduct" class="row">
	<div class="large-12 column">
		<h5><?php echo $this->translate('Related Products')?></h5>
		<?php foreach ($products as $product): ?>
			<?php if(!empty($product['name'])): ?>
			<div class="row">
				<div class="large-4 column">
			    	<?php echo $this->media()->ProductImage($product['product_id'], 60, 60, false);?>
				</div>
				<div class="large-8 column">
					<h6><a href="/<?php echo $product['uri'] ?>.html"><?php echo $product['name'] ?></a></h6>
					<p><?php echo Shineisp_Commons_Utilities::truncate(strip_tags($product['description']), 100, "...", true, true)  ?></p>
				</div>
			</div>
			<?php endif; ?>
		<?php endforeach;?>
	</div>
</div>