<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Content');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Prices');?></a></li> 
			<li><a data-toggle="tab" href="#tab4"><?php echo $this->translate('Costs');?></a></li> 
		</ul>
		
    	<div class="tab-content">
		    <div class="tab-pane active" id="tab1"> 
		    	<?php echo $form->registrars_id->render()?>
	            <?php echo $form->server_id->render()?>
		        <?php echo $form->tags->render()?>
		        <?php echo $form->ishighlighted->render()?>
		        <?php echo $form->isrefundable->render()?>
		    </div>
		    
		    <div class="tab-pane" id="tab2">
		    	<?php echo $form->name->render()?>
	            <?php echo $form->description->render()?>
		    </div>
		    
		    <div class="tab-pane" id="tab3">
		    	<?php echo $form->tax_id->render()?>
	            <?php echo $form->registration_price->render()?>
	            <?php echo $form->renewal_price->render()?>
	            <?php echo $form->transfer_price->render()?>
		    </div>
		    
		    <div class="tab-pane" id="tab4">
	            <?php echo $form->registration_cost->render()?>
	            <?php echo $form->renewal_cost->render()?>
	            <?php echo $form->transfer_cost->render()?>
		    </div>
		   <?php echo $form->tld_id->render()?>
		</div>
	</div>
</form>
