<?= $this->doctype() ?>

<html>
	<head>
	    <?= $this->headTitle() ?>
	    <?= $this->headMeta() ?>
	    <?= $this->headLink() ?>
	    <?= $this->headStyle() ?>
	    <?= $this->headScript() ?>
	   
	    <?=$this->blocks()->showblock('admin_htmlhead');?>
	    
	    <meta http-equiv="x-ua-compatible" content="ie=edge" />
	    <meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
		
		<!--[if IE 8]>
			<link rel="stylesheet" href="/skins/admin/base/css/ie8.css" />
		<![endif]-->
		
	</head>