<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Addresses');?></a></li>
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Contacts');?></a></li>
			<li><a data-toggle="tab" href="#tab4"><?php echo $this->translate('Bank');?></a></li>
			<li><a data-toggle="tab" href="#tab5"><?php echo $this->translate('Servers');?></a></li>
			<li><a data-toggle="tab" href="#tab6"><?php echo $this->translate('ISP Control Panel');?></a></li>
			<li><a data-toggle="tab" href="#tab7"><?php echo $this->translate('Other');?></a></li>
		</ul>
        <div class="tab-content">
    	    <div class="tab-pane active" id="tab1"> 
    	        <div class="row">
        		    <div class="col-sm-6 col-xs-12"> 
        		        <?php echo $form->company->render() ?>
        		        <?php echo $form->vatnumber->render() ?>
        		        <?php echo $form->slogan->render() ?>
        		        <?php echo $form->logo_email->render()?>
        		        <?php if(!empty($this->srclogoemail)): ?>
        		        	<img class="thumbnail img-polaroid" style="width:200px;height:200px" src="<?php echo $this->srclogoemail ?>" alt="<?php echo $this->translate('Email logo picture')?>"/>
        		        <?php endif;?>
        		    </div>
        		    <div class="col-sm-6 col-xs-12"> 
        		        <?php echo $form->manager->render()?>
        		        <?php echo $form->website->render()?>
        		        <?php echo $form->password->render()?>
        		        <?php echo $form->logo->render()?>
        		        <?php if(!empty($this->srclogo)): ?>
        		        	<img class="thumbnail img-polaroid" style="width:200px;height:200px" src="<?php echo $this->srclogo ?>" alt="<?php echo $this->translate('Website logo picture')?>"/>
        		        <?php endif;?>
        		    </div>
    		    </div>
        	</div>
        
    	    <div class="tab-pane" id="tab2"> 
                <?php echo $form->address->render() ?>
                <?php echo $form->zip->render() ?>
                <?php echo $form->city->render() ?>
                <?php echo $form->country->render() ?>
    	    </div>    
    	    
    	    <div class="tab-pane" id="tab3"> 
                <?php echo $form->telephone->render() ?>
                <?php echo $form->fax->render() ?>
                <?php echo $form->email->render()?>
    	    </div>  
    	        
    	    <div class="tab-pane" id="tab4"> 
                <?php echo $form->bankname->render() ?>
                <?php echo $form->iban->render() ?>
                <?php echo $form->bic->render() ?>
    	    </div>    
    	    
    	    <div class="tab-pane" id="tab5"> 
    	         <?php echo  $this->simplegrid($this->serversgrid);?>
    	    </div>        
    	    
    	    <div class="tab-pane" id="tab6"> 
    	        <?php echo $form->isppanel->render()?> 
    	    </div>        
    	    
    	    <div class="tab-pane" id="tab7"> 
    	        <?php echo $form->custom1->render()?> 
    	        <?php echo $form->custom2->render()?> 
    	        <?php echo $form->custom3->render()?> 
    	    </div>       
    	     
       		<?php echo $form->isp_id->render()?>
       	</div>
     </div>
</form>
