<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Personal');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Addresses');?></a></li>
			<li><a data-toggle="tab" href="#tab4"><?php echo $this->translate('Contacts');?></a></li>
			
			<?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
				<li><a data-toggle="tab" href="#tab7"><?php echo $this->translate('Attachments');?></a></li>
			<?php endif;?>
			
			<?php if($this->editmode): ?>
				<li><a data-toggle="tab" href="#tab5"><?php echo $this->translate('Domains');?></a></li>
				<li><a data-toggle="tab" href="#tab6"><?php echo $this->translate('Services');?></a></li>
				<li><a data-toggle="tab" href="#tab8"><?php echo $this->translate('Orders');?></a></li>
				<li><a data-toggle="tab" href="#tab9"><?php echo $this->translate('Private Notes');?></a></li>
				<li><a data-toggle="tab" href="#tab10"><?php echo $this->translate('Tickets');?></a></li>
				<li><a data-toggle="tab" href="#tab11"><?php echo $this->translate('Atributes');?></a></li>
				<li><a data-toggle="tab" href="#tab12"><?php echo $this->translate('Options');?></a></li>
				<li><a data-toggle="tab" href="#tab13"><?php echo $this->translate('Invoices');?></a></li>
				<li><a data-toggle="tab" href="#tab14"><?php echo $this->translate('E-Mails');?></a></li>
			<?php endif; ?>
		</ul>
		<div class="tab-content">
		    <div class="tab-pane active" id="tab1">
			    <div class="row">
				    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
				    
				    	<div class="media">
				    		<div class="pull-left visible-lg visible-md hidden-xs">
				    			<?php if($form->email->getValue()): ?><?php echo $this->gravatar($form->email->getValue(), 64) ?><?php endif;?>
				    		</div>
				    		<div class="media-body">
					    		<div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"><?php echo $form->firstname->render() ?></div>
					        	<div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"><?php echo $form->lastname->render() ?></div>
					        </div>	
				    	</div>
				    	
			        	<?php echo $form->company->render()?>
				        <?php echo $form->email->render()?>
				        <?php echo $form->password->render()?>
				        
				    </div>
				    
				    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
				    	<?php echo $form->group_id->render()?>
			            <?php echo $form->legalform_id->render()?>
			            <?php echo $form->type_id->render()?>
			            <?php echo $form->taxpayernumber->render()?>
			            <?php echo $form->vat->render()?>
			            <?php echo $form->status_id->render()?>
				    </div>
				</div>   
			</div>   
		    
		    <div class="tab-pane" id="tab2"> 
		    	<div class="row">
		        	<div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
			            <?php echo $form->taxpayernumber->render()?>
			            <?php echo $form->birthdate->render()?>
			            <?php echo $form->birthplace->render()?>
		            </div>
		            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
			            <?php echo $form->birthdistrict->render()?>
			            <?php echo $form->birthcountry->render()?>
			            <?php echo $form->birthnationality->render()?>
			            <?php echo $form->gender->render()?>
		            </div>
		        </div>
		    </div>    
		    
		    <div class="tab-pane" id="tab3"> 
		    	<div class="row">
					<div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
					    <?php echo $form->country_id->render()?>
					    <?php echo $form->region_id->render()?>
					    
					    <?php echo $form->area->render()?>
					    <?php echo $form->city->render()?>
					    
			            <?php echo $form->address->render()?>
			            <?php echo $form->code->render()?>
		            </div>
		            
		            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
			            <?php echo $this->mapgrid($this->addressesdatagrid);?>
		            </div>
	            </div>
		    </div>
		
		   <div class="tab-pane" id="tab4">
	             <?php echo $form->contacttypes->render()?>
	             <?php echo $form->contact->render()?>
	             <?php echo $this->simplegrid($this->contactsdatagrid);?>
		   </div>
		   
		   
			<?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
			   <div class="tab-pane" id="tab7">
		            <?php echo $form->filecategory->render()?>
		            <?php echo $form->attachments->render()?><br/>
		            <?php echo $this->simplegrid($this->filesdatagrid);?>
			   </div>
			<?php endif; ?>
		    
		    <?php if($this->editmode): ?>
		    
			    <div class="tab-pane" id="tab5">
			    	<?php echo $this->simplegrid($this->domainsdatagrid);?>
			   </div>
			    
			    <div class="tab-pane" id="tab6">
		            <?php echo $this->simplegrid($this->servicesdatagrid);?>
			   </div>   
			   
			    <div class="tab-pane" id="tab8">
		            <?php echo $this->simplegrid($this->ordersdatagrid);?>
			   </div>
			   
			    <div class="tab-pane" id="tab9">
			            <?php echo $form->note->render()?>
			   </div>   
			   
			   <div class="tab-pane" id="tab10">
			       <?php echo $this->simplegrid($this->tickets);?>
			   </div>   
			   
			   <div class="tab-pane" id="tab11">
			       <?php echo $form->attributes->render();?>
			   </div>   
			   
			   <div class="tab-pane" id="tab12">
			   	   <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
				   	   <?php echo $form->language_id->render();?>
				       <?php echo $form->parent_id->render();?>
				       <?php echo $form->isreseller->render();?>
			   	   </div>
			   	   <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
				   	   <?php echo $form->issubscriber->render();?>
				       <?php echo $form->taxfree->render();?>
				       <?php echo $form->ignore_latefee->render();?>
			   	   </div>
			       
			   </div>   
			   
			   <div class="tab-pane" id="tab13">
			   		<?php echo $this->simplegrid($this->invoicesdatagrid);?>
			   </div>   
			   
			   <div class="tab-pane" id="tab14">
			   		<?php echo $this->simplegrid($this->sentmailsdatagrid);?>
			   </div>   
		   <?php endif; ?>
		   
		   <?php echo $form->customer_id->render()?>
		
		</div>
	</div>
</form>
