<?php $email = $this->email; ?>

<?php if(empty($email)): ?>
	<p><?php echo $this->translate('No email found') ?></p>
<?php else: ?>
	<div class="emailpreview">
		<div class="content">
		
			<div class="header">
				<p><?php echo $this->translate('Date') ?>: <?php echo Shineisp_Commons_Utilities::formatDateOut($email['date']) ?></p>
				<p><?php echo $this->translate('Subject') ?>: <?php echo $email['subject'] ?></p>
				<p><?php echo $this->translate('Recipient') ?>: <?php echo $email['recipient'] ?></p>
			</div>
			
			<div class="body">
				<?php echo $email['text'] ?>
			</div>
		</div>
	</div>
<?php endif; ?>
