<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
		</ul>
    
    	<div class="content_inner">
	    
		    <div class="tab-pane" id="tab1"> 
		    	<div class="row-fluid">
				    <fieldset class="span6"> 
				        <?php echo $form->firstname->render() ?>
				        <?php echo $form->lastname->render() ?>
				        <?php echo $form->email->render() ?>
				        <?php echo $form->password->render() ?>
				    </fieldset>
				    <fieldset class="span6"> 
				        <?php echo $form->role_id->render()?>
				        <?php echo $form->isp_id->render()?>
				    </fieldset>
				</div>
	    	</div>
		    
	   		<?php echo $form->user_id->render()?>
	   	</div>
   	</div>
</form>

