<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
		</ul>
    
    	<div class="tab-content">
		    <div class="tab-pane" id="tab1"> 
		    	<div class="row">
				    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
				        <?php echo $form->firstname->render() ?>
				        <?php echo $form->lastname->render() ?>
				        <?php echo $form->email->render() ?>
				        <?php echo $form->password->render() ?>
				    </div>
				    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
				        <?php echo $form->role_id->render()?>
				        <?php echo $form->isp_id->render()?>
				    </div>
				</div>
	    	</div>
		    
	   		<?php echo $form->user_id->render()?>
	   	</div>
   	</div>
</form>

