<?php $form = $this->form ?>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" id="setup">
	<div class="row" id="page_wrapper">
		<div class="col-lg-12" id="page">
			<?php echo  $this->render('partials/header.phtml') ?>		
			<div id="content">
				<div class="progress" style="display:none">Please wait a moment...</div>
				
				<?php if($this->error):?>
					 <div class="notification error"><?php echo $this->error?></div>
				<?php endif;?>
				
				<div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('Locale Settings')?></div>
                    <div class="panel-body">
    					<?php echo $form->locale->render() ?>
    					<?php echo $form->chkagreement->render() ?>
    					<?php echo $form->agreement->render() ?>
    				</div>
    			</div>
				<div class="submit"><?php echo $form->submit->render() ?></div>
				<?php echo  $this->render('partials/footer.phtml') ?>			
			</div>		
		</div>
	</div>
</form>
