<div class="navbar navbar-default navbar-fixed-bottom">
    <div class="col-lg-12 col-md-12">
		<ul class="nav navbar-nav pull-right">
		    <li><a href="http://groups.google.com/group/shineisp" target="_blank"><i class="glyphicon glyphicon-volume-down"></i> Group/Forum</a></li>
		    <li><a href="https://github.com/shinesoftware/shineisp" target="_blank"><i class="glyphicon glyphicon-align-left"></i> Source Files</a></li>
		    <li><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JK3ERUVCWMQ8C" target="_blank"><i class="glyphicon glyphicon-euro"></i> Donate</a></li>
		    <li><a href="#"><span class="badge"><?php echo 'Mem: '.(memory_get_peak_usage(true)/1024)."KB"?></span></a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="glyphicon glyphicon-question-sign"></i> Help</a>
                <ul class="dropdown-menu">
                    <li class="dropdown"><a href="http://www.shineisp.com/translating-shineisp/" target="_blank"><i class="glyphicon glyphicon-question-sign"></i> How-to translate the project</a></li>
                        <li class="divider"></li>
                    <li class="dropdown"><a href="http://www.shineisp.com/" target="_blank">About ShineISP</a></li>
                </ul>
            </li>
		</ul>
	</div>
</div>