<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	<div id="tabs">
		<ul>
			<li><a href="#tab1"><?=$this->translate('Main');?></a></li> 
			<li><a href="#tab2"><?=$this->translate('Options');?></a></li> 
		</ul>
    
	    <div id="tab1">     
            <?php echo $form->subject->render()?>
            <?php echo $form->uri->render()?>
            <?php echo $form->category_id->render()?>
            <?php echo $form->language_id->render()?>
            <?php echo $form->active->render()?>
            <?php echo $form->content->render()?>
            <p><a class="toggle button" href="#"><?php echo $this->translate('Disable/Enable Wysiwyg')?></a></p>
            
   			<?php echo $form->wiki_id->render()?>
		</div>
	    
	    <div class="tab-pane" id="tab2">
	    	<?php echo $form->metadescription->render()?>
            <?php echo $form->metakeywords->render()?>
	    </div>
   	</div>   			
</form>
</div>

