<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Options');?></a></li> 
		</ul>
        <div class="tab-content">
    	    <div class="tab-pane active" id="tab1">
    	        <div class="row-fluid">
        	        <div class="span6">
                        <?php echo $form->subject->render()?>
                        <?php echo $form->uri->render()?>
                        <?php echo $form->category_id->render()?>    	        
        	        </div>     
        	        <div class="span6">
        	            <?php echo $form->language_id->render()?>
                        <?php echo $form->active->render()?>
        	        </div>     
    	        </div>
                <?php echo $form->content->render()?>
       			<?php echo $form->wiki_id->render()?>
    		</div>
    	    
    	    <div class="tab-pane" id="tab2">
    	    	<?php echo $form->metadescription->render()?>
                <?php echo $form->metakeywords->render()?>
    	    </div>
	    </div>
   	</div>   			
</form>

