<?php $attributes = $this->attributes ?>
<?php $products = $this->products ?>
<?php $values = $this->values ?>
<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">
	    <div class="page-header">
			<h4><?php echo $this->translate('Compare %s', $this->title) ?></h4>
			<p><?php echo $this->translate('Here you can compare all the %s product. The price shown is the lower price available.', $this->title) ?></p>
		</div>
		<div class="row">
			<?php if(!empty($attributes) && !empty($products)): ?>
				<?php foreach ($products as $product): ?>
					<div class="col-lg-3">
						 <div class="panel panel-info">
						     <div class="panel-heading"><h3 class="text-center"><?php echo !empty($product['ProductsData']['0']['nickname']) ? $product['ProductsData']['0']['nickname'] : "-"?></h3></div>
						         <div class="panel-body text-center">
									<p class="lead" style="font-size:30px"><strong><?php echo $this->prices()->getAllPricesInfo($product['product_id'], false, false, true)?></strong></p>
									<small><?php echo $product['ProductsAttributesGroups']['name']?></small>
								</div>
								<ul class="list-group list-group-flush text-center">
									<?php foreach ($attributes as $attribute): ?>
										<?php if($attribute['is_visible_on_front'] && $attribute['on_product_listing']): ?>
											<?php foreach ($values as $attrvalue): ?>
												<?php if(($attrvalue['attribute_id'] == $attribute['attribute_id']) && ($attrvalue['product_id'] == $product['product_id'])): ?>
													 <?php if($attrvalue['value'] =="-1"): ?>
											         	<li class="list-group-item" title="<?php echo $attribute['ProductsAttributesData'][0]['description'] ?>"><strong><?php echo $this->translate('Unlimited')?></strong> <?php echo $attribute['ProductsAttributesData'][0]['label'] ?></li>
											         <?php else:?>
											        	<li class="list-group-item" title="<?php echo $attribute['ProductsAttributesData'][0]['description'] ?>"><strong><?php echo $attrvalue['value'] ?></strong> <?php echo $attribute['ProductsAttributesData'][0]['label'] ?></li>
											         <?php endif;?>
													<?php break;?>
												<?php endif;?>
											<?php endforeach; ?>
										<?php endif; ?>
									<?php endforeach;?>
							</ul>
							<div class="panel-footer">
								<a class="btn btn-lg btn-block btn-danger" href="/<?php echo $product['uri'] ?>.html"><?php echo $this->translate('Buy Now')?></a>
							</div>
						</div>
					</div>
				<?php endforeach;?>	
			<?php endif; ?>
		</div>
	</div>
</div>