<?php $tld = $this->tld; ?>
<?php $taxes = Taxes::getTaxbyTldID($tld['tld_id'])?>

<div class="row">
	<div class="large-12 column">
	
		<h4><?php echo $this->translate('Domain') . " ." . $tld['DomainsTldsData'][0]['name'] ?></h4>	
		<p><b><?php echo $this->translate('Tags') ?></b>: <?php echo $tld['DomainsTldsData'][0]['tags'] ?></p>	
		
		<?php echo $tld['DomainsTldsData'][0]['description'] ?>
		
		<table>
			<tr>
				<td><?php echo $this->translate('Registration price') ?></td>
				<td><?php echo $this->currency($tld['registration_price'] * ($taxes['percentage'] + 100) / 100, array('currency' => Settings::findbyParam('currency'))) ?> (<?php echo $this->translate('VAT included') ?>)</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Transfer price') ?></td>
				<td><?php echo $this->currency($tld['transfer_price'] * ($taxes['percentage'] + 100) / 100, array('currency' => Settings::findbyParam('currency'))) ?> (<?php echo $this->translate('VAT included') ?>)</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Renewal price')?></td>
				<td>
					<?php echo $this->currency($tld['renewal_price'] * ($taxes['percentage'] + 100) / 100, array('currency' => Settings::findbyParam('currency'))) ?> (<?php echo $this->translate('VAT included') ?>)
				</td>
			</tr>
		</table>
		
		<h5><?php echo $this->translate('Domain Checker') ?></h5>
		<div class="row">
		    <form method="<?php echo $this->form->getMethod() ?>" class="dropdown custom" id="domainbox" action="<?php echo $this->form->getAction()?>">
				<div class="small-8 column"><?php echo $this->form->name->setDecorators(array('Simple'));?></div>
				<div class="small-2 column"><?php echo $this->form->tld->setDecorators(array('Simple'));?></div>
				<div class="small-2 column"><?php echo $this->form->check->setDecorators(array('Simple'));?></div>
		    </form>
		</div>
		
		<h5><?php echo $this->translate('Other extensions') ?></h5>
		<ul class="inline-list">
		<?php foreach ($this->tldslist as $id=>$tld):?>
			<li><a title="<?php echo $this->translate('Register your new .%s domain', $tld) ?>" href="/tlds/<?php echo $tld?>.html">.<?php echo $tld; ?></a></li>
		<?php endforeach;?>
		</ul>
	</div>
</div>