<?php $form = $this->form; ?>

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"notification error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>
<h2><?php echo $this->translate('Looking for a domain name?')?></h2>
<small><?php echo $this->translate('Choose your new domain name!')?></small>
<div id="domainchecker2" title="<?php echo $this->translate('Choose your new domain name!')?>">
    <div class="checkerform">
	    <form method="<?php echo $this->form->getMethod() ?>" id="domainbox" action="<?php echo $this->form->getAction()?>">
			<?php echo $this->form->name->setDecorators(array('Simple'));?>
			<?php echo $this->form->tld->setDecorators(array('Simple'));?>
			<?php echo $this->form->check->setDecorators(array('Simple'));?>
	    </form>
    </div>
</div>
