<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
        <ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Other');?></a></li> 
		</ul>
		<div class="tab-content">
		    <div class="tab-pane active" id="tab1"> 
		    	<div class="row-fluid">
			    	<div class="span6">
		    		     <?php echo $form->product_id->render()?> 
	            		<?php echo $form->publishedat->render()?> 
	            		<?php echo $form->nick->render()?> 
	            		<?php echo $form->subject->render()?>
	            	</div>
	            	<div class="span6">
			            <?php echo $form->referer->render()?>
			            <?php echo $form->email->render()?>
			            <?php echo $form->stars->render()?>
			            <?php echo $form->active->render()?>
			        </div>
	            </div>
	            <?php echo $form->review->render()?>
		    </div>
		    
		    <div class="tab-pane" id="tab2">
		    	<div class="row-fluid">
			    	<div class="span6">
				    	<?php echo $form->city->render()?>
			            <?php echo $form->ip->render()?>
			            <?php echo $form->latitude->render()?>
			            <?php echo $form->longitude->render()?>
			        </div>
		            <div class="span6">
		            	<?php if(Null != $form->latitude->getValue()): ?>
		            	<?php $pos = $form->latitude->getValue() . "," . $form->longitude->getValue()?>
			            	<a target="_blank" href="http://maps.google.com/maps?saddr=<?php echo $pos ?>&markers=<?php echo $pos ?>"><img class="img-polaroid" src="http://maps.googleapis.com/maps/api/staticmap?center=<?php echo $pos ?>&markers=color:blue%7C&zoom=8&maptype=roadmap&size=400x200&sensor=false" /></a>
			            	<br/><small><?php echo $this->translate('The location shown in the map is approximate.')?></small>
		            	<?php endif; ?>
		            </div>
		    	</div>
		    </div>
		</div>  
	</div>  
   <?php echo $form->review_id->render()?>
</form>
</div>