<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('tickets', 'date_open', 'timestamp', '25', array(
             'notnull' => 'true;',
             ));
        $this->changeColumn('tickets', 'date_updated', 'timestamp', '25', array(
             ));
        $this->changeColumn('tickets', 'date_close', 'timestamp', '25', array(
             ));
    }

    public function down()
    {

    }
}