<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('products_upgrades', 'products_upgrades_upgrade_product_id_products_product_id', array(
             'name' => 'products_upgrades_upgrade_product_id_products_product_id',
             'local' => 'upgrade_product_id',
             'foreign' => 'product_id',
             'foreignTable' => 'products',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('products_upgrades', 'products_upgrades_upgrade_product_id', array(
             'fields' => 
             array(
              0 => 'upgrade_product_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('products_upgrades', 'products_upgrades_upgrade_product_id_products_product_id');
        $this->removeIndex('products_upgrades', 'products_upgrades_upgrade_product_id', array(
             'fields' => 
             array(
              0 => 'upgrade_product_id',
             ),
             ));
    }
}