<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin_user', 'last_password_change', 'int', '10', array(
             'notnull' => '1',
             'fixed' => '0',
             ));
        $this->addColumn('admin_user', 'force_password_change', 'tinyint', '1', array(
             'notnull' => '1',
             'fixed' => '0',
             ));
        $this->addColumn('customers', 'last_password_change', 'int', '10', array(
             'notnull' => '1',
             'fixed' => '0',
             ));
        $this->addColumn('customers', 'force_password_change', 'tinyint', '1', array(
             'notnull' => '1',
             'fixed' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('admin_user', 'last_password_change');
        $this->removeColumn('admin_user', 'force_password_change');
        $this->removeColumn('customers', 'last_password_change');
        $this->removeColumn('customers', 'force_password_change');
    }
}