<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('products', 'products_group_id_products_attributes_groups_group_id');
        $this->createForeignKey('products', 'products_group_id_products_attributes_groups_group_id_1', array(
             'name' => 'products_group_id_products_attributes_groups_group_id_1',
             'local' => 'group_id',
             'foreign' => 'group_id',
             'foreignTable' => 'products_attributes_groups',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('products', 'products_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('products', 'products_group_id_products_attributes_groups_group_id', array(
             'name' => 'products_group_id_products_attributes_groups_group_id',
             'local' => 'group_id',
             'foreign' => 'group_id',
             'foreignTable' => 'products_attributes_groups',
             ));
        $this->dropForeignKey('products', 'products_group_id_products_attributes_groups_group_id_1');
        $this->removeIndex('products', 'products_group_id', array(
             'fields' => 
             array(
              0 => 'group_id',
             ),
             ));
    }
}