<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('products_attributes_indexes', 'products_attributes_indexes_product_id_products_product_id');
        $this->createForeignKey('products_attributes_indexes', 'products_attributes_indexes_product_id_products_product_id_1', array(
             'name' => 'products_attributes_indexes_product_id_products_product_id_1',
             'local' => 'product_id',
             'foreign' => 'product_id',
             'foreignTable' => 'products',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('products_attributes_indexes', 'products_attributes_indexes_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('products_attributes_indexes', 'products_attributes_indexes_product_id_products_product_id', array(
             'name' => 'products_attributes_indexes_product_id_products_product_id',
             'local' => 'product_id',
             'foreign' => 'product_id',
             'foreignTable' => 'products',
             ));
        $this->dropForeignKey('products_attributes_indexes', 'products_attributes_indexes_product_id_products_product_id_1');
        $this->removeIndex('products_attributes_indexes', 'products_attributes_indexes_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}