<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('products', 'downgradable', 'integer', '1', array(
             'default' => '1',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('products', 'downgradable');
    }
}