<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('admin_user', 'last_password_change', 'timestamp', '25', array(
             'notnull' => '',
             ));
        $this->changeColumn('customers', 'last_password_change', 'timestamp', '25', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}