<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        /* $this->changeColumn('orders_items', 'parent_detail_id', 'integer', '4', array(
             )); */
    }

    public function down()
    {

    }
}