<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version36 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('domains_tlds', 'isrefundable', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('products', 'isrefundable', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('domains_tlds', 'isrefundable');
        $this->removeColumn('products', 'isrefundable');
    }
}