<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('products_tranches_includes', array(
             'tranche_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '',
              'primary' => '1',
              'autoincrement' => '',
              'length' => '4',
             ),
             'include_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '',
              'primary' => '1',
              'autoincrement' => '',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'tranche_id',
              1 => 'include_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('products_tranches_includes');
    }
}