<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
    public function up()
    {
    	try {
	        $this->changeColumn('payments', 'income', 'float', '10', array(
	             'fixed' => '0',
	             'unsigned' => '',
	             'primary' => '',
	             'notnull' => '',
	             'default' => '0',
	             'autoincrement' => '',
	             ));
	        $this->changeColumn('payments', 'outcome', 'float', '10', array(
	             'fixed' => '0',
	             'unsigned' => '',
	             'primary' => '',
	             'notnull' => '',
	             'default' => '0',
	             'autoincrement' => '',
	             ));
	        $this->changeColumn('payments_resources', 'beginning_balance', 'float', '10', array(
	             'fixed' => '0',
	             'unsigned' => '',
	             'primary' => '',
	             'notnull' => '',
	             'default' => '0',
	             'autoincrement' => '',
	             ));
		} catch ( Exception $e ) {
			
		}
    }

    public function down()
    {

    }
}