<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version38 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('orders_items_servers', 'orders_items_servers_server_id_servers_server_id', array(
             'name' => 'orders_items_servers_server_id_servers_server_id',
             'local' => 'server_id',
             'foreign' => 'server_id',
             'foreignTable' => 'servers',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('orders_items_servers', 'orders_items_servers_order_id_orders_order_id', array(
             'name' => 'orders_items_servers_order_id_orders_order_id',
             'local' => 'order_id',
             'foreign' => 'order_id',
             'foreignTable' => 'orders',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('orders_items_servers', 'orders_items_servers_orderitem_id_orders_items_detail_id', array(
             'name' => 'orders_items_servers_orderitem_id_orders_items_detail_id',
             'local' => 'orderitem_id',
             'foreign' => 'detail_id',
             'foreignTable' => 'orders_items',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('orders_items_servers', 'orders_items_servers_server_id', array(
             'fields' => 
             array(
              0 => 'server_id',
             ),
             ));
        $this->addIndex('orders_items_servers', 'orders_items_servers_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
        $this->addIndex('orders_items_servers', 'orders_items_servers_orderitem_id', array(
             'fields' => 
             array(
              0 => 'orderitem_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('orders_items_servers', 'orders_items_servers_server_id_servers_server_id');
        $this->dropForeignKey('orders_items_servers', 'orders_items_servers_order_id_orders_order_id');
        $this->dropForeignKey('orders_items_servers', 'orders_items_servers_orderitem_id_orders_items_detail_id');
        $this->removeIndex('orders_items_servers', 'orders_items_servers_server_id', array(
             'fields' => 
             array(
              0 => 'server_id',
             ),
             ));
        $this->removeIndex('orders_items_servers', 'orders_items_servers_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
        $this->removeIndex('orders_items_servers', 'orders_items_servers_orderitem_id', array(
             'fields' => 
             array(
              0 => 'orderitem_id',
             ),
             ));
    }
}