<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('products_tranches_includes', 'products_tranches_includes_include_id_products_product_id', array(
             'name' => 'products_tranches_includes_include_id_products_product_id',
             'local' => 'include_id',
             'foreign' => 'product_id',
             'foreignTable' => 'products',
             'onUpdate' => '',
             'onDelete' => 'NO ACTION',
             ));
        $this->createForeignKey('products_tranches_includes', 'ptpt_1', array(
             'name' => 'ptpt_1',
             'local' => 'tranche_id',
             'foreign' => 'tranche_id',
             'foreignTable' => 'products_tranches',
             'onUpdate' => '',
             'onDelete' => 'NO ACTION',
             ));
        $this->addIndex('products_tranches_includes', 'products_tranches_includes_include_id', array(
             'fields' => 
             array(
              0 => 'include_id',
             ),
             ));
        $this->addIndex('products_tranches_includes', 'products_tranches_includes_tranche_id', array(
             'fields' => 
             array(
              0 => 'tranche_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('products_tranches_includes', 'products_tranches_includes_include_id_products_product_id');
        $this->dropForeignKey('products_tranches_includes', 'ptpt_1');
        $this->removeIndex('products_tranches_includes', 'products_tranches_includes_include_id', array(
             'fields' => 
             array(
              0 => 'include_id',
             ),
             ));
        $this->removeIndex('products_tranches_includes', 'products_tranches_includes_tranche_id', array(
             'fields' => 
             array(
              0 => 'tranche_id',
             ),
             ));
    }
}