<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version60 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('emails_templates', array(
             'template_id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '5',
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'products',
              1 => 'domains',
              2 => 'supports',
              3 => 'general',
              4 => 'invoices',
              5 => 'affiliates',
              6 => 'customers',
              7 => 'orders',
              ),
              'length' => '',
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'fromname' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'fromemail' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'cc' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'bcc' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'plaintext' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'default' => '1',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'template_id',
             ),
             'charset' => 'UTF8',
             ));
        $this->createTable('emails_templates_data', array(
             'id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '5',
             ),
             'template_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'length' => '5',
             ),
             'language_id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '',
              'length' => '4',
             ),
             'fromname' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'fromemail' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'subject' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'html' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '',
             ),
             'text' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->createTable('emails_templates_sends', array(
             'id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '5',
             ),
             'customer_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '',
              'length' => '4',
             ),
             'fromname' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'subject' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'recipient' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'cc' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'bcc' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'html' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'text' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('emails_templates');
        $this->dropTable('emails_templates_data');
        $this->dropTable('emails_templates_sends');
    }
}