<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version55 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('products', 'products_server_group_id_servers_groups_group_id', array(
             'name' => 'products_server_group_id_servers_groups_group_id',
             'local' => 'server_group_id',
             'foreign' => 'group_id',
             'foreignTable' => 'servers_groups',
             ));
        $this->addIndex('products', 'products_server_group_id', array(
             'fields' => 
             array(
              0 => 'server_group_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('products', 'products_server_group_id_servers_groups_group_id');
        $this->removeIndex('products', 'products_server_group_id', array(
             'fields' => 
             array(
              0 => 'server_group_id',
             ),
             ));
    }
}