<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version57 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('servers', 'is_default', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('servers', 'buy_date', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('servers', 'is_default');
        $this->removeColumn('servers', 'buy_date');
    }
}