<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('servers', 'accounts');
        $this->removeColumn('servers', 'max_accounts');
        $this->addColumn('servers', 'services', 'integer', '4', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->addColumn('servers', 'max_services', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->addColumn('servers', 'accounts', 'integer', '4', array(
             'default' => '0',
             'notnull' => '1',
             ));
        $this->addColumn('servers', 'max_accounts', 'integer', '4', array(
             ));
        $this->removeColumn('servers', 'services');
        $this->removeColumn('servers', 'max_services');
    }
}