<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version52 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('products', 'autosetup', 'integer', '4', array(
             'unsigned' => '1',
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('products', 'autosetup');
    }
}