<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version52 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('servers_groups_indexes', 'servers_groups_indexes_server_id_servers_server_id', array(
             'name' => 'servers_groups_indexes_server_id_servers_server_id',
             'local' => 'server_id',
             'foreign' => 'server_id',
             'foreignTable' => 'servers',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('servers_groups_indexes', 'servers_groups_indexes_server_id', array(
             'fields' => 
             array(
              0 => 'server_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('servers_groups_indexes', 'servers_groups_indexes_server_id_servers_server_id');
        $this->removeIndex('servers_groups_indexes', 'servers_groups_indexes_server_id', array(
             'fields' => 
             array(
              0 => 'server_id',
             ),
             ));
    }
}