<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version49 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('servers', 'accounts', 'integer', '4', array(
             'default' => '0',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('servers', 'accounts');
    }
}