<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version58 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('custom_attributes', 'panel_id', 'integer', '4', array(
             ));
			 
		$this->createForeignKey('custom_attributes', 'custom_attributes_panel_id_panels_panel_id', array(
             'name' => 'custom_attributes_panel_id_panels_panel_id',
             'local' => 'panel_id',
             'foreign' => 'panel_id',
             'foreignTable' => 'panels',
             ));			 
    }

    public function down()
    {
		$this->dropForeignKey('custom_attributes', 'custom_attributes_panel_id_panels_panel_id');
    }
}