<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version48 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('servers', 'datacenter', 'string', '200', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('servers', 'datacenter');
    }
}