<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version65 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('products', 'welcome_mail_id', 'integer', '5', array(
             'unsigned' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('products', 'welcome_mail_id');
    }
}