<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version74 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('domains_tasks', 'domains_tasks_registrars_id_registrars_registrars_id');
        $this->dropForeignKey('domains_tlds', 'domains_tlds_registrars_id_registrars_registrars_id');
        $this->createForeignKey('domains_tasks', 'domains_tasks_registrars_id_registrars_registrars_id_1', array(
             'name' => 'domains_tasks_registrars_id_registrars_registrars_id_1',
             'local' => 'registrars_id',
             'foreign' => 'registrars_id',
             'foreignTable' => 'registrars',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('domains_tlds', 'domains_tlds_registrars_id_registrars_registrars_id_1', array(
             'name' => 'domains_tlds_registrars_id_registrars_registrars_id_1',
             'local' => 'registrars_id',
             'foreign' => 'registrars_id',
             'foreignTable' => 'registrars',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('domains_tasks', 'domains_tasks_registrars_id', array(
             'fields' => 
             array(
              0 => 'registrars_id',
             ),
             ));
        $this->addIndex('domains_tlds', 'domains_tlds_registrars_id', array(
             'fields' => 
             array(
              0 => 'registrars_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('domains_tasks', 'domains_tasks_registrars_id_registrars_registrars_id', array(
             'name' => 'domains_tasks_registrars_id_registrars_registrars_id',
             'local' => 'registrars_id',
             'foreign' => 'registrars_id',
             'foreignTable' => 'registrars',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('domains_tlds', 'domains_tlds_registrars_id_registrars_registrars_id', array(
             'name' => 'domains_tlds_registrars_id_registrars_registrars_id',
             'local' => 'registrars_id',
             'foreign' => 'registrars_id',
             'foreignTable' => 'registrars',
             ));
        $this->dropForeignKey('domains_tasks', 'domains_tasks_registrars_id_registrars_registrars_id_1');
        $this->dropForeignKey('domains_tlds', 'domains_tlds_registrars_id_registrars_registrars_id_1');
        $this->removeIndex('domains_tasks', 'domains_tasks_registrars_id', array(
             'fields' => 
             array(
              0 => 'registrars_id',
             ),
             ));
        $this->removeIndex('domains_tlds', 'domains_tlds_registrars_id', array(
             'fields' => 
             array(
              0 => 'registrars_id',
             ),
             ));
    }
}