<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version85 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('addresses', 'addresses_region_id_regions_region_id', array(
             'name' => 'addresses_region_id_regions_region_id',
             'local' => 'region_id',
             'foreign' => 'region_id',
             'foreignTable' => 'regions',
             ));
        $this->addIndex('addresses', 'addresses_region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('addresses', 'addresses_region_id_regions_region_id');
        $this->removeIndex('addresses', 'addresses_region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
    }
}