<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version77 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('customers', 'resetpwd_key', 'string', '50', array(
             ));
        $this->addColumn('customers', 'resetpwd_expire', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('customers', 'resetpwd_key');
        $this->removeColumn('customers', 'resetpwd_expire');
    }
}