<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version81 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('provinces', 'provinces_country_id_countries_country_id', array(
             'name' => 'provinces_country_id_countries_country_id',
             'local' => 'country_id',
             'foreign' => 'country_id',
             'foreignTable' => 'countries',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('provinces', 'provinces_region_id_states_region_id', array(
             'name' => 'provinces_region_id_states_region_id',
             'local' => 'region_id',
             'foreign' => 'region_id',
             'foreignTable' => 'states',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('states', 'states_country_id_countries_country_id', array(
             'name' => 'states_country_id_countries_country_id',
             'local' => 'country_id',
             'foreign' => 'country_id',
             'foreignTable' => 'countries',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('provinces', 'provinces_country_id', array(
             'fields' => 
             array(
              0 => 'country_id',
             ),
             ));
        $this->addIndex('provinces', 'provinces_region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->addIndex('states', 'states_country_id', array(
             'fields' => 
             array(
              0 => 'country_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('provinces', 'provinces_country_id_countries_country_id');
        $this->dropForeignKey('provinces', 'provinces_region_id_states_region_id');
        $this->dropForeignKey('states', 'states_country_id_countries_country_id');
        $this->removeIndex('provinces', 'provinces_country_id', array(
             'fields' => 
             array(
              0 => 'country_id',
             ),
             ));
        $this->removeIndex('provinces', 'provinces_region_id', array(
             'fields' => 
             array(
              0 => 'region_id',
             ),
             ));
        $this->removeIndex('states', 'states_country_id', array(
             'fields' => 
             array(
              0 => 'country_id',
             ),
             ));
    }
}