<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version98 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('status_history', 'status_history_status_id_statuses_status_id', array(
             'name' => 'status_history_status_id_statuses_status_id',
             'local' => 'status_id',
             'foreign' => 'status_id',
             'foreignTable' => 'statuses',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('status_history', 'status_history_status_id', array(
             'fields' => 
             array(
              0 => 'status_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('status_history', 'status_history_status_id_statuses_status_id');
        $this->removeIndex('status_history', 'status_history_status_id', array(
             'fields' => 
             array(
              0 => 'status_id',
             ),
             ));
    }
}