<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version92 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('orders', 'order_number', array(
             'fields' => 
             array(
              0 => 'order_number',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('orders', 'order_number', array(
             'fields' => 
             array(
              0 => 'order_number',
             ),
             ));
    }
}