<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version95 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('oauth_clients', 'customer_id');
        $this->addColumn('oauth_clients', 'admin_id', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->addColumn('oauth_clients', 'active', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->addColumn('products', 'isp_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->addColumn('oauth_clients', 'customer_id', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->removeColumn('oauth_clients', 'admin_id');
        $this->removeColumn('oauth_clients', 'active');
        $this->removeColumn('products', 'isp_id');
    }
}