<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version100 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('customers_groups', 'customers_groups_isp_id_isp_isp_id', array(
             'name' => 'customers_groups_isp_id_isp_isp_id',
             'local' => 'isp_id',
             'foreign' => 'isp_id',
             'foreignTable' => 'isp',
             ));
        $this->addIndex('customers_groups', 'customers_groups_isp_id', array(
             'fields' => 
             array(
              0 => 'isp_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('customers_groups', 'customers_groups_isp_id_isp_isp_id');
        $this->removeIndex('customers_groups', 'customers_groups_isp_id', array(
             'fields' => 
             array(
              0 => 'isp_id',
             ),
             ));
    }
}