<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version101 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('oauth_jwt', array(
             'id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'client_id' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'subject' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'public_key' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->addColumn('products_attributes_groups', 'isp_id', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->addColumn('products_categories', 'isp_id', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->addColumn('registrars', 'isp_id', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->addColumn('taxes', 'isp_id', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->addColumn('tickets_categories', 'isp_id', 'integer', '4', array(
             'notnull' => '1',
             ));
        $this->addColumn('wiki', 'isp_id', 'integer', '4', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('oauth_jwt');
        $this->removeColumn('products_attributes_groups', 'isp_id');
        $this->removeColumn('products_categories', 'isp_id');
        $this->removeColumn('registrars', 'isp_id');
        $this->removeColumn('taxes', 'isp_id');
        $this->removeColumn('tickets_categories', 'isp_id');
        $this->removeColumn('wiki', 'isp_id');
    }
}