<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version90 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('oauth_clients', 'redirect_url');
        $this->addColumn('oauth_clients', 'redirect_uri', 'string', '500', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->addColumn('oauth_clients', 'redirect_url', 'string', '500', array(
             'notnull' => '',
             ));
        $this->removeColumn('oauth_clients', 'redirect_uri');
    }
}