<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version87 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('oauth_access_tokens', array(
             'id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'access_token' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'client_id' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'expires' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
             ),
             'scope' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->createTable('oauth_authorization_codes', array(
             'id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'authorization_code' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'client_id' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'redirect_url' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '500',
             ),
             'expires' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
             ),
             'scope' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->createTable('oauth_clients', array(
             'id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'client_id' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'secret' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'redirect_url' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '500',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->createTable('oauth_refresh_tokens', array(
             'id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'refresh_token' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'client_id' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'expires' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
             ),
             'scope' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '250',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->addColumn('orders', 'uuid', 'string', '50', array(
             ));
    }

    public function down()
    {
        $this->dropTable('oauth_access_tokens');
        $this->dropTable('oauth_authorization_codes');
        $this->dropTable('oauth_clients');
        $this->dropTable('oauth_refresh_tokens');
        $this->removeColumn('orders', 'uuid');
    }
}