<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version110 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tickets', 'tickets_order_id_orders_order_id', array(
             'name' => 'tickets_order_id_orders_order_id',
             'local' => 'order_id',
             'foreign' => 'order_id',
             'foreignTable' => 'orders',
             ));
        $this->addIndex('tickets', 'tickets_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tickets', 'tickets_order_id_orders_order_id');
        $this->removeIndex('tickets', 'tickets_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }
}