<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version117 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('isp', 'custom1', 'string', '200', array(
             'notnull' => '',
             ));
        $this->addColumn('isp', 'custom2', 'string', '200', array(
             'notnull' => '',
             ));
        $this->addColumn('isp', 'custom3', 'string', '200', array(
             'notnull' => '',
             ));
        $this->changeColumn('isp', 'manager', 'string', '200', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('isp', 'custom1');
        $this->removeColumn('isp', 'custom2');
        $this->removeColumn('isp', 'custom3');
    }
}