<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version120 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('orders_items', 'vat', 'float', '10', array(
             ));
        $this->changeColumn('orders_items', 'percentage', 'float', '10', array(
             ));
    }

    public function down()
    {

    }
}