<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version123 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('customers', 'sex');
        $this->addColumn('customers', 'gender', 'string', '1', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->addColumn('customers', 'sex', 'string', '1', array(
             'notnull' => '',
             ));
        $this->removeColumn('customers', 'gender');
    }
}