<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version130 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('status_history', 'order_id', 'integer', '4', array(
             ));
        $this->addColumn('status_history', 'ticket_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('status_history', 'order_id');
        $this->removeColumn('status_history', 'ticket_id');
    }
}