<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version136 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('domains_profiles', 'country');
        $this->addColumn('domains_profiles', 'country_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->addColumn('domains_profiles', 'country', 'string', '50', array(
             'notnull' => '',
             ));
        $this->removeColumn('domains_profiles', 'country_id');
    }
}