<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version134 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('customers_domains_registrars', 'profile_id', 'integer', '4', array(
             ));
        $this->addColumn('customers_domains_registrars', 'type', 'string', '20', array(
             'notnull' => '',
             'default' => 'owner',
             ));
    }

    public function down()
    {
        $this->removeColumn('customers_domains_registrars', 'profile_id');
        $this->removeColumn('customers_domains_registrars', 'type');
    }
}