<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version135 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('customers_domains_registrars', 'cpdp', array(
             'name' => 'cpdp',
             'local' => 'profile_id',
             'foreign' => 'profile_id',
             'foreignTable' => 'domains_profiles',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('customers_domains_registrars', 'customers_domains_registrars_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('customers_domains_registrars', 'cpdp');
        $this->removeIndex('customers_domains_registrars', 'customers_domains_registrars_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
    }
}