<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version138 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('domains_tasks', 'domain');
    }

    public function down()
    {
        $this->addColumn('domains_tasks', 'domain', 'string', '', array(
             'notnull' => '1',
             ));
    }
}