<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Notes');?></a></li> 
		</ul>
		
        <div class="tab-content">
        
    	    <div class="tab-pane active" id="tab1"> 
    	        <?php echo $form->invoice_date->render() ?>
    	        <?php echo $form->number->render() ?>
    	        <?php echo $form->formatted_number->render() ?>
    	        <?php echo $form->order_id->render() ?>
    	        <?php echo $form->customer_parent_id->render() ?>
    	    </div>
    	    
    	    <div class="tab-pane" id="tab2"> 
    	        <?php echo $form->note->render() ?>
        	</div>
    	   <?php echo $form->invoice_id->render()?>
    	</div>
	</div>
</form>

