<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div id="tabs">
		<ul>
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Notes');?></a></li> 
		</ul>
    
	    <div id="tab1"> 
	        <?php echo $form->invoice_date->render() ?>
	        <?php echo $form->number->render() ?>
	        <?php echo $form->formatted_number->render() ?>
	        <?php echo $form->order_id->render() ?>
	        <?php echo $form->customer_parent_id->render() ?>
	    </div>
	    <div id="tab2"> 
	        <?php echo $form->note->render() ?>
    	</div>
	   <?php echo $form->invoice_id->render()?>
	</div>
</form>

</div>