
<?php if(!empty($this->files)): ?>
	<h4><i class="fa fa-file-text-o"></i> <?php echo $this->translate('Your Files')?></h4>
	<ul class="list-inline">
	<?php foreach($this->files as $file): ?>
		<?php if(file_exists(PUBLIC_PATH . $file['path'] . $file['file'])): ?>
			<li><a target="_blank" href="/index/getfiles/key/<?php echo $file['publickey']?>"><?php echo basename($file['file'])?></a></li>
		<?php else:?>
			<li><?php echo basename($file['file'])?> - <?php echo $this->translate('File not found')?></li>
		<?php endif;?>
	<?php endforeach;?>
	</ul>
<?php endif; ?>	
