<?php $attributes = $this->attributes; ?>
<?php if(!empty($attributes)): ?>
	<h5><?php echo $this->translate('Features') ?></h5>
	<table class="table table-striped table-hover table-condensed">
		<?php foreach ($attributes as $attribute): ?>
			<?php if($attribute['is_visible_on_front']): ?>
		    <tr title="<?php echo $attribute['description'] ?>">
		        <td width=""><?php echo $attribute['label'] ?></td>
		        <td>
		        <?php echo $attribute['prefix'] ?> 
		         <?php if($attribute['value'] =="-1"): ?>
		         	<?php echo $this->translate('Unlimited')?>
		         <?php else:?>
		        	<?php echo $attribute['value'] ?>
		         <?php endif;?>
		         <?php echo $attribute['suffix'] ?></td>
		    </tr>
		    <?php endif; ?>
		<?php endforeach;?>
	</table>
<?php endif;?>