<div class="row">
	<div class="col-lg-12">
	    <form method="<?php echo $this->form->getMethod() ?>" id="domainbox" class="form-group" action="<?php echo $this->form->getAction()?>">
			<div class="col-lg-8"><?php echo $this->form->name->setDecorators(array('ViewHelper'));?></div>
			<div class="col-lg-2"><?php echo $this->form->tld->setDecorators(array('ViewHelper'));?></div>
			<div class="col-lg-2"><?php echo $this->form->check->setDecorators(array('ViewHelper'));?></div>
	    </form>
    </div>
    <div class="row">
	    <div class="col-lg-12">
	    	<p align="center"><a href="/common/bulkdomains"><?php echo $this->translate('Registering more than one domain name? Click here!')?></a></p>
	    </div>
    </div>
    <div class="row">
	    <div id="result" class="col-lg-12" style="display: none">
		   	<div class="col-lg-8">
		    	<div class="domain"></div>
		    	<div class="message"></div>
		    	<div class="price"></div>
		    </div>
		    <div class="col-lg-4 ordernowbtn">
		   		<a href="#" class="btn btn-default ordernow" ><?php echo $this->translate('Order Now')?></a>
		   	</div>
	   </div>
    </div>
    
    
</div>
