<div class="newdomain highlight">
    <form method="<?php echo $this->form->getMethod() ?>" id="domainbox" action="<?php echo $this->form->getAction()?>">
		<?php echo $this->form->name->setDecorators(array('Simple'));?>
		<?php echo $this->form->tld->setDecorators(array('Simple'));?>
		<?php echo $this->form->check->setDecorators(array('Simple'));?>
    </form>
    <div id="result" style="display: none">
    	<a href="#" class="button ordernow" ><?php echo $this->translate('Order Now')?></a>
    	<div class="domain"></div>
    	<div class="message"></div>
    	<div class="price"></div>
    </div>
    
    <div class="bulklink">
    	<a href="/domains/bulkdomains">
    		<?php echo $this->translate('Registering more than one domain name? Click here!')?>
    	</a>
    </div>
</div>