<?php $data = $this->data; ?>

<?php if(!empty($data) && is_array($data)):?>

    <h1><?php echo $data['title']?></h1>
    <?php if(isset($data['subitems']) && count($data['subitems']) > 0):?>
        <ul class="list-inline" id="subnav">
            <?php foreach($data['subitems'] as $item): ?>
                <li><a class="subnav1" href="/cms/page/url/<?php echo $item['link']?>"><?php echo $item['label']?></a></li> 
            <?php endforeach;?>
        </ul>
    <?php endif; ?>
        
<?php endif;?>