<?php if($this->expdomains) :?>
	<table class="summary">
	    <thead>
	        <tr class="summary_title">
	            <td><?php echo $this->translate('Domains') ?></td>
	            <td><?php echo $this->translate('Expiry Date') ?></td>
	            <td><?php echo $this->translate('Remaining Days') ?></td>
	        </tr>
	    </thead>
	    <tbody>
	        <?php foreach ($this->expdomains as $domain) : ?>
	        <tr>
	            <td><a href="/domains/edit/id/<?php echo $domain['domain_id']?>"><?php echo $domain['domain'] ?></a></td>
	            <td><?php echo $domain['expiring_date'] ?></td>  
	            <td><?php echo $domain['daysleft'] ?></td>  
	        </tr>
	        <?php endforeach; ?>
	    </tbody>
	</table>
<?php endif;?>