<?php if (isset($this->searchactive) && $this->searchactive == 1 ): ?>
    <div class="alert alert-warning alert-warning"><?php echo $this->translate('The search view is active.')?> 
    <a href="/<?php echo $this->controller ?>/reset"><?php echo $this->translate('Click here to reset the results.')?></a> </div>
<?php endif; ?>
   
<div class="row">
    <div class="col-lg-12">
        <?php if($this->filters):?>
           <strong><?php echo $this->translate('Filters');?>:</strong> 
           <select name="filter" id="filter">
                <option value=""><?php echo $this->translate('Show All');?></option>
                    <?php foreach ( $this->filters as $id=>$status ) : ?>
                        <option value="<?php echo $id?>"><?php echo $this->translate($status);?></option>
                    <?php endforeach;?>
            </select>
            <input type="button" class="btn btn-default" rel="<?php echo $this->controller ?>" id="filterbtn" value="<?php echo $this->translate('Execute');?>">
        <?php endif;?>
        
        <?php if($this->tags):?>
           <strong><?php echo $this->translate('Tags');?>:</strong> 
           <select name="tags" id="tags" rel="<?php echo $this->controller ?>">
                <option value=""><?php echo $this->translate('Show All');?></option>
                    <?php foreach ( $this->tags as $id=>$tag ) : ?>
                        <option value="<?php echo $id?>"><?php echo $tag;?></option>
                    <?php endforeach;?>
            </select>
            <input type="button" class="btn btn-default" rel="<?php echo $this->controller ?>" id="tagsbtn" value="<?php echo $this->translate('Execute');?>">
        <?php endif;?>
    </div>  
</div>  

<?php 
if (isset($this->records[0])):
    // Get all the items inside a multidimensional array
    $items = Shineisp_Commons_Utilities::array_flatten($this->records[0]);

	$columns = $this->columns;

	// Get all the fields
    $fields = array_keys($items);
    
    // Counting the field
    $numcols = count($fields);
    
?>
        <table class="table table-striped" id="itemlist">
            <thead>
                <tr>
                   <?php if($this->show_action_box && ($this->statuses || $this->customactions)):?><th><input type="checkbox" class="selectall" value=""></th><?php endif;?>
                    <?php // Creation of the Rows and Columns?>
                    <?php foreach ( $columns as $column ) : ?>
                    	<th><?php echo $column; ?></th>
                    <?php endforeach;?>   
                    <th><?php echo $this->translate('Commands');?></th>
                </tr>
            </thead>
            
            <tbody>
                 <?php // Creation of the Rows?>
                 <?php foreach ( $this->records as $record ) : ?>
                   <tr>
                   <?php if($this->show_action_box && ($this->statuses || $this->customactions)):?><td><input type="checkbox" name="item[]" value="<?php echo $record[$this->fields[0]] ?>"></td><?php endif;?>
                   <?php foreach ( $fields as $field ) : ?>
                       <?php if(strpos($field, "_id")=== false):?>
                        <?php
                                // Manage the sub arrays created by the HYDRATE_ARRAY records fetching mode  
                                 $res = "";  
                                 Shineisp_Commons_Utilities::search(array($field), $record, $res);
                                 $value = !empty($res[$field]) ? $this->translate($res[$field]) : "";?>
                                <td class="values"><a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/edit/id/<?php echo $record[$this->fields[0]]?>"><?php echo $value?></a></td>
                       <?php endif;?>
                   <?php endforeach;?>
                   <td>
                       <a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/edit/id/<?php echo $record[$this->fields[0]]?>"><?php echo $this->translate('Edit') ?></a>
                   </td>
                   </tr>
                <?php endforeach;?>
            
            </tbody>
            <tfoot>
                <tr>
                   <td colspan="<?php echo $numcols+1?>"> 
                       <div class="bulktools">
                           <?php if($this->show_action_box && ($this->statuses || $this->customactions)):?>
                               <strong><?php echo $this->translate('Actions');?>:</strong> 
                               <select name="actions" id="actions">
                                   <option value=""><?php echo $this->translate('Select ...');?></option>
                                   <?php if($this->statuses):?>
                                       <optgroup label="<?php echo $this->translate('Statuses');?>">
                                           <?php foreach ( $this->statuses as $id=>$status ) : ?>
                                               <option value="set_status&status=<?php echo $id?>"><?php echo $this->translate($status);?></option>
                                           <?php endforeach;?>
                                       </optgroup>
                                   <?php endif; ?>
                                   <?php if($this->customactions):?>
                                       <optgroup label="<?php echo $this->translate('Actions');?>">
                                       <?php foreach ( $this->customactions as $name=>$action ) : ?>
                                           <option value="<?php echo $name;?>"><?php echo $this->translate($action);?></option>
                                       <?php endforeach;?>
                                       </optgroup>
                                   <?php endif; ?>
                               </select>
                               <input type="button" class="btn btn-default" rel="<?php echo $this->controller ?>" id="bulkactions" value="<?php echo $this->translate('Execute');?>"><br />
                               <?php echo $this->translate('Select the items and then use the bulk action system to set more than one item.');?>
                            <?php endif; ?> 
                       </div>
                       <div class="row">
                           <div class="col-lg-6">
                               <ul class="pagination"><?php echo $this->pagination; ?></ul>
                           </div>
                           <div class="col-lg-6 text-right">
                                <ul class="pagination"> 
                                    <li><a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/5">5</a></li>
                                    <li><a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/15">15</a></li>
                                    <li><a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/30">30</a></li>
                                    <li><a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/50">50</a></li>
                                    <li><a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/100">100</a></li>
                                    <li><a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/all"><?php echo $this->translate('Show All');?></a></li>
                                </ul>
                           </div>
                       </div>
                   </td>
                </tr>
            </tfoot>
        </table>
        <div class="text-right"><?php echo $this->translate('Records');?>: <span class="label label-default"><?php echo $this->recordcount?></span></div>
    <?php else: ?>
    <div class="alert alert-warning alert-info"><?php echo $this->translate('No Records')?></div>
<?php endif; ?>
