<?php $form = $this->form; ?>
<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">
		<? if(isset($form) && $form->isErrors() ): ?>
			<div class="messages">    
			   <? foreach( $form->getElements() as $field){
			         $errors = array();
			   	     if($field->hasErrors()){
			        	foreach( $field->getErrors() as $error){
			        		$errors[] = $this->translate($error);
			        	}
			            echo "<div class=\"alert alert-warning alert-dismissable\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . " <a href=\"#\" class=\"close\">&times;</a></div>";
			        }   
			    } ?>
			</div>    
		<? endif; ?>
		
		<div class="headtitle">
		    <h3><?php 
			    if(!empty($this->name)){
			       	echo $this->name;
			    }elseif (!empty($this->title)){
					echo $this->title;
				}
		    ?></h3>
		    
		    <p><?php echo $this->description;?></p>
		    
		</div>
	</div>
</div>