<?php $langcode = $this->translate()->getLocale(); ?>
<?php $selectlang = Languages::get_language_name_by_code($langcode); ?>

<?php if(count($this->languages) > 1): ?>
    <li class="dropdown">
		<a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="glyphicon glyphicon-flag"></i> <?php echo $selectlang; ?></a>
		<ul class="dropdown-menu">
			<?php foreach ($this->languages as $language): ?>
				<?php if($language['language'] != $selectlang): ?>
					<li class="dropdown"><a class="<?php echo strtolower($language['language'])?>" href="/<?php echo $language['code']?>"><?php echo $this->translate($language['language']) ?></a></li>
				<?php endif; ?>
			<?php endforeach;?>
		</ul>	    
	</li>
<?php endif;?>    
