
<?php if(!empty($this->file) && file_exists(PUBLIC_PATH . $this->file)):?>
	<?php list($width, $height, $type, $attr) = getimagesize(PUBLIC_PATH . $this->file);?>
    <a class="navbar-brand" href="/"><img alt="<?php echo $this->logotitle ?> <?php echo $this->slogan ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" logotitle="<?php echo $this->logotitle ?> <?php echo $this->slogan ?>" src="<?php echo $this->file ?>"/></a>
<?php else:?>
    <a class="navbar-brand" href="/"><?php echo $this->logotitle ?></a>
<?php endif;?>