
<?php if(!empty($this->file) && file_exists(PUBLIC_PATH . $this->file)):?>
	<?php list($width, $height, $type, $attr) = getimagesize(PUBLIC_PATH . $this->file);?>
    <a href="/"><img alt="<?php echo $this->title ?> <?php echo $this->slogan ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" title="<?php echo $this->title ?> <?php echo $this->slogan ?>" src="<?php echo $this->file ?>"/></a>
<?php else:?>
    <h3 class="txtlogo" title="<?php echo $this->slogan ?>"><a href="/"><?php echo $this->title ?></a></h3>
<?php endif;?>