<?php $resources = $this->resources; ?>
<?php $productdata = $this->productdata; ?>
<?php $index = 0; ?>

<ul class="hidden-xs list-unstyled">

	<?php if(count($resources)==0): ?>
	    <li class="image-empty product-image"><a href="/<?php echo $productdata['uri']?>.html"><img class="img-responsive img-rounded" width="<?php echo $this->width?>" src="http://placehold.it/<?php echo $this->width?>&text=ShineISP"/></a></li>
	<?php endif; ?>
	
	<?php if(!empty($resources[0])): ?>
		<li class="image-standard product-image"><a href="<?php echo $resources[0]['path']?>"><?php echo $this->image($resources[0]['name'], $resources[0]['path'], array('width'=>$this->width, 'height'=>$this->height, 'class' => 'img-responsive img-rounded', 'alt' => $resources[0]['name'], 'title' => $resources[0]['name'])); ?></a></li>
		<?php unset($resources[0]);?>
		
	<?php endif; ?>
	
	<?php if($this->showall):?>
		
        <li class="">
            <ul class="list-inline">
                <?php foreach($resources as $resource):?>
                    <li><a title="<?php echo $resource['name']; ?>" href="#"><?php echo $this->image($resource['name'], $resource['path'], array('width'=>'80', 'class' => 'thumbnail img-responsive img-thumbnail', 'alt' => $resource['description'], 'title' => $resource['name'])); ?></a></li>
                <?php endforeach;?>
            </ul>
        </li>
		
	<?php endif ?>
</ul>

<div tabindex="-1" class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h3 class="modal-title">Heading</h3>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
