<div id="menu">
<?php
if($this->container){
    echo '<ul id="main-nav">';
    // loop root level (only has Home, but later may have an Admin root page?)
    foreach ($this->container as $page) {
        // check if it is active (not recursive)
        $isActive = $page->isActive(false);
        $liClass = $isActive ? ' class="nav-top-item active current"' : 'class="nav-top-item"';
        $pagename = $this->menu()->htmlify($page);
        echo '<li ' . $liClass . '>' . $pagename . '<br><small>'.$this->translate($page->description).'</small></li>', PHP_EOL;
        // loop next level
        foreach ($page as $page) {
            // check if it is active (recursive)
            $isActive = $page->isActive(true);
            $pagename = $this->menu()->htmlify($page);
            $liClass = $isActive ? ' menuitem active current"' : 'class="menuitem"';
            echo '<li ' . $liClass . '>' . $this->translate($pagename) . '</li>', PHP_EOL;
        }
    }
    echo '</ul>';
}    
?>
</div>