<div class="newsletter">
    <strong>Newsletter</strong>
    <p>I accept to subscribe the privacy terms: <a href="/cms/privacy.html">Privacy</a>.</p>
    <form id="newsletter" class="smartform" method="post" action="/newsletter/optin">
             <div>
	          <input type="text" name="email" title="write here your email">
		     <input type="hidden" value="add" name="action">
	     	     <input type="submit" class="newsletterbtn" value="Subscribe">
	     </div>
    </form>
</div>