<?php $payments = $this->payments ?>
<?php $i = 0; ?>

<div class="row">
	<div class="col-lg-12">
		<div class="section-container accordion" data-section="accordion">
	    <?php foreach($payments as $payment):?>
			<section class="<?php echo $i==0 ? "active": ""; ?>">
				<p class="title" data-section-title><a href="#"><?php echo $payment['name']?></a></p>
				<div class="content" data-section-content>
		        	<?php echo $payment['html']?>
		        </div>
		    </section>
		    <?php $i++?>
	    <?php endforeach; ?>
	    </div>
	</div>
</div>