<?php

$showallinfo = $this->showallinfo;
$vatNotIncludedlabel = $this->translate('Vat Excluded');
$measurement = "";
$bulletlist = "";

if ($this->data ['type'] == "multiple") {
	if (! empty ( $this->data ['minvalue'] )) {

		// Get the minimum value from the group of the prices
		$price = $this->data ['minvalue'];
		$pricetax = $this->data ['minvaluewithtaxes'];
		$discount = $this->data ['discount'];
		
		if(!empty($this->data ['tranches'][0])){
			$months = $this->data ['tranches'][0]['BillingCycle']['months'];
		}else{
			$months = "";
		}
		
		$pricetax = $this->currency($pricetax, array('currency' => Settings::findbyParam('currency')));
		$price = $this->currency($price, array('currency' => Settings::findbyParam('currency')));
		
		$bulletlist = "<ul class=\"no-bullet prices\">";
		
		// Get the recurring period label
		if(!empty($this->data['tranches'][0] ['measurement'])){
			$measurement = '<span class="frequency">'.$this->translate($this->data['tranches'][0] ['measurement']).'</span>';
		}
		
		// Print the price
		$bulletlist .= "<li class=\"priceincludedvat\" title=\"".$this->translate('VAT included')."\">$pricetax " . "</li>";
		$bulletlist .= "<li class=\"pricenotincludedvat\" >$price $measurement $vatNotIncludedlabel</li>";

		// Simple raw text price 
		$rawtextprice = $pricetax . "<br><small>$months $measurement</small>";
	
		if($showallinfo && !empty($this->data['tranches'][0] ['BillingCycle']['name']) && !empty($this->data['discount'])){
			$bulletlist .= "<li class='subscription'>" .  $this->translate('Subscribing %s you can save %s', $this->translate($this->data['tranches'][0] ['BillingCycle']['name']), " " .  $this->currency($this->data['discount'], array('currency' => Settings::findbyParam('currency')))) . "</li>";
		}
	
	}
} else {
	
	$bulletlist = "<ul class=\"no-bullet prices\">";
	
	$price = $this->data ['value'];
	$pricetax = $this->data ['taxincluded'];
	
	$price = $this->currency($price, array('currency' => Settings::findbyParam('currency')));
	$pricetax = $this->currency($pricetax, array('currency' => Settings::findbyParam('currency')));
	
	// Print the price
	$bulletlist .= "<li class=\"priceincludedvat\" title=\"".$this->translate('VAT included')."\"><strong>$pricetax</strong></li>";
	$bulletlist .= "<li class=\"pricenotincludedvat\" >$price $vatNotIncludedlabel</li>";

	// Simple raw text price
	$rawtextprice = $pricetax;
}
	
$bulletlist .= "</ul>";

if($this->onlymasterprice){
	echo $rawtextprice;
}else{
	echo $bulletlist;
}
