<?php 
	$isp = Isp::getActiveISP(); 
	$ns = new Zend_Session_Namespace ();
?>
<li class="dropdown">
    <?php if(!empty($ns->customer)): ?>
    	<a class="dropdown-toggle" data-toggle="dropdown" accesskey="H" title="<?php echo $this->translate('Press %s to open the page', 'Alt+Shift+H')?>" href="#">
    		<i class="glyphicon glyphicon-user"></i>  
    		<?php if($ns->customer['gender'] == "F"): ?>
    			<?php echo $this->translate('Welcome Mrs. %s', $ns->customer['lastname'])?>
    		<?php elseif($ns->customer['gender'] == "M"): ?>
    			<?php echo $this->translate('Welcome Mr. %s', $ns->customer['lastname'])?>
    		<?php else: ?>
    			<?php echo $this->translate('Welcome %s', $ns->customer['lastname'])?>
    		<?php endif; ?>
    	</a>
    	<ul class="dropdown-menu">
    	    <?php if($this->userlogged):?>
             <li class="dropdown">
                 <a href="/dashboard" title="<?php echo $this->translate('Press %s to open the page', 'Alt+Shift+D')?>" accesskey="D" ><?php echo $this->translate('Dashboard') ?></a>
             </li>
             <li class="dropdown">
                 <a href="/profile" title="<?php echo $this->translate('Press %s to open the page', 'Alt+Shift+P')?>" accesskey="P" ><?php echo $this->translate('Profile') ?></a>
             </li>
             <li class="dropdown">
                 <a class="removeqtip" title="<?php echo $this->translate('Press %s to open the page', 'Alt+Shift+O')?>" accesskey="O" class="tooltip" href="/index/out">
                    <?php echo $this->translate('Logout') ?>
                 </a>
             </li>        
        <?php else: ?>
                <li class="dropdown">
                     <a title="<?php echo $this->translate('Press %s to open the page', 'Alt+Shift+I')?>" accesskey="I" href="/customer/login">
                        <?php echo $this->translate('Sign in') ?>
                     </a>
                 </li>
        <?php endif; ?>
    	</ul>
    <?php else: ?>
    	<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="glyphicon glyphicon-user"></i> <?php echo $this->translate('Login')?> <b class="caret"></b></a>
    	<ul class="dropdown-menu">
    	    <li class="dropdown"><a href="/customer/login"><?php echo $this->translate('Sign In')?></a></li>
    	</ul>
    <?php endif; ?>
</li>
