<?php if (isset($this->searchactive) && $this->searchactive == 1 ): ?>
    <div class="notification attention"><?php echo $this->translate('The search view is active.')?> 
    <a href="/<?php echo $this->controller ?>/reset"><?php echo $this->translate('Click here to reset the results.')?></a> </div>
<?php endif; ?>
   
<?php if(!empty($this->mex)) :?>
    <div class="notification <?php echo $this->mexstatus; ?>"><?php echo $this->translate($this->mex);?></div>
<?php endif;?>

<br/>

<div class="filters">
<?php if($this->filters):?>
   <b><?php echo $this->translate('Filters');?>:</b> 
   <select name="filter" id="filter">
        <option value=""><?php echo $this->translate('Show All');?></option>
            <?php foreach ( $this->filters as $id=>$status ) : ?>
                <option value="<?php echo $id?>"><?php echo $this->translate($status);?></option>
            <?php endforeach;?>
    </select>
    <input type="button" class="littlebutton" rel="<?php echo $this->controller ?>" id="filterbtn" value="<?php echo $this->translate('Execute');?>">
<?php endif;?>

<?php if($this->tags):?>
   <b><?php echo $this->translate('Tags');?>:</b> 
   <select name="tags" id="tags" rel="<?php echo $this->controller ?>">
        <option value=""><?php echo $this->translate('Show All');?></option>
            <?php foreach ( $this->tags as $id=>$tag ) : ?>
                <option value="<?php echo $id?>"><?php echo $tag;?></option>
            <?php endforeach;?>
    </select>
    <input type="button" class="littlebutton" rel="<?php echo $this->controller ?>" id="tagsbtn" value="<?php echo $this->translate('Execute');?>">
<?php endif;?>
</div>  

<?php 
if (isset($this->records[0])):
    // Get all the items inside a multidimensional array
    $items = Shineisp_Commons_Utilities::array_flatten($this->records[0]);

	$columns = $this->columns;
	
	// Get all the fields
    $fields = array_keys($items);
    
    // Counting the field
    $numcols = count($fields);
    
?>
        <div class="notification infos" id="mex" style="display:none"></div>
        
        <table border="0" cellpadding="5" class="simplegrid zebratable" id="itemlist">
            <thead>
                <tr>
                   <?php if($this->show_action_box && ($this->statuses || $this->customactions)):?><th><input type="checkbox" class="selectall" value=""></th><?php endif;?>
                    <?php // Creation of the Rows and Columns?>
                    <?php foreach ( $columns as $column ) : ?>
                    	<th><?php echo $column; ?></th>
                    <?php endforeach;?>                   
                    <th><?php echo $this->translate('Commands');?></th>
                </tr>
            </thead>
            
            <tbody>
                 <?php // Creation of the Rows?>
                 <?php foreach ( $this->records as $record ) : ?>
                   <tr>
                   <?php if($this->show_action_box && ($this->statuses || $this->customactions)):?><td><input type="checkbox" name="item[]" value="<?php echo $record[$this->fields[0]] ?>"></td><?php endif;?>
                   <?php foreach ( $fields as $field ) : ?>
                       <?php if(strpos($field, "_id")=== false):?>
                        <?php
                                // Manage the sub arrays created by the HYDRATE_ARRAY records fetching mode  
                                 $res = "";  
                                 Shineisp_Commons_Utilities::search(array($field), $record, $res);
                                 $value = !empty($res[$field]) ? $this->translate($res[$field]) : "";?>
                                <td class="values"><a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/edit/id/<?php echo $record[$this->fields[0]]?>"><?php echo $value?></a></td>
                       <?php endif;?>
                   <?php endforeach;?>
                   <td>
                       <a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/edit/id/<?php echo $record[$this->fields[0]]?>"><?php echo $this->translate('Edit') ?></a>
                       <a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/change/id/<?php echo $record[$this->fields[0]]?>"><?php echo $this->translate('Upgrade') ?></a>
                   </td>
                   </tr>
                <?php endforeach;?>
            
            </tbody>
            <tfoot>
                <tr>
                   <td colspan="<?php echo $numcols+1?>"> 
                       <div class="bulktools">
                           <?php if($this->show_action_box && ($this->statuses || $this->customactions)):?>
                               <b><?php echo $this->translate('Actions');?>:</b> 
                               <select name="actions" id="actions">
                                   <option value=""><?php echo $this->translate('Select ...');?></option>
                                   <?php if($this->statuses):?>
                                       <optgroup label="<?php echo $this->translate('Statuses');?>">
                                           <?php foreach ( $this->statuses as $id=>$status ) : ?>
                                               <option value="set_status&status=<?php echo $id?>"><?php echo $this->translate($status);?></option>
                                           <?php endforeach;?>
                                       </optgroup>
                                   <?php endif; ?>
                                   <?php if($this->customactions):?>
                                       <optgroup label="<?php echo $this->translate('Actions');?>">
                                       <?php foreach ( $this->customactions as $name=>$action ) : ?>
                                           <option value="<?php echo $name;?>"><?php echo $this->translate($action);?></option>
                                       <?php endforeach;?>
                                       </optgroup>
                                   <?php endif; ?>
                               </select>
                               <input type="button" rel="<?php echo $this->controller ?>" id="bulkactions" value="<?php echo $this->translate('Execute');?>"><br />
                               <?php echo $this->translate('Select the items and then use the bulk action system to set more than one item.');?>
                            <?php endif; ?> 
                       </div>
                   </td>
                </tr>
                <tr>
                   <td colspan="<?php echo $numcols+1?>">
                        <div class="col-lg-6"><?php echo $this->pagination; ?></div>
                        <div class="col-lg-6">
                            <p align="right"><?php echo $this->recordcount?> <?php echo $this->translate('Records');?><br/> 
                            <?php echo $this->translate('Records per page');?>: 
                            <a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/5">5</a>
                            <a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/15">15</a>
                            <a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/30">30</a>
                            <a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/50">50</a>
                            <a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/100">100</a>
                            <a href="/<?php echo $this->module ?>/<?php echo $this->controller ?>/recordsperpage/id/all"><?php echo $this->translate('Show All');?></a>
                            </p>
                       </div>
                   </td>
                </tr>
            </tfoot>
        </table>
    <?php else: ?>
    <div class="notification infos"><?php echo $this->translate('No Records')?></div>
<?php endif; ?>
