<?php 
if (isset($this->records[0])):
    // Get all the items inside a multidimensional array
    $items = Shineisp_Commons_Utilities::array_flatten($this->records[0]);

	$columns = $this->columns;
    
    // Get all the fields
    $fields = array_keys($items);
    
    // Counting the records
    $recordcount = count($this->records);
    
    // Counting the field
    $numcols = count($fields);
?>
    
    <table class="table table-striped table-hover table-responsive data sublist" id="sublist_<?php echo $this->name?>">
        <thead>
            <tr>
                <?php // Creation of the Rows and Columns?>
                <?php foreach ( $columns as $column ) : ?>
                	<th><?php echo $column; ?></th>
                <?php endforeach;?>
                <?php if($this->view || $this->edit || $this->delete || $this->actions ):?><th><?php echo $this->translate('Commands');?></th><?php endif;?>
            </tr>
        </thead>
        <tbody>
             <?php  // Creation of the Rows?>
             <?php foreach ( $this->records as $record ) : ?>
               <tr>
               <?php foreach ( $fields as $field ) : ?>
                    <?php if(strpos($field, "_id")=== false):?>
                        <?php
                        // Manage the sub arrays created by the HYDRATE_ARRAY records fetching mode    
                         Shineisp_Commons_Utilities::search(array($field), $record, $res);
                         $value = !empty($res[$field]) ? $this->translate($res[$field]) : "";
                         ?>
                         <td class="values"><?php echo $value?></td>
                     <?php endif;?>
               <?php endforeach;?>
               <?php if($this->view || $this->edit || $this->delete || $this->actions):?>
               <td>
                    <?php if($this->view):?>
                       <a target="<?php echo $this->targetlink ?>" href="<? echo "/" . $this->module . "/" . $this->view['controller'] . "/" . $this->view['action'] . "/id/" . $record[$fields[0]]?>" title="<?php echo $this->translate('Click here to view'); ?>"><?php echo $this->translate('View'); ?></a>
                    <?php endif;?>

                    <?php if($this->edit):?>
                        <a target="<?php echo $this->targetlink ?>" href="<? echo "/" . $this->module . "/" . $this->edit['controller'] . "/" . $this->edit['action'] . "/id/" . $record[$fields[0]]?>" title="<?php echo $this->translate('Click here to edit'); ?>"><?php echo $this->translate('Edit'); ?></a>
                    <?php endif;?>
                    
                    <?php if($this->delete):?>
                        <a target="<?php echo $this->targetlink ?>" href="<? echo "/" . $this->module . "/" . $this->delete['controller'] . "/" . $this->delete['action'] . "/id/" . $record[$fields[0]]?>" title="<?php echo $this->translate('delete'); ?>"><?php echo $this->translate('Delete'); ?></a>
                    <?php endif;?>
                    
                    <?php if($this->actions && count($this->actions) > 1):?>
                        <?php foreach ($this->actions as $action): ?>
	                        <?php foreach ($action as $url=>$name): ?>
	                            <a target="<?php echo $this->targetlink ?>" href="<? echo $url . $record[$fields[0]]?>" title="<?php echo $name;?>"><?php echo $name; ?></a>
                        	<?php endforeach;?>
                        <?php endforeach;?>
                    <?php elseif($this->actions):?>
                        <?php foreach ($this->actions as $url=>$name): ?>
                            <a target="<?php echo $this->targetlink ?>" href="<? echo $url . $record[$fields[0]]?>" title="<?php echo $name;?>"><?php echo $name;?></a>
                        <?php endforeach;?>
                    <?php endif;?>
                    
                    <?php if($this->onclick):?>
                        <?php foreach ($this->onclick as $onclick=>$name): ?>
                            <a href="#" title="<?php echo $this->translate($name); ?>" onclick="<?php echo str_replace('[id]', $record[$fields[0]], $onclick);?>" >
                            	<?php echo $name; ?>
                            </a>
                        <?php endforeach;?>
                    <?php endif;?>
                    
               </td>
               <?php endif;?>
               </tr>
            <?php endforeach;?>
        
        </tbody>
    </table>
    <?php else: ?>
        <div class="alert alert-info"><?php echo $this->translate('No Records')?></div>
<?php endif; ?>
