<?php 
if (isset($this->records[0])):
    // Get all the items inside a multidimensional array
    $items = Shineisp_Commons_Utilities::array_flatten($this->records[0]);
    
	$columns = $this->columns;

    // Get all the fields
    $fields = array_keys($items);
    
    // Counting the field
    $numcols = count($fields);
    
?>
    <table class="table table table-striped" id="sublist_<?php echo $this->name?>">
            <thead>
                <tr>
                    <?php // Creation of the Rows and Columns?>
                    <?php foreach ( $columns as $column ) : ?>
                    	<th><?php echo $column; ?></th>
                    <?php endforeach;?>
                    <?php if($this->edit || $this->delete || $this->actions ):?><th><?php echo $this->translate('Actions');?></th><?php endif;?>
                </tr>
            </thead>
            
            <tbody>
                 <?php  // Creation of the Rows?>
                 <?php foreach ( $this->records as $record ) : ?>
                   <tr>
                   <?php foreach ( $fields as $field ) : ?>
                        <?php if(strpos($field, "_id")=== false):?>
	                        <?php
	                        // Manage the sub arrays created by the HYDRATE_ARRAY records fetching mode    
	                         Shineisp_Commons_Utilities::search(array($field), $record, $res);
	                         $value = !empty($res[$field]) ? $this->translate($res[$field]) : "";
	                         ?>
	                         <td class="values"><?php echo $value?></td>
                         <?php endif;?>
                   <?php endforeach;?>
                   <?php if($this->edit || $this->delete || $this->actions):?>
                   <td>
	                    <?php if($this->edit):?>
                            <a href="<? echo "/" . $this->module . "/" . $this->edit['controller'] . "/" . $this->edit['action'] . "/id/" . $record[$fields[0]]?>" title="<?php echo $this->translate('Click here to edit'); ?>" class="btn btn-default" ><?php echo $this->translate('Edit'); ?></a>
                        <?php endif;?>
                        
                        <?php if($this->delete):?>
                            <a href="<? echo "/" . $this->module . "/" . $this->delete['controller'] . "/" . $this->delete['action'] . "/id/" . $record[$fields[0]]?>" title="<?php echo $this->translate('Click here to delete'); ?>" class="btn btn-default"><?php echo $this->translate('Delete'); ?></a>
                        <?php endif;?>
                        
                        <?php if($this->actions):?>
	                        <?php foreach ($this->actions as $url=>$name): ?>
	                            <a href="<? echo $url . $record[$fields[0]]?>" title="<?php echo $this->translate($name); ?>"><?php echo $this->translate($name); ?></a>
	                        <?php endforeach;?>
                        <?php endif;?>
                   </td>
                   <?php endif;?>
                   </tr>
                <?php endforeach;?>
            
            </tbody>
        </table>
 
    <?php else: ?>
	    <div class="alert alert-warning alert-dismissable" id="mex" >
	      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	      <?php echo $this->translate('No Records')?>
	    </div>
<?php endif; ?>
