<?php $products = $this->products; ?>
<?php if(!empty($products)): ?>
	<?php foreach($products as $product): ?>
	
		<?php 
		
			$attributes = ProductsAttributesIndexes::getAttributebyProductID($product['product_id']);
			$price = Products::getPrices($product['product_id']);
			
			if(!empty($product['name'])):
				$result = preg_split('/ /', $product['name'], 2);
				
				$firstword = $result[0];
				$otherwords = $result[1]; ?>
	
				<div class="slide clearfix">
					<div class="slideSwitchLabel">
						<strong><?php echo $product['nickname'] ?></strong> 
					</div>
					<div class="information">
						<h1><a href="/<?php echo $product['uri']?>.html"><?php echo $firstword ?> <span><?php echo $otherwords ?></span></a></h1>
						<p><?php echo Shineisp_Commons_Utilities::truncate(strip_tags($product['description']), 70, "...", false, false) ?></p>
						
						<ul class="clearfix">
							<?php foreach($attributes as $attribute): ?>
								<?php if($attribute['on_product_listing']):?>
									<li title="<?php echo $attribute['description'] ?>"><strong><?php echo $attribute['prefix']. " " . $attribute['value']. " " . $attribute['suffix'] ?></strong> <?php echo $attribute['label']?></li>
								<?php endif; ?>
							<?php endforeach;?>
						</ul>
						
						<div class="box clearfix">
							
							<?php if($price['type'] == "multiple"): ?>
								<div class="label">
									<?php echo $this->translate("Starting at")?>
								</div>
								<div class="price">
									<?php echo $this->prices()->getPriceIncludedVat($product['product_id'])?>
								</div>
								
							<?php elseif ($price['type'] == "flat"): ?>
								<div class="label">
									<?php echo $this->translate("Starting at")?>
								</div>
								<div class="price">
									<?php echo $this->currency($price['value'], array('currency' => Settings::findbyParam('currency')))?>
								</div>
								
							<?php endif;?>
							<a class="colorButton" href="/compare/products/code/<?php echo $product['groupcode']?>"><span class="pointer"><?php echo $this->translate('View all available plans now') ?></span></a>
						</div>
					</div>
					<?php list($width, $height, $type, $attr) = getimagesize(PUBLIC_PATH . "/skins/default/base/images/server.png");?>
					
					<img src="/skins/default/base/images/server.png" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="Shared" />
				</div>
		 <?php endif;?>
	<?php endforeach;?>
<?php endif;?>