<?php $products = $this->products; ?>

<?php if(!empty($products)): ?>
	<div class="orbit-container">
		<ul id="featured">
		<?php foreach($products as $product): ?>
			<li>
				<img src="http://placehold.it/1600x600&text=<?php echo $product['name']?>">
			</li>
			<?php endforeach;?>
		</ul>
	</div>
	<script>
	    $(window).load(function(){
	      $("#featured").orbit();
	    });
	</script> 
<?php endif;?>
