<ul class="navigation">
	 
     <?php if(!empty($this->menu)): ?>
     	<?php echo $this->menu ?>
     <?php endif;?>
     
     <?php if(!empty($this->cartitems)): ?>
	     <li> 
		 	<?=$this->cart();?>
		 </li>
	 <?php endif; ?>
	 
     <li>   
     	<a class="dropdown" accesskey="H" title="<?php echo $this->translate('Press %s to open the page', 'Alt+Shift+H')?>" href="/"><?=$this->translate('Profile') ?></a>
	 	<?php echo $this->profile ();?>
	 </li>
	 
</ul>
