<ul class="<?php echo !empty($this->menucls) ? $this->menucls : "navigation" ?>">
	 
     <?php if(!empty($this->menu)): ?>
     	<?php echo $this->menu ?>
     <?php endif;?>
     
     <?php if(!empty($this->cartitems)): ?>
	     <li class="has-dropdown" > 
		 	<?php echo $this->cart();?>
		 </li>
	 <?php endif; ?>
	 
     <li class="has-dropdown" >  
	 	<?php echo $this->profile ();?>
	 </li>
	 
</ul>
