<?php $wiki = $this->items; ?>
<div class="headtitle"></div>
<h4><?php echo $this->translate('Wiki Help') ?></h4>
<p>
	<?php echo $this->translate('Read our wiki articles before asking.') ?><br/>
	<a href="/wiki"><?php echo $this->translate('Search on Wiki Help Guide') ?></a>
</p><br/>

<ul id="wikilist" class="no-bullet">
	<?php foreach($wiki as $item):?>
		<li><h6><a href="/wiki/<?php echo $item['uri']?>.html"><?php echo $item['subject'] ?></a></h6>
		<small><?php echo $this->translate('Category') . ": " . $item['WikiCategories']['category']?></small>
		<p><?php echo Shineisp_Commons_Utilities::CropSentence(strip_tags($item['content']), 100, "...")?></p>
		</li>
	<?php endforeach;?>
</ul>