<?php $wiki = $this->items; ?>

<h4><?php echo $this->translate('Wiki Help') ?></h4>
<p><?php echo $this->translate('Read our wiki articles before asking.') ?><br/></p>

<div class="list-group">
    <?php foreach($wiki as $item):?>
        <a href="/wiki/<?php echo $item['uri']?>.html" class="list-group-item">
            <h4 class="list-group-item-heading"><?php echo $item['subject'] ?></h4>
            <p class="list-group-item-text"><?php echo Shineisp_Commons_Utilities::CropSentence(strip_tags($item['content']), 100, "...")?></p>
        </a>
	<?php endforeach;?>  
</div>
<a class="btn btn-success" href="/wiki"><?php echo $this->translate('Search on Wiki Help Guide') ?></a>