<?php $form = $this->form ?>
<?php echo  $this->render('partials/header.phtml') ?>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>" id="setup">
	<div class="container" id="page_wrapper">
		<div class="row" id="page">
					
			<div class="col-lg-12 col-md-12" id="content">
				<div class="progress" style="display:none">Please wait a moment...</div>
				
				<?php if($this->error):?>
					 <div class="notification error"><?php echo $this->error?></div>
				<?php endif;?>
				
				<div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('Preferences Settings')?></div>
                    <div class="panel-body">
                    	<div class="col-lg-6 col-md-6 col-xs-12">
	                    	<?php echo $form->company->render() ?>
	    					<?php echo $form->firstname->render() ?>
	    					<?php echo $form->lastname->render() ?>
	    					<?php echo $form->email->render() ?>
                    	</div>
                    	<div class="col-lg-6 col-md-6 col-xs-12">
                    		<?php echo $form->password->render() ?>
	    					<?php echo $form->password_confirm->render() ?>
                    	</div>
				    </div>
				</div>
				<div class="pull-right"><?php echo $form->submit->render() ?></div>
				<?php echo  $this->render('partials/footer.phtml') ?>			
			</div>		
		</div>
	</div>
</form>
