<?php $post = $this->post;?>

<div class="row">
	<div class="col-lg-12">
		<h3><?php echo $post['subject']?></h3>
		<p><?php echo $this->translate('Category') ?>: <?php echo $post['category']?></p>
		<div id="pageToc"></div>
		<div id="wiki" class="wiki" class="wikihelp"><?php echo $post['content']; ?></div>
		<p><?php echo $this->translate('posted') ?> <?php echo Shineisp_Commons_Utilities::formatDateOut($post['creationdate']) ?> | <?php echo $this->translate('This article has been read %s times', $post['views']); ?></p>
		<p><a href="/wiki"><?php echo $this->translate('back to the list') ?></a></p>
	</div>
</div>