<?php $post = $this->post;?>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">
		<h3><?php echo $post['subject']?></h3>
		<p><span title="<?php echo $this->translate('Category') ?>" class="badge"><?php echo $post['category']?></span></p>
		
		<div id="wiki" class="wiki" class="wikihelp"><?php echo $post['content']; ?></div>
		<div class="well well-sm"><?php echo $this->translate('posted') ?> <?php echo Shineisp_Commons_Utilities::formatDateOut($post['creationdate']) ?> | <?php echo $this->translate('This article has been read %s times', $post['views']); ?></div>
		<p class="text-right"><a class="btn btn-info" href="/wiki"><?php echo $this->translate('back to the list') ?></a></p>
	</div>
</div>