<?php echo $this->render('partials/header.phtml') ?>
<?php $posts = $this->wiki['records'];?>
<?php $form = $this->form;?>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">
		<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>">
			<?php echo $form->topic->render()?>
			<p align="right"><?php echo $form->wikisearch->setDecorators(array('ViewHelper'))?></p>
		</form>
	</div>
	
	<div class="col-lg-12 col-md-12 col-xs-12">
		<?php foreach($posts as $post):?>
		    <div id="post-<?php echo $post['wiki_id'];?>" class="wikipost">
		        <div class="entry">
		            <h5 id="post-<?php echo $post['wiki_id'];?>">
		            	<a title="Permanent Link to <?php echo $post['subject'];?>" rel="bookmark" href="/wiki/<?php echo $post['uri'];?>.html"><?php echo $post['subject'];?></a>
		            </h5>
		            <small><?php echo $this->translate('Posted')?>: <?php echo $post['creationdate'];?> in <a title="<?php echo $post['category_id'];?>" href="#"> <?php echo $post['category'];?> </a></small> <br/>
		            <p>
		            	<?php $introduction = Shineisp_Commons_Utilities::truncate($post['content'], 200, "...", false, true)?>
		            	<?php echo strip_tags($introduction);?>
		            </p>
		        </div>
		    </div>
		<?php endforeach;?>
	</div>
	
	<div class="col-lg-12 col-md-12 col-xs-12">
		<h4><a href="/customer/login"><?php echo $this->translate('Have you found what you need? If not write a question here.') ?></a></h4>
	</div>
</div>