<?php $products = $this->products; ?>
<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">
		<h5><?php echo $this->translate('Products Reference')?></h5>
		<?php foreach ($products as $product): ?>
			<?php if(!empty($product['Products']['ProductsData'][0]['name'])): ?>
				
				<div class="row">
					<div class="col-lg-3">
				    	<?php echo $this->media()->ProductImage($product['product_id'], 60, 60, false);?>
					</div>
					<div class="col-lg-9">
						<h6><a href="/<?php echo $product['Products']['uri']?>.html"><?php echo $product['Products']['ProductsData'][0]['name']?></a></h6>
						<p><?php echo Shineisp_Commons_Utilities::truncate($product['Products']['ProductsData'][0]['shortdescription'], 100, "...", false, true) ?></p>
					</div>
				</div>
			<?php endif; ?>
		<?php endforeach;?>
	</div>
</div>