<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
    <?php echo $form->subject->render() ?>
    <?php echo $form->body->render() ?>
    <?php echo $form->send->render() ?>
</form>