<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"notification error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form class="multiple_select_form" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div id="tabs">
		<ul>
			<li><a href="#tab1"><?=$this->translate('Main');?></a></li> 
		</ul>

	    <div id="tab1"> 
            <?php echo $form->var->render()?> 
            <?php echo $form->title->render()?>
            <?php echo $form->language_id->render()?>
            <?php echo $form->body->render()?>
            <a class="toggle button" href="#"><?php echo $this->translate('Disable/Enable Wysiwyg')?></a>
    	</div>
    </div>    
   <?php echo $form->block_id->render()?>
</form>
</div>

