<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">

	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Resources');?></a></li> 
			<li><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Users');?></a></li> 
		</ul>
        <div class="tab-content">
    	    <div class="tab-pane active" id="tab1"> 
    	        <?php echo $form->name->render() ?>
    	    </div>
        
    	    <div class="tab-pane" id="tab2"> 
    	        <div id="resources" name="resources"></div>
    	    </div>
        
    	    <div class="tab-pane" id="tab3"> 
    	        <?php echo $form->users->render() ?>
    	    </div>
    	</div>
    </div>
	
	<?php echo $form->role_id->render() ?>
</form>

<script type="text/javascript">
<!--
function isArray(variable) {
	if (variable.constructor == Array)
		return true;
	else
	    return false;
}

var data = <?php echo $this->resources ?>;

$(function(){
    $("#resources").dynatree({
    	children: data,
        data: {mode: "all"},
        checkbox: true,
        selectMode: 2,
        minExpandLevel: 2
        
    });
    
    $("form").submit(function() {
        
        // then append Dynatree selected 'checkboxes':
       var tree = $("#resources").dynatree("getTree");
        var data = tree.serializeArray();
        var items = new Array();
        
        $('#resourcesitems').remove();
        
        $.each(data, function(i, fd) {
            items[i]= fd.value;
        });    
        
        if(isArray(items) && items.length > 0){
        	$(this).append("<input type='hidden' id='resourcesitems' name='resources' value='"+items.join("/")+"' />");
        }     
    });
});


//-->
</script>
</div>