<?php $form = $this->form; ?>
<?php echo $this->render('partials/header.phtml') ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
    <fieldset>
    	<legend><?php echo $this->translate('Generic data') ?></legend>
        <div class="row">
			<div class="large-6 columns"> 
				<?php echo $form->firstname->render() ?>
	        	<?php echo $form->lastname->render()?>
	        	<?php echo $form->email->render()?>
	        	<?php echo $form->password->render()?>
	        </div>
	        
		    <div class="large-6 columns">
		    	<?php echo $form->legalform->render()?>
		    	<?php echo $form->company->render()?>
	            <?php echo $form->company_type_id->render()?>
	            <?php echo $form->vat->render()?>
		    </div>
	    </div>
    </fieldset>
    
    <fieldset>
    	<legend><?php echo $this->translate('Personal data') ?></legend>
        <div class="row">
			<div class="large-6 columns"> 
		        <?php echo $form->birthdate->render()?>
	            <?php echo $form->birthplace->render()?>
	            <?php echo $form->birthdistrict->render()?>
	            <?php echo $form->birthcountry->render()?>
	            <?php echo $form->birthnationality->render()?>
	        </div>
	        <div class="large-6 columns"> 
	            <?php echo $form->gender->render()?>
	            <?php echo $form->taxpayernumber->render()?> 
			</div>
		</div>
    </fieldset>
    
    <fieldset>
    	<legend><?php echo $this->translate('Address') ?></legend>
        <div class="row">
			<div class="large-12 columns"> 
	            <?php echo $form->address->render()?>
	            <?php echo $form->code->render()?>
	            <?php echo $form->city->render()?>
	            <?php echo $form->area->render()?>
	            <?php echo $form->country_id->render()?>
			</div>
    	</div>
	</fieldset>
	
   <fieldset>
    	<legend><?php echo $this->translate('Contacts') ?></legend>
        <div class="row">
			<div class="large-12 columns">
	             <?php echo $this->simplegrid($this->contactsdatagrid);?>
	             <?php echo $form->contacttypes->render()?>
	             <?php echo $form->contact->render()?>
	   		</div>
	   </div>
   </fieldset>

   <?php if($this->isReseller):?>
	   <fieldset>
	    	<legend><?php echo $this->translate('My Customers') ?></legend>
	        <div class="row">
				<div class="large-12 columns">
		        	<?php echo  $this->simplegrid($this->clients);?>
			    </div>
			</div>
	   </fieldset>
   <?php endif;?>
   
   
   <fieldset>
    	<legend><?php echo $this->translate('Newsletter') ?></legend>
        <div class="row">
			<div class="large-12 columns">
	       		<?php echo $form->newsletter->render()?>
		    </div>
	   </div>
   </fieldset>
	<p align="right"><?php echo $form->submit->render()?></p>
   <?php echo $form->customer_id->render()?>
</form>

