<div class="headtitle">
    <h3><?php echo $this->translate('deleteaction');;?></h3>
    <small><?php echo $this->translate('desc_deleteaction');?></small>
</div>
<h3><?=$this->contact[0]['contact']; ?></h3>
<p><?=$this->translate('areusure'); ?></p>
<p>
<a href="/profile"><?=$this->translate('noiwrong'); ?></a>
<a href="/profile/delete/id/<?=$this->contact[0]['contact_id']; ?>"><?=$this->translate('yesiwant'); ?></a>
</p>