<?php $form = $this->form;?>
<?php $setup = $this->setup; ?>

<?php echo $this->render('partials/header.phtml') ?>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">	
		<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" class="custom dropdown" action="<?php echo $form->getAction()?>">
			<div class="section-container" data-section data-options="deep_linking: false; one_up: false">
		
			    <div class="section"> 
			    	<div class="title" data-section-title><a href="#tab1"><?php echo $this->translate('Main') ?></a></div>
		          	<div class="content" data-slug="tab1">
		          		<h3><?php echo $this->translate('Main') ?></h3>
			            <?php echo $this->verticalgrid($this->datagrid)?>
			            <?php echo $form->autorenew->render() ?>
			            <?php if( isset( $form->upgrade ) ) { echo $form->upgrade->render(); } ?>
			        </div>
			    </div>
			    
			    <?php if($setup): ?>
			    <div class="section"> 
			    	<div class="title" data-section-title><a href="#tab1"><?php echo $this->translate('Configuration') ?></a></div>
			    	<div class="content" data-slug="tab2">
				    	<ul id="setup">
				    	<?php foreach ($setup as $service => $item):?>
				    		<li>
				    			<h3><?php echo $service ?></h3>
					    		<?php foreach ($item as $label => $data):?>
					    			<?php echo $label ?>: <?php echo $data?><br/>
					    		<?php endforeach; ?>	
					    	</li>
				    	<?php endforeach; ?>
				    	</ul>
				    </div>
			    </div>
			    <?php endif;?>
			    
			    <div class="section"> 
			    	<div class="title" data-section-title><a href="#tab1"><?php echo $this->translate('Messages') ?></a></div>
			    	<div class="content" data-slug="tab3">
				    	<p><?php echo $this->translate('Here you can see all the questions and replies about this service/domain') ?></p>
			            <?php echo $this->bbslist($this->messages); ?>
			            <p><?php echo $form->message->render()?></p>
			            <br/>
			            <p align="right"><?php echo $form->submit->render()?></p>
			    	</div>
			    </div>    
			
			</div>
			
			<?php echo $form->detail_id->render()?>
			<p align="right"><?php echo $form->submit->render()?></p>
		</form>
	</div>
</div>
