<?php $form = $this->form;?>
<?php $setup = $this->setup; ?>

<?php echo $this->render('partials/header.phtml') ?>

<div class="row">
	<div class="col-lg-12 col-md-12 col-xs-12">	
		<h2><?php echo $this->domainame ?></h2>
		<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" class="custom dropdown" action="<?php echo $form->getAction()?>">
            
            <div class="tabbable" id="tabs">
            
        		<ul class="nav nav-tabs">
        			<li class="active"><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
        			<?php if(!empty($setup)): ?><li class=""><a data-toggle="tab" href="#tab2"><?php echo $this->translate('Configuration');?></a></li><?php endif;?> 
        			<li class=""><a data-toggle="tab" href="#tab3"><?php echo $this->translate('Messages');?></a></li> 
        		</ul>
        			    
        	    <div class="tab-content">
        	    
        		    <div class="tab-pane active" id="tab1"> 
        		        <?php echo $this->verticalgrid($this->datagrid)?>
    		            <?php echo $form->autorenew->render() ?>
    		        </div>
        	    
        		    <div class="tab-pane" id="tab2"> 
        		        <ul id="setup">
        			    	<?php foreach ($setup as $service => $item):?>
        			    		<li>
        			    			<h3><?php echo $service ?></h3>
        				    		<?php foreach ($item as $label => $data):?>
        				    			<?php echo $label ?>: <?php echo $data?><br/>
        				    		<?php endforeach; ?>	
        				    	</li>
        			    	<?php endforeach; ?>
    			    	</ul>
    		        </div>
        	    
        		    <div class="tab-pane" id="tab3"> 
        		        <div class="row">
                            <?php echo $this->bbslist($this->messages); ?>
                            <?php echo $form->message->render()?> 
                        </div>
    		        </div>
        	    
    		    </div>
            </div>

			<?php echo $form->detail_id->render()?>
			<p class="text-right"><?php echo $form->submit->render()?></p>
		</form>
	</div>
</div>
