<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"notification error\">".$this->translate('This field') .": <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form id="shineform" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div id="tabs">
		<ul>
			<li><a href="#tab1" class="default-tab current"><?=$this->translate('Main');?></a></li> 
			<li><a href="#tab2" class="default-tab"><?=$this->translate('Details');?></a></li>
			<li><a href="#tab3" class="default-tab"><?=$this->translate('Payments');?></a></li>
			<li><a href="#tab4" class="default-tab"><?=$this->translate('Customer');?></a></li>
			<?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
				<li><a href="#tab5" class="default-tab"><?=$this->translate('Attachments');?></a></li>
			<?php endif;?>
			<li><a href="#tab6" class="default-tab"><?=$this->translate('Messages');?></a></li>
			<li><a href="#tab7" class="default-tab"><?=$this->translate('Private Notes');?></a></li>
		</ul>
    
	    <div id="tab1"> 
		    <fieldset class="column-left"> 
		        <?php echo $form->customer_id->render() ?>
		        <?php echo $form->customer_parent_id->render() ?>
		        <?php echo $form->invoice_id->render() ?>
		        <?php echo $form->order_date->render() ?>
		        <?php echo $form->expiring_date->render() ?>
		        <?php echo $form->fastlink->render() ?>
		        <?php echo $form->visits->render() ?>
		        
		    </fieldset>
		    
		    <fieldset class="column-right">
	            <?php echo $form->isp_id->render()?>
	            <?php echo $form->status_id->render()?>
	            <?php echo $form->is_renewal->render()?>
	            <?php echo $form->cost->render()?>
	            <?php echo $form->setupfee->render()?>
	            <?php echo $form->total->render()?>
	            <?php echo $form->vat->render()?>
	            <?php echo $form->grandtotal->render()?>
	            <?php echo $form->received_income->render()?>
	            <?php echo $form->missing_income->render()?>
		    </fieldset>
		    <div class="clear"></div>
	    </div>
   
	   <div class="ui-tabs-hide" id="tab2">
            
	        <?php echo $form->categories->render()?>
            
            <div class="productslist" style="display:none" id="detail1">
	            <?php echo $form->products->render()?>
            </div>
            
            <div class="billingcycle" style="display:none" id="billingcycle">
            	<?php echo $form->billingcycle_id->render()?>
            </div>
            
            <div class="domain" style="display:none" id="detail2">
                <p id="domainsearchph"><?php echo $form->searchdomains->render()?>
                <p id="domainph"><?php echo $form->domains->render()?>
                <a id="add" class="button"><?php echo $this->translate('Add')?></a> <a id="remove" class="button"><?php echo $this->translate('Remove')?></a>
                <p id="domainselph"><?php echo $form->domains_selected->render()?>
            </div>
            
            <div class="generic" style="display:none" id="detail3">
                <?php echo $form->referdomain->render()?>
	            <?php echo $form->quantity->render()?>
	            <?php echo $form->description->render()?>
	            <?php echo $form->price->render()?>
            </div>
            
            <br>
            <?= $this->simplegrid($this->ordersdatagrid);?>
	   </div>
	   
	   <div class="ui-tabs-hide" id="tab3">
	   		<?= $this->simplegrid($this->paymentsdatagrid);?>
	   		<br/>
            <?php echo $form->paymentdate->render()?>
            <?php echo $form->bank_id->render()?>
            <?php echo $form->reference->render()?>
            <?php echo $form->confirmed->render()?>
            <?php echo $form->income->render()?>
            <?php echo $form->payment_description->render()?>
	   </div>
	   
	   <div class="ui-tabs-hide" id="tab4">
	        <?= $this->verticalgrid($this->customer);?>
	   </div>
	   
	   <?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
		   <div class="ui-tabs-hide" id="tab5">
	            <?= $this->simplegrid($this->filesgrid);?>
	            <?php echo $form->filecategory->render()?>
	            <?php echo $form->attachments->render()?>
		   </div>
		<?php endif;?>
		
	    <div class="ui-tabs-hide" id="tab6">
            <?php echo $this->bbslist($this->messages); ?>
            <?php echo $form->message->render()?>
	   </div>
	   
	    <div class="ui-tabs-hide" id="tab7">
	        <?php echo $form->note->render()?>
	   </div>
	   
	   <?php echo $form->order_id->render()?>
	</div>
	
</form>
</div>
