<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<?php echo $this->render('partials/formerrors.phtml'); ?>

<form id="shineform" enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li><a data-toggle="tab" href="#tab1" class="default-tab current"><?php echo $this->translate('Main');?></a></li> 
			<li><a data-toggle="tab" href="#tab2" class="default-tab"><?php echo $this->translate('Details');?></a></li>
			<li><a data-toggle="tab" href="#tab3" class="default-tab"><?php echo $this->translate('Payments');?></a></li>
			<li><a data-toggle="tab" href="#tab4" class="default-tab"><?php echo $this->translate('Customer');?></a></li>
			<?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
				<li><a data-toggle="tab" href="#tab5" class="default-tab"><?php echo $this->translate('Attachments');?></a></li>
			<?php endif;?>
			<li><a data-toggle="tab" href="#tab6" class="default-tab"><?php echo $this->translate('Messages');?></a></li>
			<li><a data-toggle="tab" href="#tab7" class="default-tab"><?php echo $this->translate('Private Notes');?></a></li>
			<li><a data-toggle="tab" href="#tab8" class="default-tab"><?php echo $this->translate('Status History');?></a></li>
		</ul>
    	<div class="tab-content">
		    <div class="tab-pane" id="tab1"> 
			    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12"> 
			        <?php echo $form->customer_id->render() ?>
			        <?php echo $form->customer_parent_id->render() ?>
			        <?php echo $form->invoice_id->render() ?>
			        <?php echo $form->order_date->render() ?>
			        <?php echo $form->expiring_date->render() ?>
			        <?php echo $form->fastlink->render() ?>
			        <?php echo $form->visits->render() ?>
			    </div>
			    
			    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
		            <?php echo $form->isp_id->render()?>
		            <?php echo $form->status_id->render()?>
		            <?php echo $this->status($this->statushistory);?>  
		            <?php echo $form->is_renewal->render()?>
		            
		            <fieldset class="alert alert-warning">
    		            <div class="col-lg-6">
    			            <?php echo $form->cost->render()?>
    			            <?php echo $form->profit->render()?>
    			            <?php echo $form->received_income->render()?>
    			            <?php echo $form->missing_income->render()?>
    			        </div>
    			        
    			        <div class="col-lg-6">
    			        	<?php echo $form->setupfee->render()?>
    			        	<?php echo $form->total->render()?>
    			            <?php echo $form->vat->render()?>
    			            <?php echo $form->grandtotal->render()?>
    			        </div>
    			    </fieldset>
			    </div>
			    
		    </div>
	   
		   <div class="tab-pane" id="tab2">
		       <h5><?php echo $this->translate('Attach a new service or product to this order') ?></h5>
		       <fieldset class="alert alert-warning">
                    <div class="row">
        	            <div class="col-lg-6 col-xs-12" >
        		            <?php echo $form->categories->render()?>
        	            </div>
        	            
        	            <div class="productslist col-lg-6 col-xs-12" id="detail1">
        		            <?php echo $form->products->render()?>
        	            </div>
                    </div>
                    
                    <div class="row">
        	            <div class="col-lg-6 col-xs-12" id="billingcycle">
        	            	<?php echo $form->billingcycle_id->render()?>
        	            </div>
        	            
        	            <div class="col-lg-6 col-xs-12" id="detail2">
        	                <?php echo $form->referdomain->render()?>
        	            </div>
                    </div>
	            </fieldset>
	            
	            <h5><?php echo $this->translate('Add one or more domains to this order') ?></h5>
	            <fieldset class="alert alert-warning">
	                <?php echo $form->domains_selected->render()?>
	            </fieldset>
	            <div class="generic" id="detail3">
		            <?php echo $form->quantity->render()?>
		            <?php echo $form->description->render()?>
		            <?php echo $form->price->render()?>
	            </div>
	            
	            <br>
	            <?php echo $this->simplegrid($this->ordersdatagrid);?>
		   </div>
		   
		   <div class="tab-pane" id="tab3">
		       <h5><?php echo $this->translate('Attach a new payment transaction to the order') ?></h5>
		   		<fieldset class="alert alert-warning">
			   		<div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
			   			<?php echo $form->paymentdate->render()?>
			            <?php echo $form->income->render()?>
			            <?php echo $form->confirmed->render()?>
			   		</div>
			   		
			   		<div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
				   		<?php echo $form->bank_id->render()?>
			            <?php echo $form->reference->render()?>
			            <?php echo $form->payment_description->render()?>
			   		</div>
			   	</fieldset>
			   	
			   	<?php echo $this->simplegrid($this->paymentsdatagrid);?>
		   </div>
		   
		   <div class="tab-pane" id="tab4">
		        <?php echo $this->verticalgrid($this->customer);?>
		   </div>
		   
		   <?php  if(false == Shineisp_Commons_Utilities::isAppleClient()): ?>
			   <div class="tab-pane" id="tab5">
			       <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
		                <?php echo $form->filecategory->render()?>
		                <div class="alert alert-info"><?php echo $this->translate('Add your file categories from this link')?> <a href="/admin/filecategories"><?php echo $this->translate('File categories')?></a></div>
		                <?php echo $form->attachments->render()?>
		           </div>
		           <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
		               <?php echo $this->simplegrid($this->filesgrid);?>
			       </div>
			   </div>
			<?php endif;?>
			
		    <div class="tab-pane" id="tab6">
	            <?php echo $this->bbslist($this->messages); ?>
	            <?php echo $form->message->render()?>
		    </div>
		   
			<div class="tab-pane" id="tab7">
		    	<?php echo $form->note->render()?>
			</div>
	
			<div class="tab-pane" id="tab8">
		    	<?php echo $this->simplegrid($this->statushistorygrid); ?>
			</div>
	
		   
		   <?php echo $form->order_id->render()?>
		</div>
	</div>
</form>

