<?php 
	$isp = Isp::getActiveISP(); 
	$ns = new Zend_Session_Namespace ();
?>

<div class="row">
	<div class="large-5 columns">
		<?php if(!empty($ns->customer)): ?>
			<a href="/dashboard" class="iconSmallClient">
				<strong>
					<?php if($ns->customer['sex'] == "F"): ?>
						<?php echo $this->translate('Welcome Mrs. %s', $ns->customer['lastname'])?>
					<?php elseif($ns->customer['sex'] == "M"): ?>
						<?php echo $this->translate('Welcome Mr. %s', $ns->customer['lastname'])?>
					<?php else: ?>
						<?php echo $this->translate('Welcome %s', $ns->customer['lastname'])?>
					<?php endif; ?>
				</strong>
				</a>
		<?php else: ?>
			<a href="/customer/login" class="iconSmallClient"><strong><?php echo $this->translate('Login or Create a new Account')?></strong></a>
		<?php endif; ?>
	</div>
	
	<div class="large-4 columns">
		<?php echo $this->cart()?>
	</div>
	
	<div class="large-3 columns right">
		<?php echo $this->searchbar()?>
	</div>

</div>