<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>

<div class="content_inner">

<?php if(!empty($this->mex)) :?>
    <div class="notification <?php echo  $this->mexstatus; ?>"><?php echo $this->translate($this->mex);?></div>
<?php endif;?>
    
<? if( $form->isErrors() ): ?>
	<div class="messages">    
	   <? foreach( $form->getElements() as $field){
	         $errors = array();
	   	     if($field->hasErrors()){
	        	foreach( $field->getErrors() as $error){
	        		$errors[] = $this->translate($error);
	        	}
	            echo "<div class=\"alert alert-error\">".$this->translate('field') ." <b>". $field->getLabel() . "</b> " . implode(" - ", $errors) . "</div>";
	        }   
	    } ?>
	</div>    
<? endif; ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<p align="right">
	  	<?php echo $form->save->render()?>
	</p>	
	
	<div class="tabbable" id="tabs">
		<ul>
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
		</ul>
    
	    <div class="tab-pane active" id="tab1"> 
            <?php echo $form->request_path->render()?>
            <?php echo $form->target_path->render()?>
            <?php echo $form->category_id->render()?>
            <?php echo $form->product_id->render()?>
            <?php echo $form->temporary->render()?>
            <?php echo $form->description->render()?>
    	</div>
   		<?php echo $form->url_rewrite_id->render()?>
   	</div>
</form>

</div>