<?php $form = $this->form; ?>

<?php  // Here the common header will be render ?>
<?php echo $this->render('partials/headers.phtml'); ?>
<?php echo $this->render('partials/formerrors.phtml'); ?>

<form enctype="multipart/form-data" method="<?php echo $form->getMethod() ?>" action="<?php echo $form->getAction()?>">
	
	<div class="tabbable" id="tabs">
		<ul class="nav nav-tabs">
			<li><a data-toggle="tab" href="#tab1"><?php echo $this->translate('Main');?></a></li> 
		</ul>
		
        <div class="tab-content">
    	    <div class="tab-pane" id="tab1"> 
                <?php echo $form->request_path->render()?>
                <?php echo $form->target_path->render()?>
                <?php echo $form->category_id->render()?>
                <?php echo $form->product_id->render()?>
                <?php echo $form->temporary->render()?>
                <?php echo $form->description->render()?>
        	</div>
       		<?php echo $form->url_rewrite_id->render()?>
       	</div>
   	</div>
</form>